### ISSUE TITLE
Add Default NSSAI and a dropdown for Network Type in Subscriber Addition Screen on NMS dashboard.

### ISSUE THREAD

**Issue by pmishra-wavelabs** [magma/magma#8631] opened 2021-08-13 07:39 UTC
Subscriber Addition Screen
1) checkbox for Default NSSAI (Will be disable if EPC selected)
2) Dropdown For Network type : 5GC(5G) and EPC(4G)

**Comment by anusha-konda** [comment] 2021-09-09 06:08
Duplicate of #8787, hence closing the issue.

**Closed as completed by anusha-konda** 2021-09-09 06:08 UTC
Labels: product: 5g sa
