### ISSUE TITLE
[Regression Testing] Tc1d is failing on daily regression test suit.

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#10028] opened 2021-11-02 10:19 UTC
TC1d(SA_TC1d_Concurrent_SUCI_Registration_with_2_UE__Mix_of_Valid_+_Invalid_UE_Reg) is failing on daily regression setup.
I executed manually in our setup i.e 140server. Testcase is passing.
Compared both the pcaps, observed that in failed scenario registration reject msg is not seen for the invalid UE in the first attempt. so it went for a retry and received registration reject msg with the reason illegal UE.

could you please let us know the exact scenario and passing criteria for the test case.
please find the passing and failing pcaps 
[https://app.zenhub.com/files/170803235/a9762983-6567-4584-9a09-f95999918d06/download](https://app.zenhub.com/files/170803235/a9762983-6567-4584-9a09-f95999918d06/download)[https://app.zenhub.com/files/170803235/8bb3ec66-908e-469e-8926-6f5f6e7d2c8f/download](https://app.zenhub.com/files/170803235/8bb3ec66-908e-469e-8926-6f5f6e7d2c8f/download)

**Comment by arun-magma** [comment] 2021-11-05 06:11
Need to check why reject msg is not seen for the invalid UE in the first attempt ? , 
Anyways will check to include in retry rejects for verdict in scripts.

**Comment by shanjanaWL** [comment] 2021-11-05 11:53
Executed TC1d in 141server. Testcase is failing due to subscriberdb is not coming up, which is causing retrying of registration requests. Please find the pcaps and logs below 
[https://app.zenhub.com/files/170803235/f4b13856-28b6-4b18-bb92-0d9587a79fee/download](https://app.zenhub.com/files/170803235/f4b13856-28b6-4b18-bb92-0d9587a79fee/download)
[https://app.zenhub.com/files/170803235/179c17a9-f84a-4fae-b5fa-7ab1bc5d493a/download](https://app.zenhub.com/files/170803235/179c17a9-f84a-4fae-b5fa-7ab1bc5d493a/download)

**Comment by arun-magma** [comment] 2021-11-16 07:56
First invalid UE Registration fails with no response and on retry we get expected error Cause-3 and there is a pkt loss of more than 10% found for 100 Pkts.

**Comment by NeelimaKalpana** [comment] 2021-11-17 08:33
Hi Arun, 

I Will execute the test case and update the status .

**Comment by NeelimaKalpana** [comment] 2021-12-01 16:58
Hi Arun ,
I checked TC1d failure logs, I will discuss with developers and I will update the same with you. This TC1d is passing on individual run.

**Comment by rupa455wavelabs** [comment] 2021-12-09 05:54
TC1d is passing when we run it individually, it's failing in the suit due to pdu session retry.

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/13217bf5-06ff-482f-a022-c807f7624147)

**Comment by arun-magma** [comment] 2021-12-09 06:09
Hi @rupa455wavelabs : This issue is still open due to this PDU Request no answer issue, kindly escalate for the fix

**Comment by rupa455wavelabs** [comment] 2021-12-09 06:13
sure @arun-magma, I will escalate for the fix and update it.

**Comment by rupa455wavelabs** [comment] 2022-03-10 04:36
Closing the issue, as TC1d is passing in daily regression suit.

**Closed as completed** 2022-05-05 11:10 UTC
Labels: wontfix, product: 5g sa
