### ISSUE TITLE
[AMF]: Sentry issue Fatal Error: SIGSEGV /SEGV_MAPERR

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#11255] opened 2022-01-24 06:52 UTC
https://sentry.io/organizations/lf-9c/issues/2948359076/?project=5754002&query=is%3Aunresolved

**Comment by Neudrino** [comment] 2022-02-02 11:23
Potential duplicate of https://github.com/magma/magma/issues/9586?

**Closed as completed** 2022-03-26 13:11 UTC
Labels: type: bug, wontfix, component: agw, priority: high, product: 5g sa
