### ISSUE TITLE
[Proposal] A strategy for safe configuration presence validation

### ISSUE THREAD

**Issue by electronjoe** [magma/magma#8991] opened 2021-09-08 12:40 UTC
## Summary

Magma uses mconfig protobuf definitions to enable runtime configuration of various behaviors.

The mconfig definitions declare a proto3 versioning.

The proto3 API does not support native type detection of protobuf field presence, there are no `has_<field>()` functions provided.  Instead every field will return its default value if queried.  This is a dangerous property for configuration data, as it makes detection of field omission quite fragile (or impossible, depending upon valid field values and proto3 defaults). For a thorough discussion of the dangers and pitfalls - and recognition that proto3 had a design flaw here - see this [Protoc design doc proposal](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md#how-to-enable-explicit-presence-in-proto3).

Scanning through the code base, I can find regular occurrences in which an mconfig field is used without validation of presence - possibly resulting in undefined or undesirable behavior should the mconfig on disk be incorrect (due to human edit, corruption, etc). Further, this generally means that every mconfig proto field is required for healthy operation (if the field is used in whatever mode the instance is running in).

## Solution

Proto3 has recently (as of [release notes](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0) of `3.15`) enabled annotating fields as optional. For a very thorough discussion see [How to enable explicit presence in proto3](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md#how-to-enable-explicit-presence-in-proto3) from the associated protoc design doc proposal for the proto3 `optional` annotations. Compilers prior to `3.15` can also support proto3 optional fields by use of the `-experimental_allow_proto3_optional` protoc flag (back to protoc version `3.12.0`).

Here is an example.

```proto
syntax = "proto3";
package example;
message Msg {
  optional int32 foo = 1;
}
```

```c++
Msg m = GetProto();
if (m.has_foo()) {
  // Clear the field:
  m.clear_foo();
} else {
  // Field is not present, so set it.
  m.set_foo(1);
}
```

It's worth noting that in Go this results in `proto2` like behavior in which the field must be compared with `nil` to determine presence. I know this is not preferred by @markjen but seems to have been done to be compatible with proto2 heritage. For protoc outputs across languages see [documented examples in the feature's protoc proposal design doc](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md#using-the-generated-code).

```golang
m := GetProto()
if m.Foo != nil {
  // Clear the field:
  m.Foo = nil
} else {
  // Field is not present, so set it.
  m.Foo = proto.Int32(1)
}
```

## Alternatives

A couple alternatives were considered, including storage of configuration data as proto2 (which enables concrete presence detection) or use of explicit presence in proto3 by use of `OneOf` fields with default proto3 values of an Enum which indicates absence of the field e.g.

```proto
syntax = "proto3";
package example;

enum Absent {
  ABSENT = 0;
}

message Msg {
  OneOf {
    Absent absent = 1;
    int32 foo = 2;
  }
}
```

**Comment by electronjoe** [comment] 2021-09-08 13:00
I'm concerned that - possibly - the path through e.g. Swagger could completely negate any improvements in proto-based presence detection. E.g. our auto-generated Swagger <-> proto code could either be knowledge-free of optional fields, or could generally set fields to the default values if unset - ruining any improvements in our proto annotations.

Needs exploration / explanation by those in the know.

**Comment by electronjoe** [comment] 2021-09-08 13:09
It also appears my knowledge is fairly far off base, in that YAML files appear to be written by the config sync from Orc8r -> AGW per [Documentation Here](https://docs.magmacore.org/docs/lte/dev_notes).  I must say I'm now completely confused as to what is going on w.r.t. configuration at Magma. Are we translating protoc definitions into YAML files and swagger UIs? Why would we voluntarily generate YAML on disk instead of storing the string rerpresentations of the protobufs? This is not achieving [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and jointly limits our ability to migrate to better practices.

**Comment by electronjoe** [comment] 2021-09-08 14:55
I also now spot [mconfigs being read as JSON format](https://sourcegraph.com/github.com/magma/magma/-/blob/orc8r/gateway/python/magma/configuration/mconfig_managers.py?L192-217)... ?

**Comment by markjen** [comment] 2021-09-08 15:22
1. The core issue in #8978 is the code does not properly handle a zero value. Normal/new behavior is a zero value should become a default value and documented as such. In this example, if a "continuous sync" mode is desired, that should be a separate setting that invalidates `sync_interval`. (`sync_interval` == 0 is ambiguous. Should this mean: unset use a sane default, sync continuously, or do not sync at all)

2. Proto2 would not save us by default (again, the issue here is not checking/handling the 0 value in our code). Consumers of proto2 codegen typically end up using the accessor methods (e.g. `GetSyncInterval() uint32`) or in Python, will receive the default value for the field when it is unset.

3. There is (was?) a desire to use YAML as a config format. I prefer JSON since it's well known and directly parseable by libs including protobuf. Note that modern tools, e.g. VSCode, use JSON as a config language. Lastly, JSON does not support inline comments by default (and by design); but most libs allow C-style comments or a pre-processor can be setup pre-parse.

See also https://en.wikipedia.org/wiki/YAML#Criticism (some of these cases I have run into in production)

4. Something to follow up on is whether we can remove Swagger entirely given we already use protobuf/grpc everywhere else.

**Comment by hcgatewood** [comment] 2021-09-16 18:56
@markjen @electronjoe 

I have strong feelings about this topic and am willing to write up and end-to-end design for our configs story if desired, just let me know

- (1) Checking whether config exists. I actually think we should *not* be doing this. The gateways should not have to decide anything -- we are going with "smart controller, dumb gateway" as much as possible (among other benefits, this makes it easier to make backward-compatible changes). So, the solution here is that Orc8r should fully specify the mconfigs it sends down, and *never* omit a value
- (1a) Of course this still leaves open the question of "is the zero value zero, default, or sentinel." Per (1), we can rule out default, cause then controller should just send the default. Similarly, sentinel is a bad pattern because you should just use an additional field. So, then, zero -> zero is the logical choice imo
- (2) I'm planning to have my intern (starting next week) handle an experimental upgrade to the Orc8r configs. If it goes well, we can use it as the pattern for a larger improvement to the end-to-end configs story. Ref: https://fb.quip.com/WwLhAUmEv73Y

**Comment by electronjoe** [comment] 2021-09-17 09:52
When I wrote this proposal I didn't yet have a full picture of the configuration landscape at Magma. I'm in agreement with ~everybody that the bigger picture needs revision.

@markjen and @hcgatewood maybe we need to meet quick to ensure nobody is doing duplicate work / ideas are subject to an early volley of feedback before anything too detailed pops out?

- (1) If we are going to have `smart controller, dumb gateway` - which does sound appealing with respect to system complexity
  - We are going to have to make it much easier to plumb new configurations (e.g. feature flags) all the way through magma [presently a 160 LOC effort](https://github.com/magma/magma/pull/8143)
  - Do we need to consider testing complexity of requiring an Orc8r? I do not know if this is done, but I could envision people being happy running just AGW daemons to test e.g. datapath interaction in linux, and not wanting to require an Orc8r (perhaps this just needs planning as to an approach for injection by command line / fake from Orc8r?).
- (1a) `controller should just send the default.` -> I personally don't like checking against a slew of default values to see if a field was set - it feels like sentinel value checking to me. And by slew I mean `ok this is an int, so I check against zero.. this is a string I check against ""... this is a boolean I check against false, etc`.  Boolean is particularly troubling. So your flag can only be True. If it's False you don't know if it was omitted accidentally or if it was False...
- (2) Just worried that your efforts and Marks may be colliding (with Golang experiments in AGW) - you two should talk (or we three should talk) and make sure duplicate effort isn't going on

**Comment by hcgatewood** [comment] 2021-09-29 04:33
@electronjoe 

1. Agreed it's too difficult right now. The solution is we have to get away from swagger for our data models 🙂 This is one of the things that is too big to take on with our current Orc8r headcount
2. "Controller should send the default" by that I mean the semantically-default value (e.g. 42) rather than the protobuf-default value (e.g. 0)
3. Agreed. @markjen and I will sync, along with @reginawang3495, before she gets to that part of her project plan 🙂

**Comment by hcgatewood** [comment] 2021-09-29 04:34
Closing for now for lack of concrete actionable. Can re-open when we have a specific strategy

**Closed as completed by hcgatewood** 2021-09-29 04:34 UTC
Labels: type: proposal
