### ISSUE TITLE
[CI/CD] Make master more stable

### ISSUE THREAD

**Issue by mattymo** [magma/magma#3564] opened 2020-10-31 07:23 UTC
We have a few approaches we need to consider and try to implement:
1. Implement conditional test jobs in CI to run fewer tests per-commit (try only to test components that actually changed in PR)
2. make Jenkins faster
3. play around with tags more

**Comment by mattymo** [comment] 2020-10-31 07:37
@ttx @119Vik  @ssanadhya @amarpad  Please feel free to elaborate on the above issues and suggest what approach we should take.

**Comment by mattymo** [comment] 2020-11-01 09:53
@119Vik recently made some Jenkins improvements:
    component: agw  triggers LTE_integ pipeline and magma_integration_tests ( which came from OAI)
    component: agw , component: feg , component: cwf  triggers CWAG_integ pipeline

**Comment by ttx** [comment] 2020-11-03 12:22
Could you expand on what you mean by "speculative CI to run lighter tests per-commit" ?

In my book, speculative CI (think zuul-ci.org) is using speculative execution to parallelize strict gating: first, making sure that master does not get broken at merge time (like a regression due to something that merged since last tests ran), and second, using speculative execution in the gating pipeline to parallelize tests so that such strict gating does not result in a huge backlog.

While implementing such a solution would definitely make master more stable, I'm not sure any of those would result in "running lighter tests per-commit", so I suspect we may be talking about two different things.

**Comment by mattymo** [comment] 2020-11-04 07:04
@ttx I meant a way to enable given tests based on which files in the git repository changed in a Pull Request. For example, don't run cwag precommit for PRs that only modify documentation. If there's a better way to define this kind of tests, I'd be happy to update the wording.

**Comment by ttx** [comment] 2020-11-04 15:29
Oh ok, we'd call that conditional test jobs.

Other question: what would you say is the key issue you need to solve:
- Testing delays (tests take forever to run and report results)
- False positive results (tests incorrectly reporting success) introducing regressions in master branch
- False negative results (tests incorrectly reporting failure) triggering a lot of retests and delays
- Regressions at code merge time (change passes tests but merging with recently-introduced changes creates regressions)
- Platform instability (CI platform itself breaks and is inaccessible)

If I read your solution list correctly, it seems it's the first one ?

**Comment by 119Vik** [comment] 2020-11-05 13:50
Some stats I was able to collect from so far :
Infra:
- Baremetall hosts: 2 
- Jenkins Staves: 13 of 16 possible (+3 VMs we can create at BM node where we run magma_integration_tests) 
- Total Executions per day: 6-30 

We have 3 Pipelines:
**CWAG Group** 
https://jenkins.magmacore.org/job/CWAG-integration-test/

- Executions per day: 2-10 
- Execution example: https://jenkins.magmacore.org/blue/organizations/jenkins/CWAG-integration-test/detail/CWAG-integration-test/203/pipeline
- Total Execution Time: 71 minutes
- Start and configure VMs: 50 minutes
- Run Tests: 14 minutes

**LTE  Group**
_Notes:_ 

1. Following 2 pipelines transferred to community from OAI Jenkins and FB CircleCi. 
LTE-integration-test is Duplicate 50% of the magma_integration_tests so it make sense to rework them. Possible Options:
- Exclude "LTE-integration-test" tests from magma_integration_tests so we have 2 isolated pipelines without duplications.
- Merge them into 1 so we we have single pipeline without duplications
- Other. Split them in to 5-10 pipelines where each pipeline performs 1/n of all AGW tests.
2. Implemented optimisations :
- magma_integration_tests uses Jenkins parallel task execution for optimisation
- LTE-integration-test - is mostly consists of single Python Fabric script which is executing each and every action sequentially

https://jenkins.magmacore.org/job/magma_integration_tests/
- Executions per day: 2-10
- Execution example: https://jenkins.magmacore.org/blue/organizations/jenkins/magma_integration_tests/detail/magma_integration_tests/1245/pipeline
- Total Execution Time: 62 minutes
- Start and configure VMs: ~5 minutes
- Run Tests: 52 minutes 

https://jenkins.magmacore.org/job/LTE-integration-test/

- Executions per day: 2-10
- Execution example: https://jenkins.magmacore.org/blue/organizations/jenkins/LTE-integration-test/detail/LTE-integration-test/155/pipeline
- Total Execution Time: 55 minutes
- Start and configure VMs: ~40 minutes (
~7 minutes - Ansible 
~23 minutes - cmake  magma/lte/gateway/c/oai -DCMAKE_BUILD_TYPE=Debug  -DS6A_OVER_GRPC=True -DEMBEDDED_SGW=True -DENABLE_OPENFLOW=True -DSPGW_ENABLE_SESSIOND_AND_MOBILITYD=True -GNinja
~3 minutes - cmake  magma/lte/gateway/c/session_manager -DCMAKE_BUILD_TYPE=Debug   -GNinja
)
- Run Unit Tests: ~16 minutes 
- Run Integ Tests: Not started because of "Unable to load SSH config file '/home/jenkins/.ssh/config'"

**Comment by 119Vik** [comment] 2020-11-05 14:07
Some thoughts:
- Having 2 pipelines which partially duplicate each other in the LTE group is waste of resources.
- Why don't do tasks in parallel if they do not depend on each other
- Do "All things" in single Fab Script is
   - less transparent
   - hard to measure timing
   - sub optimal
- As a result of Opt-In strategy implementation our Jenkins infra seems to be under utilised now
- In case of magma_integration_tests - we may split tests in to 10 groups each of which will be performed in the separate env so we will allocate 10 VMs each of which will spend ~10 minutes (5 to setup VM + 5 to do tests)  
Or 5VMs x 15Minutes 
Or other option 
- Most of the PRs are coming from the US timezone - so Jenkins is busy ~50% of time Monday-Friday and 100% spare during the weekend. We can schedule more tests against master / RC branch / for the US nights and weekends.

**Comment by 119Vik** [comment] 2020-11-05 14:17
Most of the PRs are coming from the US timezone - so Jenkins is busy ~50% of time Monday-Friday and 100% spare during the weekend. We can schedule more tests against master / RC branch / <you name it> for the US nights and weekends.

**Comment by amarpad** [comment] 2020-11-05 15:30
I think we are missing a proposal here to run the full integration tests "CWF + LTE" on all accepted patches.

**Comment by amarpad** [comment] 2020-11-05 15:33
ok lets start at the top:
1 - Master is unstable because we are not running all integration tests on all PRs.
2 - The reason for that is that it is taking too long to run all integration tests on all PRs, and opt in opt out tags while great are still sub optimal as in the end state we want the integration tests to run on all PRs that is the whole point of the integration tests.
3 - There are two ways to match this, speed up the pipeline so supply of test resources match the demand of runs or reduce supply (which is to only run all CI tests on accepted patches)

**Comment by ttx** [comment] 2020-11-05 16:08
Thanks @amarpad, that makes sense. So the issue is not test coverage, but rather that in order to reduce the time it takes to get test results, there is an optimization on what tests run in each case, which ends up defeating the purpose of integration testing and introduces regressions in master.

I agree with the two directions you suggest, and choice between them is about how much test resources you have at your disposal. It feels like parallelizing the build steps and then parallelizing the tests in a single pipeline would speed things up significantly and avoid wasting resources building the same things over and over again, to the point where running tests on all patchsets (pre-approval) would be doable. If not, running full integration only on accepted patches is one way to work around it.

**Comment by mattymo** [comment] 2020-11-05 17:46
@119Vik I think what you left out is CWAG wastes a lot of time doing setup and we could probably take 15 minutes off that test time by improving the base VM image. What's good from these results is that magma-integration-tests and LTE tests have no such waste. All we can do from that end is to figure out a better strategy to run serially-configured tests:
1 - run some tests in parallel that can be grouped together
2 - break up tests into different groups but still run serially and run them in separate jobs spread out across different VMs and/or bare metal
3 - figure out if we can make these tests run faster by optimizing their internal logic

**Comment by amarpad** [comment] 2020-11-05 19:18
https://github.com/magma/magma/pull/2806/commits/616965036364fe47200c2069ffe5e7722abf0688

This was the proposal from @tmdzk

**Closed as completed** 2022-03-17 13:30 UTC
Labels: wontfix
