### ISSUE TITLE
sanity test suite is not running continuously 

### ISSUE THREAD

**Issue by rsarwad** [magma/magma#13767] opened 2022-08-29 10:48 UTC
sanity test suite is not running continuously because test case, test_attach_nw_initiated_detach_with_mme_restart.py is  not clearing state information. So any subsequent test case executed results into failure.  

### Your Environment

- **Version:**
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** mme service
- **Deployment Environment:**  Vagrant (AGW)

### Describe the Issue
sanity test suite is not running continuously because test case, test_attach_nw_initiated_detach_with_mme_restart.py is  not clearing state information. So any subsequent test case executed results into failure.

#### To Reproduce
First execute test_attach_nw_initiated_detach_with_mme_restart.py and then execute test_attach_detach_multiple_ip_blocks_mobilityd_restart.py which results into failure

**Comment by mpfirrmann** [comment] 2022-10-14 09:18
Hey @rsarwad, 
I took a quick look into this. when I worked on the dockerized AGW. Could this be a race condition between the `mme` restart + waiting 30s to continue and the 3422 timer? This 6s timer T3422 is repeated four times which leads to similar 30s of overall time. Since we modified the restart behavior to accommodate for the containerized AGW, it may take too long of a time to continue after restarting the mme. In the case of a containerized AGW we check for container health instead of a fixed waiting time (which effectively results in ~20s of waiting) and both tests pass continuously. The same is true if I reduce the wait time for the mme to restart to 20s with the `systemd`-based AGW.
The error does not appear in CI since we test for flakiness and `test_attach_detach_multiple_ip_blocks_mobilityd_restart.py` runs green the second time.

**Comment by rsarwad** [comment] 2022-10-14 10:20
Hi @mpfirrmann,
Thanks for looking into the issue. I still see this issue in my vagrant setup. Looks like there is some at s1ap tester because after mme restarts mme re-transmits Detach Request but s1ap is not responding immediately, Detach Accept is sent after releasing the S1 signaling connection. Please find the snippet of Wireshark capture. 
[Nw_Init_Detach_Req.zip](https://github.com/magma/magma/files/9784934/Nw_Init_Detach_Req.zip)

Let me rebase s1ap tester code base and try

**Comment by rsarwad** [comment] 2022-10-14 11:57
Even after rebasing it's the same issue. The issue is in both s1ap tester and mme service. 
Issue at s1ap tester: It's not responding to Detach request sent after mme restarts
Issue at mme service: After final expiry of 3422 timer, mme should clear all the contexts relevant to that UE and also update the same to DB.

**Comment by nstng** [comment] 2023-01-02 07:19
I can not reproduce this - locally this is working for me and the tests are running, in the order given in the "To Reproduce" section, successfully in CI. I will close this issue for now - feel free to re-open with updated information if I missed something.

**Closed as completed by nstng** 2023-01-02 07:19 UTC
Labels: type: bug
