### ISSUE TITLE
Replace `save-state` and `set-output` by new environment files

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#14149] opened 2022-10-13 07:07 UTC
For details to the why and how, see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

As to the where: Everywhere in CI.

**Comment by voisey** [comment] 2022-10-14 15:57
Closing this as duplicate of https://github.com/magma/magma/issues/14146

**Closed as completed by voisey** 2022-10-14 15:57 UTC
Labels: good first issue, component: ci
