### ISSUE TITLE
TVM Scale Test: IdleMode to Active Transition

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11030] opened 2021-12-30 12:41 UTC
magma build version: 1.7.0-1640745493-d0ca0d93

Executed scale test scenario's for IdleMode to Active Transition TC: 

1. SA_TC2c_Verify_Idle_and_Active_Mode_transition_with_Multi_PDU_session -
100 UE, 12 GNB, SUCI Registration, Single PDU Sessions Idle/Active MO & traffic - All the 100 UE's are transitioning between IdleMode and Active Mode - Testcase is failing due to UL/DL packet drop issue.

2.  SA_TC2c_Verify_Idle_and_Active_Mode_transition_with_Multi_PDU_session -
200 UE, 12 GNB, SUCI Registration, Single PDU Sessions Idle/Active MO & traffic - All the 200 UE's are transitioning between IdleMode and Active Mode - Testcase is failing due to UL/DL packet drop issue.

Please check the logs and pcaps for more information: 
https://drive.google.com/drive/folders/1ScqgUbEuIucfSe3I54S1jiMeW3-bJXeP

**Comment by Kaleem-Wavelabs** [comment] 2022-01-13 19:10
@rupa455wavelabs 

Close this as the root cause is same as #11021 and #11022

**Comment by rupa455wavelabs** [comment] 2022-01-18 11:15
Executed the TC with latest magma code and observed an issue with service accept, Please check the attached logs and pcaps for reference.
[https://app.zenhub.com/files/170803235/992b3cdf-12f5-4758-b030-42832d7d1f83/download](https://app.zenhub.com/files/170803235/992b3cdf-12f5-4758-b030-42832d7d1f83/download)

![2c_200ue.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/53cc768e-93d1-4105-a915-2db2b6b019e3)

![2c_n1_n2_200ue.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/7d8bd9fb-4749-4712-b937-a81283b6b1bc)

![n3_2c_200ue.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/a4672371-36c9-49bb-bcd0-43e115629a9a)

**Comment by rupa455wavelabs** [comment] 2022-03-03 09:19
Need to re-verify it in spirent setup and update the results.

**Comment by rupa455wavelabs** [comment] 2022-03-14 09:13
Hi @all, I re-executed the TC2c scenario(200UE, 5ue/s,1 PDU session), I am observing that out of 200 PDU sessions, 3 PDU session release is not triggered, and  loss in ul/dl traffic. Please check the below screenshots and logs for the reference.
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/b2936afa-3cf7-4fcf-81fd-38ee81696985)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/b17b784b-62c5-4264-8e58-0ed9ecb3c48c)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/e21dbdae-0553-4b0a-a909-77d0de628bf5) 
[https://app.zenhub.com/files/170803235/d9906d0a-c7a8-4d5b-a4a0-f5f868f72f90/download](https://app.zenhub.com/files/170803235/d9906d0a-c7a8-4d5b-a4a0-f5f868f72f90/download)

Verdict Log:
verification fail:  ((nas5g_sent_Service_Req_=200)		 	== (nas5g_received_Service_Acc_=197))  => False
verification fail:  ((as_received_raw_bytes=13046000) 			>= (ue_sent_total_bytes=39697000)-((ue_sent_total_bytes=39697000)*0.01))  => False
verification fail:  ((ue_received_total_bytes=7841000)			>= (as_sent_total_bytes=12697236)-((as_sent_total_bytes=12697236)*0.01))  => False
verification fail:  ((as_received_raw_bytes_40=13046000)			>= (ue_sent_bytes_40=39697000)-((ue_sent_bytes_40=39697000)*0.01))  => False
verification fail:  ((ue_received_bytes_40=4985000)			>= (as_sent_bytes_40=12697236)-((as_sent_bytes_40=12697236)*0.01))  => False
verification fail:  ((nas5g_sent_Sess__Rel__Req_=197)       	>= 200*1*1)  => False
verification fail:  ((nas5g_received_Sess__Rel__Cmd_=197)   	>= 200*1*1)  => False
verification fail:  ((nas5g_sent_Dereg__Req_=197)           	>= 200*1)  => False
verification fail:  ((nas5g_received_Dereg__Acc_=197)       	>= 200*1)  => False

**Comment by panyogesh** [comment] 2022-05-05 11:12
Closing as this will be again tested on Abot framework

**Closed as completed by panyogesh** 2022-05-05 11:12 UTC
Labels: product: 5g sa
