### ISSUE TITLE
IMSI's are shown with session state as SESSION_ACTIVE even after the UE is detached from the network

### ISSUE THREAD

**Issue by Siddharthlende** [magma/magma#12041] opened 2022-03-10 07:29 UTC
Prior to submitting an issue, check to see if one has already been created. If there is currently an open issue, add a thumbs-up emoji to identify that it is also affecting you.

### Your Environment

- **Version: v1.6.1**
- **Affected Component: NMS**
- **Affected Subcomponent: AGW **
- **Deployment Environment: local docker-compose (orc8r), Vagrant (AGW)**

issue Description: IMSI's in subscriber Tab -Sessions showing Active sessions 1 irrespective of UE attached or detached

**To Reproduce**
1. Go to 'NMSUI'
2. Click on 'Subscriber'
3. Navigate to Sessions in Subscriber tab 
4. Find attached Screen shots. Irrespective of UE's state the Active Sessions showing 1.

**Expected behavior**
Active Sessions should be one if the UE attached, and Active Session should be 0 when the UE id detached/Freshly added UE using .csv file.

**Screenshots**
![image](https://user-images.githubusercontent.com/50014969/157610344-a667974a-2ed5-4c86-ae16-08cded79f4b8.png)

**Comment by Bharat0908** [comment] 2022-03-10 08:20
@andreilee please suggest your inputs.

**Comment by sebathomas** [comment] 2022-04-19 15:45
I don't think this is a bug in NMS but there may be something wrong with the way the session state is handled between gateway and orc8r.

As far as I understand, the session state is managed by sessiond inside the gateway and periodically forwarded to the state service on the cloud side (via GetOperationalStates). When that happens, the cloud persists the data in Postgres. NMS only shows what's stored in the DB (the entries in the table "states" with type "subscriber_state").

I am not sure how an entry is cleaned up after a session is no longer active. I think this only happens if the gateway actively sends an update for that IMSI during the periodic state sync. I didn't see any code that cleans up old sessions that are no longer known on the gateway side. Maybe there are cases where an update is missed and then there is a permanently active dead session still in the DB.

I think the basic idea of how it works is explained in this proposal:
https://github.com/magma/magma/blob/master/docs/readmes/proposals/p006_subscriber_state_view.md
Maybe @themarwhal knows more about this?

**Comment by themarwhal** [comment] 2022-04-19 15:53
> I don't think this is a bug in NMS but there may be something wrong with the way the session state is handled between gateway and orc8r.
> 
> As far as I understand, the session state is managed by sessiond inside the gateway and periodically forwarded to the state service on the cloud side (via GetOperationalStates). When that happens, the cloud persists the data in Postgres. NMS only shows what's stored in the DB (the entries in the table "states" with type "subscriber_state").
> 
> I am not sure how an entry is cleaned up after a session is no longer active. I think this only happens if the gateway actively sends an update for that IMSI during the periodic state sync. I didn't see any code that cleans up old sessions that are no longer known on the gateway side. Maybe there are cases where an update is missed and then there is a permanently active dead session still in the DB.
> 
> I think the basic idea of how it works is explained in this proposal: https://github.com/magma/magma/blob/master/docs/readmes/proposals/p006_subscriber_state_view.md Maybe @themarwhal knows more about this?

Hi @sebathomas! Yes, this is more of an issue with Orc8r/AGW rather than NMS. This issue outlines the problem a bit more in detail: https://github.com/magma/magma/issues/8621 . I do not have bandwidth to work on this, but it is open for anyone to pick it up. :)

**Comment by p00jaY** [comment] 2022-04-19 17:03
Hi @sebathomas @themarwhal,
Thanks for your inputs. Debugged in AGW code, AGW side after detaching UE it is changing session state from SESSION_ACTIVE to SESSION_RELEASED and later SESSION_RELEASED to SESSION_TERMINATED it seems it is correct from AGW end. Please find attached screen shots below.
![image(2)](https://user-images.githubusercontent.com/101162794/164056948-a1ab7e71-0259-45b6-acd7-d99d2ee74c43.png)
![image(3)](https://user-images.githubusercontent.com/101162794/164056954-a2c36dc2-c7b4-4006-b027-485c32ecd995.png)

**Comment by p00jaY** [comment] 2022-04-19 17:14
@sebathomas @themarwhal 
Grepped in NMS code i can see only SESSION_ACTIVE state (in magma/nms/app/packages/magmalte/app/views/subscriber/SubscriberStateTable.js,)  
SESSION_TERMINATING and SESSION_TERMINATED are there in mock/db.json  file. 
Attaching screen shot for same. Your inputs are highly appreciable.
![image(4)](https://user-images.githubusercontent.com/101162794/164059019-9f0d78ca-fffb-46f2-90be-a4767ee38f73.png)

**Comment by Siddharthlende** [comment] 2022-04-19 17:23
Hi @sebathomas and @themarwhal ,
Thank you so much for your inputs. Debugged in AGW code after detaching of UE session state is changing from SESSION_ACTIVE to SESSION_RELEASED after some times SESSION_RELEASED to SESSION_TERMINATED. It seems it is correct behavior in AGW end. Please find below screen shots for the same.
![image(2)](https://user-images.githubusercontent.com/50014969/164060266-3eca05f3-71ae-4b73-832d-6a7a4267a275.png)
![image(3)](https://user-images.githubusercontent.com/50014969/164060279-6990da6e-9d6f-40b3-939e-cae9bbc07896.png)

**Comment by Siddharthlende** [comment] 2022-04-19 17:33
@sebathomas and @themarwhal ,
Another thing what i observed is:
In NMS code i can see only the session state SESSION_ACTIVE (magma/nms/app/packages/magmalte/app/views/subscriber/SubscriberStateTable.js file) and i observed SESSION_TERMINATING and SESSION_TERMINATED in mock/db.json file. Please find attached screenshot for same. Your inputs are highly appreciable.
![image(4)](https://user-images.githubusercontent.com/50014969/164062145-812cfc8f-bc01-43d5-94cd-8fbd28425ae7.png)

**Comment by Siddharthlende** [comment] 2022-04-20 05:12
Hi @sebathomas and @themarwhal,
Just now checked session state on NMS still it is showing SESSION_ACTIVE. I detached UE yesterday itself. Please find screenshot attached.
![image(5)](https://user-images.githubusercontent.com/50014969/164155044-fbae7910-3313-4e00-997c-2118e2fec475.png)

**Comment by sebathomas** [comment] 2022-04-20 07:23
> @sebathomas and @themarwhal , Another thing what i observed is: In NMS code i can see only the session state SESSION_ACTIVE (magma/nms/app/packages/magmalte/app/views/subscriber/SubscriberStateTable.js file) and i observed SESSION_TERMINATING and SESSION_TERMINATED in mock/db.json file. Please find attached screenshot for same. Your inputs are highly appreciable.

That's right, NMS only counts subscribers in state SESSION_ACTIVE as active sessions, and doesn't have any logic for the other states. However, they are shown in the frontend if they are stored in orc8r. The problem is that the state update is never forwarded from sessiond to orc8r, and then the stale entry will be shown forever.

**Comment by Siddharthlende** [comment] 2022-04-20 07:46
@sebathomas,
Agree with your points that NMS have only logic for state SESSION_ACTIVE. But what surprised me is: 
Few days back while reproducing this issue, i saw something new like session state got changed from SESSION_ACTIVE to SESSION_RELEASED and active sessions count became 0, hopefully we know on NMS side we have logic for active sessions only. So, still i am in confusion....! Your inputs are highly appreciable...
Please find below attached screen shot. 
![image(6)](https://user-images.githubusercontent.com/50014969/164177134-b59dafa0-1227-4096-9277-9a6422b5b64b.png)

**Comment by sebathomas** [comment] 2022-04-20 07:49
Yeah, that's exactly what the logic does. SESSION_RELEASED doesn't count for the number of active sessions.

I still don't completely understand in what cases the release is forwarded to orc8r and in what cases the state change is lost. It might depend on the timing of the periodic state sync?

**Comment by sebathomas** [comment] 2022-07-13 09:26
With the merge of #13151, this should be fixed on master. Old session states will now be removed the next time the gateway checks in (typically within 1 minute).

**Closed as completed** 2022-09-22 14:19 UTC
Labels: type: bug
