### ISSUE TITLE
[Regression] TC1d behavior is not as per expectations when executed in suit.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10660] opened 2021-12-03 07:42 UTC
Your Environment

- Version: 1.7.0-1638481478-58af1059
- Affected Component: Access Gateway 
- Affected Subcomponent: AGW service

Describe the Issue
AMF is sending identity-request when UE is requesting for SUCI-registration procedure.

**To Reproduce**
This is happening when executing TC1d in suit.

**Expected behavior**
SUCI registration should happen successful.

**Screenshots**
Failure_case
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/814cc390-77ba-444c-a9fe-3a52d53906bb)

Working Case:

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/fc20d811-8a40-4227-8398-e8c848202513)[https://app.zenhub.com/files/170803235/8db49ea2-3c91-44e1-8046-655ff974645e/download](https://app.zenhub.com/files/170803235/8db49ea2-3c91-44e1-8046-655ff974645e/download)

**Comment by moinuddin1980** [comment] 2021-12-06 17:15
Analysis as of today:
The problem is with line no 121 in lte/gateway/c/core/oai/tasks/amf/amf_as.cpp

119) static int amf_as_establish_req(amf_as_establish_t* msg, int* amf_cause) {
120) amf_security_context_t* amf_security_context = NULL;
121) amf_nas_message_decode_status_t decode_status; --> **value is uninitialized**

The above variable decode_status is uninitialized. 
Also, with the initial UE Registration request message we have the message header->security_header_type is SECURITY_HEADER_TYPE_NOT_PROTECTED
Thus, during call to nas5g_message_decode()->nas5g_message_header_decode()
integrity_protected_message field remains unintialized.

As a result of which while processing initial registration request, the existing logic sends an identity request, if  integrity_protected_message is true.

**Comment by moinuddin1980** [comment] 2021-12-10 05:56
PR code changes w.r.t #10660 is already in master with below commit. Hence, closing the ticket.

commit 3a01401
Author: ganeshg87 83060027+ganeshg87@users.noreply.github.com
Date: Fri Dec 10 06:07:16 2021 +0530

**fix(amf): AMF is sending UE Context Release command when there is a unsuccessful PDU session setup (#10453)

* fix(amf): AMF is sending UE Context Release command when there is a unsuccessful PDU session setup**

**Comment by moinuddin1980** [comment] 2021-12-10 05:56
PR code changes w.r.t #10660 is already in master with below commit. Hence, closing the ticket.

commit 3a01401
Author: ganeshg87 83060027+ganeshg87@users.noreply.github.com
Date: Fri Dec 10 06:07:16 2021 +0530

**fix(amf): AMF is sending UE Context Release command when there is a unsuccessful PDU session setup (#10453)

* fix(amf): AMF is sending UE Context Release command when there is a unsuccessful PDU session setup**

**Closed as completed by moinuddin1980** 2021-12-10 05:56 UTC
Labels: type: bug, product: 5g sa
