### ISSUE TITLE
[4G AGW] [4G Orchestrator] NMS changes doesn't reflect in AGW gateway.mconfig file

### ISSUE THREAD

**Issue by Chandrashrathore** [magma/magma#11041] opened 2022-01-03 11:11 UTC
Version: :AGW : 1.6.1-1636529012-5d886707
Affected Component : Orchestrator, Access Gateway
Affected Subcomponent : AGW
Deployment Environment : AWS (orc8r), bare-metal (AGW)

In Orchestrator when we do the changes in JSON Config setting for Disable gx_gy_relay_enabled, hss_relay_enabled it is happing their but in AGW the changes is not reflected then we do forcefully changes done in AGW
( /var/opt/magma/configs/gateway.mconfig ).

Previously it is happening properly but after the Orchestrator updates it is not happening and we do forcefully  in AGW side.
 
![NMS snap.PNG](https://images.zenhubusercontent.com/61bad8f715f837be5855c509/1242db85-bde2-46b8-aa52-217f171e9cb6)![gateway.mconfig snap.PNG](https://images.zenhubusercontent.com/61bad8f715f837be5855c509/7405746c-178a-424d-9296-6a37354fa151)

**Comment by anusha-konda** [comment] 2022-01-05 12:31
Based on the logs, magmad is unable to fetch the updates from Orc8r while accessing nil pointer. The issue is fixed with merge of these PRs #10717 , #10758 . Please update the Orc8r deployment.

**Closed as completed** 2022-03-18 02:31 UTC
Labels: type: bug, wontfix
