### ISSUE TITLE
[DevOps][Artifactory] Change way to set up gpg key in local Vagrant VM

### ISSUE THREAD

**Issue by tmdzk** [magma/magma#4981] opened 2021-02-16 18:57 UTC
Context: 
When we provision the local Vagrant VM with Ansible, we cp from the magma codebase (here)[https://github.com/magma/magma/blob/master/orc8r/tools/ansible/roles/pkgrepo/files/jfrog.pub] the gpg public key and then `apt-key -add`. It's an ok way to automate that however if the gpg key change you need to update it in the codebase and then rerun the provision. Let's fetch it from the artifactory api instead.

What to do: 
Instead of doing a cp from the codebase let's `wget` it from the artifactory endpoint https://facebookconnectivity.jfrog.io/artifactory/api/gpg/key/public

**Comment by ranj8work** [comment] 2021-02-17 23:14
I figured the fix for this issue. Please see details below. I will work on making these changes and make a pull request soon. Please let me know if you have any questions. Thanks !

**In tasks/redhat.yml file**
- name: Add JFrog key
  block:
    - get_url: _# Fix is to replace the "copy" with "get_url" module and put the jfrog path below_
        src: https://facebookconnectivity.jfrog.io/artifactory/api/gpg/key/public
        dest: /tmp/jfrog.pub
    - rpm_key:  
        key: /tmp/jfrog.pub
    - file:
        path: /tmp/jfrog.pub
        state: absent

**In tasks/debian.yml file**
- name: Add JFrog key
  block:
    - get_url:   _# Fix is to add new block "get_url" module and put the jfrog path below_
        src: https://facebookconnectivity.jfrog.io/artifactory/api/gpg/key/public
        dest: /tmp/jfrog.pub 
    - apt_key:
        data: "{{ lookup('file', '/tmp/jfrog.pub') }}"  _# Update the file path_
        state: present

**Comment by ranj8work** [comment] 2021-02-25 01:09
The issue is fixed and the changes are merged to the magma repo. Below is the link of the approved pull request.
https://github.com/magma/magma/pull/5101

**Closed as completed by ranj8work** 2021-02-25 01:09 UTC
Labels: good first issue, workstream: devops
