### ISSUE TITLE
[NMS] AGW health status incorrectly shows as 'BAD' in NMS GUI

### ISSUE THREAD

**Issue by vinayaachar** [magma/magma#7645] opened 2021-06-17 22:00 UTC
### Your Environment

- **Version:** 1.5
- **Affected Component:** NMS
- **Affected Subcomponent:** AGW Health in NMS 
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue
 Customers see AGW health shown as BAD in NMS but becomes good after refreshing the page
Internal Task: T93533003

![Screen Shot 2021-06-17 at 2 58 23 PM](https://user-images.githubusercontent.com/43836914/122477461-99e8d780-cf7c-11eb-89c7-162cd270d49c.png)
![Screen Shot 2021-06-17 at 2 58 40 PM](https://user-images.githubusercontent.com/43836914/122477462-9b1a0480-cf7c-11eb-80f7-a0ec80735f94.png)

**Comment by karthiksubraveti** [comment] 2021-06-22 13:59
@HannaFar don't we autorefresh this component ?

**Comment by HannaFar** [comment] 2021-06-22 14:05
> @HannaFar don't we autorefresh this component ?

@karthiksubraveti  Yes we do but  I don't see the autorefresh checkbox on the screenshot

<img width="1235" alt="Capture d’écran 2021-06-22 à 16 02 59" src="https://user-images.githubusercontent.com/26038920/122938954-799d8c00-d373-11eb-9b6f-16e9e1e0e896.png">

**Comment by karthiksubraveti** [comment] 2021-06-22 16:44
@vinayaachar The 1.5.0 image tagged in docker.artifactory.magmacore.org/magmalte contains this fix. I'm closing this issue. Please upgrade your repo and check if the issue is fixed for you as well. Thanks

**Comment by vinayaachar** [comment] 2021-06-22 20:30
@karthiksubraveti  I upgraded to 1.5 and still see the same issue 
![Screen Shot 2021-06-22 at 1 29 25 PM](https://user-images.githubusercontent.com/43836914/122995128-0ccbc700-d35e-11eb-8484-0566ec0dcc12.png)

**Comment by karthiksubraveti** [comment] 2021-06-22 22:21
> @karthiksubraveti I upgraded to 1.5 and still see the same issue
> ![Screen Shot 2021-06-22 at 1 29 25 PM](https://user-images.githubusercontent.com/43836914/122995128-0ccbc700-d35e-11eb-8484-0566ec0dcc12.png)

Can you open developer window and check if the gateway information is being fetched again and if the health turns to Good ? Currently autorefresh refreshed state every 30 seconds I believe

**Comment by karthiksubraveti** [comment] 2021-06-30 07:27
@wallyrb why is this reopened ? What's the issue here?

**Comment by wallyrb** [comment] 2021-06-30 15:01
> @wallyrb why is this reopened ? What's the issue here?

Hey @karthiksubraveti , I re-opened since the issue happens also in 1.5. Health changes to "Bad" when the AGW still alive (with the auto-refresh option enabled)Will collect the information from developer window in order to find more info

**Comment by karthiksubraveti** [comment] 2021-06-30 15:06
> > @wallyrb why is this reopened ? What's the issue here?
> 
> Hey @karthiksubraveti , I re-opened since the issue happens also in 1.5. Health changes to "Bad" when the AGW still alive (with the auto-refresh option enabled)Will collect the information from developer window in order to find more info

Health is based on when the gateway checks in, can you check if the last checkin time is < 5 mins

**Comment by HannaFar** [comment] 2021-07-15 15:13
Hey @wallyrb !
Were you able to get more info ?

**Comment by wallyrb** [comment] 2021-07-15 17:20
Hey @HannaFar Let me check the logs and will come back to you

**Comment by vinayaachar** [comment] 2021-07-15 18:36
@HannaFar  Checked syslogs on AGW and found that AGW is checking into Orc8 every min (sample timestamps below) with message "INFO:root:Checkin Successful! Successfully sent states to the cloud!" 

Seems like AGW is fine here Attaching syslogs
[agw_syslog.txt](https://github.com/magma/magma/files/6825511/agw_syslog.txt)


31:30
32:31
33:32
34:33
35:34
36:35

**Comment by ekowtaylor** [comment] 2021-07-16 15:23
@andreilee please revise this issue with conservative story points for the sprint https://app.zenhub.com/workspaces/magma-5fac75d3e2cd890011f1677a/issues/magma/magma/7645

**Comment by vinayaachar** [comment] 2021-07-19 23:40
I was able to go to developer mode and check (in NMS) when the issue happened and found the "checkin_time" remains constant while NMS is showing BAD state and this boolean becomes false https://github.com/magma/magma/blob/1.5/nms/app/packages/magmalte/app/components/GatewayUtils.js#L184

From my syslog, I see this during BAD state in NMS and after this error AGW stops sending checkin for about 20mins

Jul 19 21:35:00 magma-dev magmad[16571]: ERROR:root:[SyncRPC] Failing to forward request, err: Received RST_STREAM with error code 2
Jul 19 21:35:00 magma-dev magmad[16571]: ERROR:root:[SyncRPC] gRPC error: Received RST_STREAM with error code 2, reconnecting to cloud.
Jul 19 21:35:00 magma-dev magmad[16571]: ERROR:root:Checkin Error! Failed to report states. [StatusCode.INTERNAL] Received RST_STREAM with error code 2
Jul 19 21:35:00 magma-dev magmad[16571]: INFO:root:StateReporting (Checkin) failure threshold met, remediating...
Jul 19 21:35:01 magma-dev magmad[16571]: ERROR:root:StateReporting failure likely not due to invalid cert


Jul 19 21:57:16 magma-dev systemd[16388]: Time has been changed
Jul 19 21:57:16 magma-dev systemd[1]: Time has been changed
Jul 19 21:57:16 magma-dev systemd[1]: anacron.timer: Adding 3min 33.733055s random time.
Jul 19 21:57:16 magma-dev systemd[1]: apt-daily-upgrade.timer: Adding 30min 20.236682s random time.
Jul 19 21:57:17 magma-dev control_proxy[18392]: 2021-07-19T21:57:17.639Z [127.0.0.1 -> streamer-controller.moseglobal.org,8443] "POST /magma.orc8r.Streamer/GetUpdates HTTP/2" 200 2086bytes 0.205s
Jul 19 21:57:17 magma-dev magmad[16571]: INFO:root:Processing config update vinay-test
Jul 19 21:57:19 magma-dev td-agent-bit[18404]: [0] eventd: [1626731837.662037374, {"event_t

**Comment by ekowtaylor** [comment] 2021-07-20 16:32
cc. @andreilee

**Comment by ekowtaylor** [comment] 2021-07-20 16:54
@andreilee please add story points here https://app.zenhub.com/workspaces/magma-5fac75d3e2cd890011f1677a/issues/magma/magma/7645

**Comment by andreilee** [comment] 2021-07-20 19:49
Thanks Vinay. This looks to be originating as a SyncRPC issue so far.

**Comment by ardzoht** [comment] 2021-07-20 20:13
@vinayaachar can you provide a longer output of the syslog? And also if it's possible logs from the dispatcher service on Orc8r. 

RST_STREAM on syncRPC usually happens when connection is dropped out for any reason, I'm trying to debug what is going on but it's difficult to see from a specific time snapshot

**Comment by vinayaachar** [comment] 2021-07-20 20:53
@ardzoht  Attaching longer syslogs. I will look into getting dispatcher service logs 

[agw_syslog_0719.txt](https://github.com/magma/magma/files/6851159/agw_syslog_0719.txt)

**Comment by vinayaachar** [comment] 2021-07-21 18:13
@ardzoht Attached are 2 dispatcher logs from orc8. I see this `receiveFromStream: error receiving from stream: context canceled`  in the logs, not sure if relevant    

[orc8_dispatcher1.log](https://github.com/magma/magma/files/6857972/orc8_dispatcher1.log)
[orc8_dispatcher2.log](https://github.com/magma/magma/files/6857973/orc8_dispatcher2.log)

**Comment by ardzoht** [comment] 2021-07-22 00:28
Thanks @vinayaachar for the detailed logs, from looking at the syncRPC error logs, I can see that it recovers soon after the error happens on all occurrences:
```
1657 Jul 19 16:43:22 magma-dev magmad[14401]: ERROR:root:Error! Streaming from the cloud failed! [StatusCode.INTERNAL] Received RST_STREAM with error code 2
1658 Jul 19 16:43:22 magma-dev magmad[14401]: ERROR:root:[SyncRPC] Failing to forward request, err: Received RST_STREAM with error code 2
1659 Jul 19 16:43:22 magma-dev magmad[14401]: ERROR:root:[SyncRPC] gRPC error: Received RST_STREAM with error code 2, reconnecting to cloud.
1660 Jul 19 16:43:22 magma-dev subscriberdb[14502]: ERROR:root:Error! Streaming from the cloud failed! [StatusCode.INTERNAL] Received RST_STREAM with error code 2
1661 Jul 19 16:43:23 magma-dev magmad[14401]: INFO:root:[SyncRPC] Opening stream to cloud
1662 Jul 19 16:43:23 magma-dev magmad[14401]: INFO:root:[SyncRPC] Waiting for requests
``` 
However I'm interested by this
```
1665 Jul 19 19:18:17 magma-dev systemd[1]: Time has been changed
1666 Jul 19 19:18:17 magma-dev systemd[1]: anacron.timer: Adding 2min 27.520850s random time.
1667 Jul 19 19:18:17 magma-dev systemd[1]: apt-daily-upgrade.timer: Adding 10min 7.047916s random time.
1668 Jul 19 19:18:17 magma-dev kernel: [101918.903870] 19:18:17.707091 timesync vgsvcTimeSyncWorker: Radical host time change: 8 237 746 000 000ns (HostNow=1 626 722 297 707 000 000 ns HostLast=1 626 714 059 961 000 000 ns
1669 Jul 19 19:18:17 magma-dev systemd[1]: Started Run anacron jobs.
1670 Jul 19 19:18:17 magma-dev anacron[10694]: Anacron 2.3 started on 2021-07-19
1671 Jul 19 19:18:17 magma-dev anacron[10694]: Normal exit (0 jobs run)
1672 Jul 19 19:18:17 magma-dev systemd[1]: anacron.timer: Adding 37.552542s random time.
```

Do you know what's the originating trigger for this? I ask because since we use checkin_time validity against latest successful checkin to define the health status, not sure if this time change could be interfering with that.

**Comment by vinayaachar** [comment] 2021-07-22 19:36
@ardzoht  Not sure, what I do notice is , my AGW instance lags in current time. It does not match the actual UTC time. Could that be an issue ?

**Comment by andreilee** [comment] 2021-07-23 22:01
Are there steps to reproduce this reliably?

**Comment by andreilee** [comment] 2021-07-23 22:02
`checkin_time` as reported from the gateway status is not going to update every time the browser makes a GET request for the gateway status. Checkins happen about once a minute.

**Comment by andreilee** [comment] 2021-08-04 00:01
@vinayaachar

**Comment by vinayaachar** [comment] 2021-08-04 00:10
@andreilee Can you advise on the next steps ?

**Comment by andreilee** [comment] 2021-08-04 00:11
Are there some steps to reproduce this issue? We're having trouble reproducing this locally.

**Comment by ekowtaylor** [comment] 2021-08-09 17:33
No feedback to reproduce, will close and reopen when there is new data

**Comment by jpad-freedomfi** [comment] 2021-11-10 00:14
@ekowtaylor @andreilee @wallyrb  can we reopen this? We can reproduce readily. Looks like this is triggered by long latency between AGW and orc8r. We have multiple sat terminal AGWs with RTT of ~700ms. Magmad logs show gRPC link to orc8r flapping regularly. More importantly, we see this block Gx ReAuth request where orc8r replies to FeG with Queue not found if Gx message arrives while gRPC link is down and being re-established. 

Example log snippets here, but we have 

Here is gRPC issue:

```
Nov 09 15:19:20 agw magmad[7662]: INFO:root:[SyncRPC] Opening stream to cloud
Nov 09 15:19:20 agw magmad[7662]: INFO:root:[SyncRPC] Waiting for requests
Nov 09 15:19:21 agw magmad[7662]: INFO:root:Processing config update nuc
Nov 09 15:19:27 agw magmad[7662]: ERROR:root:[SyncRPC] Failing to forward request, err: Received RST_STREAM with error code 2
Nov 09 15:19:27 agw magmad[7662]: ERROR:root:[SyncRPC] gRPC error: Received RST_STREAM with error code 2, reconnecting to cloud.
Nov 09 15:19:28 agw magmad[7662]: INFO:root:[SyncRPC] Opening stream to cloud
Nov 09 15:19:28 agw magmad[7662]: INFO:root:[SyncRPC] Waiting for requests
Nov 09 15:19:30 agw magmad[7662]: INFO:root:Checkin Successful! Successfully sent states to the cloud!
Nov 09 15:19:48 agw magmad[7662]: ERROR:root:[SyncRPC] Failing to forward request, err: Received RST_STREAM with error code 2
Nov 09 15:19:48 agw magmad[7662]: ERROR:root:[SyncRPC] gRPC error: Received RST_STREAM with error code 2, reconnecting to cloud.
```

Here is failing request from FeG to Or8cr:

```
E1109 23:19:26.041929       1 handlers.go:51] Error relaying reauth request to gateway: rpc error: code = Internal desc = err sending request gwId:"7bf97027-6442-4641-9736-4caf544f4ed7" authority:"sessiond" path:"/magma.lte.SessionProxyResponder/ChargingReAuth" headers:<key:"Content-Type" value:"application/grpc" > headers:<key:"Te" value:"trailers" > headers:<key:"User-Agent" value:"grpc-go/1.31.0" > payload:"\000\000\000\0003\n\032IMSI334190000000015-489529\032\023IMSI334190000000015 \001"  to gateway: Queue does not exist for gwId 7bf97027-6442-4641-9736-4caf544f4ed7
```

**Comment by joary** [comment] 2021-11-10 19:44
@jpad-freedomfi can you share the logs from both k8s orc8r-dispatcher pods? I believe the behavior seen is expected, follows my rationale:

FeG is not able to enqueue the ReAuth, because the queue is [immediately removed from orc8r-dispatcher in case the communication to the AGW is lost](https://github.com/magma/magma/blob/master/orc8r/cloud/go/services/dispatcher/servicers/sync_rpc_service.go#L109). Assuming the gRPC stream is reset, orc8r-dispatcher will simply restart itself.

Having the [dispatcher logs](https://github.com/magma/magma/blob/master/orc8r/cloud/go/services/dispatcher/servicers/sync_rpc_service.go) can get us a better understanding of what is causing the gRPC stream to be lost. Though in bad network condition it will happen anyway.

Then it comes down to: what is the expected behavior? From my point of view FeG (as the Gx integration proxy) should have a retrial mechanism.

On the other hand, I don’t think this is related to NMS but related to the way Orc8r/FeG handles the queues in the scenario of a connectivity lost to AGW. Maybe a good Idea to move this conversation to another issue.

**Comment by jpad-freedomfi** [comment] 2021-11-12 02:18
Hi @joary the point here was the comment thread less the subject. The comment thread is showing issue related to grpc connection flapping. Ticket was closed due to lack of steps to recreate. We can now easily recreate. 

Happy to start a new thread. 

Real issue for us here is: grpc needs to be stable over long latency links. Links with latency up to average 700ms RTT and peaks upto 1500ms RTT. 

Want me to open a new issue on that?

**Comment by jpad-freedomfi** [comment] 2021-11-12 02:20
Sorry, second option is what you said, queuing and retry for Gx in FeG. 

Either way would solve the issue. 

Or both. Cause any API call to AGW with grpc connection flapping will cause random failures in all sorts of things. 

Specifically for sat term deployments that will, return as an issue.

**Comment by joary** [comment] 2021-11-16 12:29
@jpad-freedomfi, I propose to have two separate threads:

1. Root-Cause the gRPC reset issue and search for workaround.
   - Help Needed: Collect the logs from both k8s orc8r-dispatcher pods.
   - Expected Outcome: Understand the specific cause for gRPC reset and if there's some configuration to reduce the impact (Timeouts, keep-alives)

2. Provide a more reliable mechanism for Gy Re-Auth [Feature]:
   - Help Needed: Setup a lab for validation.
   - Expected Outcome: Make Gy Re-Auth reliable to AGW connectivity lost.

**Comment by jpad-freedomfi** [comment] 2021-11-16 18:38
agree 💯. sounds like the right paths. @joary

**Comment by joary** [comment] 2021-11-30 18:04
To share the knowledge broadly:

The issue regarding `gRPC error: Received RST_STREAM with error code 2, reconnecting to cloud.`

Was workarounded by reducing the syncRPC interval [here](https://github.com/magma/magma/blob/master/orc8r/gateway/python/magma/magmad/main.py#L136)

**Closed as completed** 2021-12-01 13:09 UTC
Labels: type: bug, component: nms, fbcpp
