### ISSUE TITLE
UE attach failed for networks with PLMN based on 3 Digit MNC.

### ISSUE THREAD

**Issue by 119Vik** [magma/magma#1217] opened 2020-02-18 10:49 UTC
### Your Environment

- **Version:** Magma 1.0.1
- **Affected Component:** Orchestrator, Access Gateway, or NMS
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** AWS (orc8r),  bare-metal (AGW)

### Describe the Issue
As per [public resources](https://en.wikipedia.org/wiki/Mobile_country_code) and [specification](https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.212B-2018-PDF-E.pdf) MNC can be 2 or 3 digits long. At the moment Magma only works correctly with 2 digit MNC.

Current known issue is miscalculation of the MAC (AUTN or possible xres) used when negotiating the Security Mode during the attach procedure. This results in UE sending Security Mode Reject message which prevents UE attach. This issue cause S1 to flap, after each Security Mode Reject message we saw the S1 Setup/Response exchange happen again indicating S1 connection had gone down and come back up. That shouldn’t be happening. By switching to PLMN with 2 digit MNC the issue goes away.

**To Reproduce**
1. Setup new Network (or use existing one)
2. Add new AGW, eNodeB( in case of new network)
3. Set MNC to be 3 digit value at the Network configuration page
4. Try to connect UE to the network 
5. See UE attach **failed**
6. Update Network configuration with 2 digit MNC value
7. Try to connect UE to the network 
8. See UE attach **success**

**Expected behavior**
UE attach should be successful for both (3 digits and 2 digits) MNC values in the network configuration

**Comment by 119Vik** [comment] 2020-02-19 10:47
@ulaskozat @lionelgo  would be cool to get your feedback regarding this improvement

**Comment by jpad-freedomfi** [comment] 2020-02-20 19:55
FYI, anyone trying to reproduce we saw this with PLMN 315010 so MCC 315, MNC 010 which is the shared HNI for CBRS networks. So for testing/reproducing, probably a good one to make sure is working.

**Comment by xjtian** [comment] 2020-02-20 20:25
@119Vik to clarify - are you using 2 different IMSIs for this test? 1 with 2-digit MNC and another with 3-digit MNC?

**Comment by jpad-freedomfi** [comment] 2020-02-20 20:49
The two tested IMSIs we have tried are:
315010999900101 (MCC 315, MNC 010, MSIN 999900101)
208950000000001 (MCC 208, MNC 95, MSIN 0000000001)

**Comment by amarpad** [comment] 2020-02-20 20:57
This is a regression, let me try and find a patch from the past and paste it here.

**Comment by jpad-freedomfi** [comment] 2020-02-20 21:03
BTW, the 208.... worked. The 315... did not.

**Comment by amarpad** [comment] 2020-02-20 21:16
@jpad-freedomfi would you be up to trying the equivalent of this logical patch and seeing if it fixes it? Basically the memcopy assumes a static length.


[tmp.patch.txt](https://github.com/facebookincubator/magma/files/4233067/tmp.patch.txt)

**Comment by jpad-freedomfi** [comment] 2020-02-20 22:11
@amarpad we can test it but two things: 1)I am more the system level guy, we need @119Vik to help patch our magma instance and 2) from the patch text comment I’m not sure it’s the same issue, this error occurs at initial attach where guti isn’t used, IMSI is sent directly. But I guess it could catch a similar code path.

**Comment by amarpad** [comment] 2020-02-20 22:18
Yeah we were copying imsi length incorrectly, so that patch was supposed to fix it. We shall put it into our backlog and try out the patch if it is hard to do. @119Vik let us know

**Comment by ssanadhya** [comment] 2020-02-21 16:41
@jpad-freedomfi @119Vik, I am trying to reproduce the error in our local setup and debug it. I will get back soon with a fix.

**Comment by ssanadhya** [comment] 2020-02-24 23:37
@jpad-freedomfi @119Vik , are you testing with real SIM cards or with Magma test VM, which runs  S1ap-tester? I could reproduce the same issue in my dev setup and the cause is an outdated version of the S1ap-tester on the test VM. I have updated the S1aptester package version to 1.0.8 and attach/detach is working fine for MCC:315 and MNC: 010. Attached is a packet capture from my dev setup with a simulated UE.
[plmn_315010_0.pcap.zip](https://github.com/facebookincubator/magma/files/4247356/plmn_315010_0.pcap.zip)

If you are seeing this failure with real SIM cards, do you mind sharing the pcap and MME logs?

Note that the same test case fails on the latest master and we are working on fixing that.

**Comment by jpad-freedomfi** [comment] 2020-02-25 14:40
We are testing with a real USIM. We have not used the tester. I will ask Alex to get PCAPs and logs.

**Comment by 119Vik** [comment] 2020-03-02 22:12
@amarpad  we tested patch and unfortunately it does not solve issue for us

**Comment by 119Vik** [comment] 2020-03-02 22:17
@ssanadhya as as result of tests we found following positive:
 - [good_mme.log](https://github.com/facebookincubator/magma/files/4278156/good_mme.log)
- [s1ap-good_pcapng.log](https://github.com/facebookincubator/magma/files/4278157/s1ap-good_pcapng.log)
And negative logs :
 - [bad_mme.log](https://github.com/facebookincubator/magma/files/4278155/bad_mme.log)
 - [s1ap-badmnc_pcapng.log](https://github.com/facebookincubator/magma/files/4278158/s1ap-badmnc_pcapng.log)

**Comment by jpad-freedomfi** [comment] 2020-03-03 04:30
Hi @ssanadhya 

We found this issue in OAI code back in 2013. I have lost my records, but my recollection was that the MAC (Message Authentication Code) in the Security Mode Command message wasn't being calculated correctly when MNC was 3 digits. 

So in frame 6 in the s1ap-badmnc_pcapng.log file the MAC = 0x044c23c2. That is very likely wrong. I am looking for algo to produce that MAC in a reference.

**Comment by jpad-freedomfi** [comment] 2020-03-03 05:06
FWIW 

I think magma uses this to calculate MAC with EIA1
https://github.com/facebookincubator/magma/blob/1aa8ff9241ccc050cecfecbb5922ef2b27fade2d/lte/gateway/c/oai/lib/secu/nas_stream_eia1.c

here is a reference from nextEPC for same function, see "snow_3g_f9"
https://github.com/nextepc/nextepc/blob/7a8e32f4538407384b073d26b7cb62f6f6506431/src/mme/snow_3g.c

**Comment by ssanadhya** [comment] 2020-03-03 23:15
@119Vik, thanks for sharing the pcaps!
@jpad-freedomfi, thanks for the insight on MAC calculation! I am trying to reproduce the issue locally with a USIM, in place of S1ap-tester. Let me investigate and get back to you.

**Comment by rsarwad** [comment] 2020-03-06 05:27
@119Vik , Are the above shared pcaps, captured while testing with real UE and thirdparty HSS or subscriberDB?

**Comment by jpad-freedomfi** [comment] 2020-03-06 05:58
SubscriberDB. We added user info via Magma UI.

**Comment by ssanadhya** [comment] 2020-03-11 21:54
@jpad-freedomfi @119Vik , can you try the changes in PR #1294 ? We are still in the process of testing this on real hardware with both 2 digit and 3 digit MNC values. Will post packet captures once we are done.

**Comment by ssanadhya** [comment] 2020-03-16 04:16
Fixed in d966c7812ea4ad5c602b03599a46cd473aa6d538

**Closed as completed by ssanadhya** 2020-03-16 04:16 UTC
Labels: type: bug, component: agw
