### ISSUE TITLE
Magma SA-TeraVM | Default Allow all Packet Filters & QOS Rule seems not adding in right QF-id 5 on DL 5G NAS

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#8758] opened 2021-08-25 06:11 UTC
Kindly validate this QF-ID values.

Default Allow all Packet Filters & QOS Rule seems not adding in right QF-id 5 on 5G-NAS instead added in next QF-id 6 but PDU session (on GTP Tunnel) is being setup with QF-id 5. 

on NGAP "PDU Session Resource Setup Request" AMF/ SMF is setting QOS actions on **QF-id = 5** where as on 5G NAS of "PDU Session Establish Accept" QOS Rules are being Setup for **QF-id = 6**, below are the snaps of it.

Expectation:  Generally Default Allow all Packet Filters & QOS Rule would be added in default QF-id 5 on 5G-NAS as PDU Session (GTP Tunnel) is setup for QF-id 5.

NGAP "PDU Session Resource Setup Request"
<img width="1524" alt="Screen Shot 2021-08-24 at 11 00 15 PM" src="https://user-images.githubusercontent.com/70725754/130734878-74cea469-e4cf-49e3-9c04-e8deec71914d.png">

5G NAS of "PDU Session Establish Accept"
<img width="1524" alt="Screen Shot 2021-08-24 at 11 00 27 PM" src="https://user-images.githubusercontent.com/70725754/130734917-56b5043a-2a5a-4495-a726-97b449a631bd.png">

[Pcaps Enclosed]
[SA_01_02_03_04_Hyper_Suci_210824_121721-1.pcapng.zip](https://github.com/magma/magma/files/7044075/SA_01_02_03_04_Hyper_Suci_210824_121721-1.pcapng.zip)

**Comment by ganeshg87** [comment] 2021-08-30 13:36
this issue was handling another Zenhub ticket, closing this ticket as a duplicate of
https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/8798

**Closed as completed** 2021-08-30 13:37 UTC
Labels: type: bug, product: 5g sa
