### ISSUE TITLE
[TeraVM 5G Regression] : TC51 is failing due to udp traffic

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#10772] opened 2021-12-10 04:30 UTC
**Description:**

**Expected behavior:** 
 
  Basic call flow and udp traffic should work fine.

**Actual behavior:**

 Basic call flow is fine due to an issue with udp traffic TC is failing.

**Comment by rupa455wavelabs** [comment] 2021-12-10 11:34
Please check the attached pcap and logs 
[https://app.zenhub.com/files/170803235/95ffd456-68f0-4032-bbd9-94208155b577/download](https://app.zenhub.com/files/170803235/95ffd456-68f0-4032-bbd9-94208155b577/download)

**Comment by prabinakpattnaik** [comment] 2021-12-10 11:36
As per syslog, this is a known issue and introduced recently by refactoring sessiond code. Please find the details on ticket number : https://github.com/magma/magma/issues/10632

**Comment by moinuddin1980** [comment] 2021-12-10 11:40
It's a duplicate of #10632. Hence, closing this.
https://github.com/magma/magma/issues/10632

**Closed as completed by moinuddin1980** 2021-12-10 11:40 UTC
Labels: product: 5g sa

**Comment by rupa455wavelabs** [comment] 2021-12-24 10:00
Tested TC52 and TC51 with a fix given by Developers for the UDP and TCP traffic flow. we are able to see successful traffic flow(Both UL/DL) but In TVM GUI statistics are not updating properly and Testcase is also failing. Please check the below PCAP's for your reference.
https://app.zenhub.com/files/170803235/6d15832c-a05a-4510-9c26-04a3d70f4eeb/download
