### ISSUE TITLE
[AGW][BE] Hashtable OAI library migration to C++ 

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#8801] opened 2021-08-26 17:48 UTC
OAI makes use of its own internal library for hashtable structures. This is a wide-used library being used throughout all MME tasks mostly for the maintenance of both task’s and UE state. There are multiple types available to use, but mostly both uint64 => uint64 and uint64 => object PTR thread-safe mappings are the most used in the codebase.

iteratively migrate OAI’s hashtable and their usage to protobuf's generated object CPP hashmap structs, a starting point to refer can be: https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp

**Comment by ssanadhya** [comment] 2022-02-07 18:13
This is a duplicate of https://github.com/magma/magma/issues/11190, closing the older of the two.

**Closed as completed by ssanadhya** 2022-02-07 18:13 UTC
Labels: Epic, cpp-migration
