### ISSUE TITLE
[Magma NMS/FeG] Mapping Service Identifier with Rating group for CCR-I to OCS

### ISSUE THREAD

**Issue by emersonacuna** [magma/magma#7498] opened 2021-06-11 16:59 UTC
### Federated LTE Network

- **Version:** 1.4
- **Affected Component:** Orchestrator, Access Gateway, NMS, FeG
- **Affected Subcomponent:** Orchestrator, Access Gateway, NMS, FeG
- **Deployment Environment:** local docker-compose (orc8r), openstack AGW/FeGW

### Describe the Feature
Able to add Service Identifier mapping together to Rating Group. This is in order to include AVP code 439 Service-Identifier inside AVP MSCC in CCR-I send to OCS. 

**Specify the applicable product use-cases**
FWA telecom operator

**Describe the solution you'd like**
Able to add Service Identifier mapping together to Rating Group. This is in order to include AVP code 439 Service-Identifier inside AVP MSCC in CCR-I send to OCS. 

Similar feature has been added for CLI Gy test: https://github.com/magma/magma/pull/7014

**Comment by uri200** [comment] 2021-06-12 02:22
Service identifier is already taken in our PCEF (sessiond) and sent by the FEG http://github.com/magma/magma/blob/master/feg/gateway/services/session_proxy/credit_control/gy/gy_client.go#L403-L403

Per our code we use service identifier and rating group to set the mapping. 

Can you describe the current issue you see with pcaps and session_proxy logs please? It would be good to enable grpc logging at session_proxy

```
  session_proxy:
    <<: *goservice
    environment:
      USE_GY_FOR_AUTH_ONLY: ${USE_GY_FOR_AUTH_ONLY}
      GY_SUPPORTED_VENDOR_IDS: ${GY_SUPPORTED_VENDOR_IDS}
      GY_SERVICE_CONTEXT_ID: ${GY_SERVICE_CONTEXT_ID}
      MAGMA_PRINT_GRPC_PAYLOAD: 1 							<----- ADD THIS FOR LOGGING GRPC
    container_name: session_proxy 
    command: envdir /var/opt/magma/envdir /var/opt/magma/bin/session_proxy -logtostderr=true -v=9
```

Note the feature added 7014 was just a CLI field, just to include a value on that AVP that the CLI didn't have before.

**Comment by emersonacuna** [comment] 2021-06-14 14:19
Hi @uri200, I can send you these logs/traces for now, note that response of the OCS in the CCA-I is 5030 DIAMETER USER UNKNOWN. Our current real test user is not provisioned in the OCS. Even that, it is enough to make my point. 

Gy diameter link is set with TCP 5112. The PCEF send the CCR-I to OCS. Inside this CCR-I, and inside the AVP 456 MSCC, the PCEF send AVP 432 Rating Group and AVP 437 Requested Service Unit. 

![image](https://user-images.githubusercontent.com/79710920/121906505-cb4d7300-ccf0-11eb-8507-cbc82f515d04.png)

What we need is, along with AVP RG and Req-Serv-Unit, need to be the AVP 439 Service-Identifier for each service/RG requested to OCS. This new AVP must be configurable in the policy rule, just like the RG:
![image](https://user-images.githubusercontent.com/79710920/121906996-41ea7080-ccf1-11eb-9d76-2502ad701c11.png)

Here the info you need:
[log_trace.zip](https://github.com/magma/magma/files/6648993/log_trace.zip)

**Comment by uri200** [comment] 2021-06-14 19:27
So the problem is local policy definition don't currently support service identifier.

Does you have a dynamic policy comming from PCRF with service identifier? With dynamic rules you should be able to see service identifier

**Comment by emersonacuna** [comment] 2021-06-15 18:04
Yes, thats the problem. Service Identifier must be configurable for static rules, it means configurable for each policy rule.

**Comment by joary** [comment] 2021-06-15 18:18
@uri200 , regarding the question below:

> Does you have a dynamic policy comming from PCRF with service identifier? 

No, this policy is one of the static policies defined by partner infra, this means we should have it configured statically on policydb

**Comment by uri200** [comment] 2021-06-15 18:42
The question is, can you test it with a dynamic rule to see if service identifier is showing up on the messages?
Per what I could see in the code, the logic for dynamic rules is there.

**Comment by emersonacuna** [comment] 2021-06-15 18:52
OK, i see if we can try with a dynamic rule. But note that the final test must be with static rules.

**Comment by uri200** [comment] 2021-06-15 18:54
yes, what I am trying to understand where is exactly the gap on this feature. Note I have some changes done on our master branch to test the addition of this field to the static rule definition in or8cr
https://github.com/magma/magma/pull/7545

**Comment by uri200** [comment] 2021-06-17 03:39
@emersonacuna please, find attached a file where you can find a test using the PRs included on that issue

At frame 102 you can see service identifier being sent 

Once this is landed you will need to rebuild Orc8r and FEG using latest code on v1.5

![image](https://user-images.githubusercontent.com/16157139/122327564-ebdd1f00-cee2-11eb-8baf-aa6b626a541c.png)


[gx_gy_combined_03_210616_200926-1.pcapng.zip](https://github.com/magma/magma/files/6667197/gx_gy_combined_03_210616_200926-1.pcapng.zip)

**Closed as completed** 2021-06-17 22:15 UTC
Labels: type: feature
