### ISSUE TITLE
Reproduce nginx syncRPC bidirectional streaming flakiness during high request load

### ISSUE THREAD

**Issue by xjtian** [magma/magma#3206] opened 2020-10-13 00:39 UTC
During CWF SIT:

- 5K UE's attaching to network at about 17Hz. Each attach sends at least 1 RPC call to FeG, which eventually responds over the syncRPC channel back to the originating AGW.
- We usually see a few hundred attach failures when we run this test with nginx as the ingress. Failure rate seems to be related to how many nginx pods there are, how many controller pods there are, and the worker process count on the nginx pods. 1 nginx pod, 1 worker process, and 1 controller pod seems to result in the lowest number of failures
- We need to RC this because this was not an issue using nghttpx as the ingress proxy. Set up some local testing scripts to try and track this down.

**Comment by ardzoht** [comment] 2020-11-17 18:06
I've added a local script to stress test the SyncRPC communication, locally still trying to reproduce the issue using local FeG, Orc8r and AGW sending a high number of feg_hello RPC requests. I'll be using the script to generate requests on one of the CWF setups where this issue was first seen and reported. As for now, I'm hesitant to provide an estimate as I haven't seen the flaky behavior on my testing.

**Comment by ardzoht** [comment] 2020-11-19 17:25
The cw04 and cwf05 setups with feg are having network issues per CWF folks, I'm waiting for the setup to be ready so we can initiate traffic testing with FeG as this has been the culprit where this issue appears.

**Comment by ardzoht** [comment] 2021-01-07 17:32
Closing the task since it's been a while since the issue has appeared on our setups, we'll reopen if it comes back again to take a look and fix the issue

**Closed as completed by ardzoht** 2021-01-07 17:32 UTC
Labels: priority: high
