### ISSUE TITLE
gateway "python setup.py egg_info" failed with errorcode 1 and sypne version is 2.2.16

### ISSUE THREAD

**Issue by jacqueline0124** [magma/magma#206] opened 2019-04-19 05:29 UTC
After SSHing into the gateway box, and running make run "python setup.py egg_info" failed with error code 1

sudo service magma@* stop
make -C /home/gateway/magma/lte/gateway/python buildenv
make[1]: Entering directory '/home/gateway/magma/lte/gateway/python'
Initializing virtualenv with python version 3.5
virtualenv --system-site-packages --python=/usr/bin/python3.5 /home/gateway/build/python
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /home/gateway/build/python/bin/python3.5
Not overwriting existing python script /home/gateway/build/python/bin/python (you must use /home/gateway/build/python/bin/python3.5)
Installing setuptools, pip, wheel...
done.
. /home/gateway/build/python/bin/activate;
/home/gateway/build/python/bin/pip3 install -q -U --cache-dir ~/.pipcache pip==9.0.3
/home/gateway/build/python/bin/pip3 install -q -U --cache-dir ~/.pipcache setuptools==25.1.4
/home/gateway/build/python/bin/pip3 install -q -U --cache-dir ~/.pipcache "grpcio-tools==1.16.1"
Generating python code for orc8r .proto files
/home/gateway/build/python/bin/python /home/gateway/magma/protos/gen_protos.py /home/gateway/magma/orc8r/protos/ /home/gateway/magma,/home/gateway/magma/orc8r/protos/prometheus /home/gateway/magma /home/gateway/build/python/gen/
Generating python code for lte .proto files
/home/gateway/build/python/bin/python /home/gateway/magma/protos/gen_protos.py /home/gateway/magma/lte/protos/ /home/gateway/magma,/home/gateway/magma/orc8r/protos/prometheus /home/gateway/magma /home/gateway/build/python/gen/
Generating python code for feg .proto files
/home/gateway/build/python/bin/python /home/gateway/magma/protos/gen_protos.py /home/gateway/magma/feg/protos/ /home/gateway/magma,/home/gateway/magma/orc8r/protos/prometheus /home/gateway/magma /home/gateway/build/python/gen/
/home/gateway/build/python/bin/python /home/gateway/magma/protos/gen_prometheus_proto.py /home/gateway/magma /home/gateway/build/python/gen
make -C /home/gateway/magma/lte/gateway/python install_egg
make[2]: Entering directory '/home/gateway/magma/lte/gateway/python'
Initializing virtualenv with python version 3.5
virtualenv --system-site-packages --python=/usr/bin/python3.5 /home/gateway/build/python
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /home/gateway/build/python/bin/python3.5
Not overwriting existing python script /home/gateway/build/python/bin/python (you must use /home/gateway/build/python/bin/python3.5)
Installing setuptools, pip, wheel...
done.
. /home/gateway/build/python/bin/activate;
/home/gateway/build/python/bin/pip3 install -q -U --cache-dir ~/.pipcache pip==9.0.3
Installing egg link for lte
/home/gateway/build/python/bin/pip3 install -q -U --cache-dir ~/.pipcache -e .[dev]
make[2]: Leaving directory '/home/gateway/magma/lte/gateway/python'
make -C /home/gateway/magma/orc8r/gateway/python install_egg
make[2]: Entering directory '/home/gateway/magma/orc8r/gateway/python'
Initializing virtualenv with python version 3.5
virtualenv --system-site-packages --python=/usr/bin/python3.5 /home/gateway/build/python
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /home/gateway/build/python/bin/python3.5
Not overwriting existing python script /home/gateway/build/python/bin/python (you must use /home/gateway/build/python/bin/python3.5)
Installing setuptools, pip, wheel...
done.
. /home/gateway/build/python/bin/activate;
/home/gateway/build/python/bin/pip3 install -q -U --cache-dir ~/.pipcache pip==9.0.3
Installing egg link for orc8r
/home/gateway/build/python/bin/pip3 install -q -U --cache-dir ~/.pipcache -e .[dev]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-x4hgmz7l/systemd-python/
/home/gateway/magma/orc8r/gateway/python/python.mk:72: recipe for target 'install_egg' failed
make[2]: *** [install_egg] Error 1
make[2]: Leaving directory '/home/gateway/magma/orc8r/gateway/python'
Makefile:16: recipe for target '/home/gateway/magma/orc8r/gateway/python_build' failed
make[1]: *** [/home/gateway/magma/orc8r/gateway/python_build] Error 2
make[1]: Leaving directory '/home/gateway/magma/lte/gateway/python'
Makefile:60: recipe for target 'build_python' failed
make: *** [build_python] Error 2

root@ubuntu:/# pip3 list|grep spyne
spyne             2.12.16 

root@ubuntu:/# pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
aiodns (2.0.0)
aioeventlet (0.4)
aiohttp (2.3.10)
ansible (2.7.10)
asn1crypto (0.24.0)
async-timeout (2.0.1)
Babel (2.6.0)
bcrypt (3.1.6)
certifi (2019.3.9)
cffi (1.12.2)
chardet (3.0.4)
Click (7.0)
command-not-found (0.3)
cryptography (2.6.1)
debtcollector (1.21.0)
dnspython (1.16.0)
envoy (0.0.3)
eventlet (0.24.1)
Fabric3 (1.14.post1)
Flask (1.0.2)
greenlet (0.4.15)
grpcio (1.20.0)
grpcio-tools (1.16.1)
idna (2.8)
idna-ssl (1.1.0)
iperf3 (0.1.11)
itsdangerous (1.1.0)
Jinja2 (2.10.1)
language-selector (0.1)
lte (0.0.0, /home/gateway/magma/lte/gateway/python)
lxml (4.2.1)
MarkupSafe (1.1.1)
monotonic (1.5)
msgpack-python (0.5.6)
multidict (4.5.2)
netaddr (0.7.19)
nose (1.3.7)
oslo.config (6.8.1)
oslo.i18n (3.23.1)
ovs (2.10.0)
paramiko (2.4.2)
pbr (5.1.3)
pip (9.0.3)
protobuf (3.7.1)
pyasn1 (0.4.5)
pycares (3.0.0)
pycparser (2.19)
pycrypto (2.6.1)
pygobject (3.20.0)
PyMemoize (1.0.3)
PyNaCl (1.3.0)
pyroute2 (0.5.5)
python-apt (1.1.0b1+ubuntu0.16.4.2)
pytz (2019.1)
PyYAML (5.1)
repoze.lru (0.7)
requests (2.21.0)
rfc3986 (1.2.0)
Routes (2.4.1)
ryu (4.13)
scapy (2.4.2)
setuptools (41.0.0)
six (1.12.0)
sortedcontainers (2.1.0)
spyne (2.12.16)
ssh-import-id (5.5)
stevedore (1.30.1)
tinyrpc (1.0.1)
typing (3.6.6)
ufw (0.35)
urllib3 (1.24.2)
virtualenv (16.4.3)
WebOb (1.8.5)
Werkzeug (0.15.2)
wheel (0.33.1)
wrapt (1.11.1)
WSGIserver (1.3)
yarl (1.2.0)
You are using pip version 9.0.3, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by mubashertnss** [comment] 2019-04-22 16:00
Upgrade the pip:
$ python3 -m pip install --upgrade pip

**Comment by jacqueline0124** [comment] 2019-04-23 02:04
Thanks ，I resolved the issue according to the install_requires in /magma/orc8r/gateway/python/setup.py

**Comment by mpgermano** [comment] 2019-04-23 03:49
@jacqueline0124 I'm glad you were able to resolve the issue. I was unable to reproduce this on a fresh VM. It seems the python dependencies can often cause troubles.

**Comment by xjtian** [comment] 2019-04-23 18:21
Closing as resolved

**Closed as completed by xjtian** 2019-04-23 18:21 UTC
