### ISSUE TITLE
Intra TAU should be accepted by Magma

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#8856] opened 2021-08-28 05:42 UTC
### Your Environment (If applicable)

- **Version: 1.5**
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** bare-metal

### Describe the problem

**Description**
In some networks we have observed the TAU being rejected leads to service issues as some Handsets when rejected a TAU doesnt proceed with further signaling. for eg Service Request or Attach Request. they keep on sending a TAU request and keep getting rejected. 

### Describe your idea(optional)

The recommendation is to accept the TAU for a UE which is already attached to the same AGW.

**Description**
Since AGW already has a context of the UE as it was connected to the same UE, better the AGW accepts the TAU since it already has the context of the UE and this TAU Type would be "intra".

**Desired timelines**
ASAP :).

[logs.zip](https://github.com/magma/magma/files/7070202/logs.zip)

**Comment by shehzadalee** [comment] 2021-08-28 06:14
@jpad-freedomfi

**Comment by ulaskozat** [comment] 2021-08-31 16:18
This is being taken care of by @pruthvihebbani

**Comment by ssanadhya** [comment] 2022-01-19 20:28
This issue is resolved on latest master. Closing this issue. Please re-open if this reappears.

**Closed as completed by ssanadhya** 2022-01-19 20:28 UTC
Labels: type: feature, fbcpp

**Comment by jpad-freedomfi** [comment] 2022-01-19 21:54
@ssanadhya can you share the commit that resolved this issue? Is it the fix Amar helped with to change the cause code or is is something else that was added to master?

**Comment by ssanadhya** [comment] 2022-01-19 22:09
@jpad-freedomfi , please look at https://github.com/magma/magma/pull/8936 and https://github.com/magma/magma/pull/11007
