### ISSUE TITLE
[Regression]paging is not getting triggered as UPF is not finding the session for the respective IMSI because of IMSI prefix problem.

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11093] opened 2022-01-07 12:47 UTC
Your Environment

- Version: 
- Affected Component: Access Gateway
- Affected Subcomponent: AGW service
- Deployment Environment: bare-metal (AGW)-VMBased

### Describe the Issue
Paging is not getting triggered as UPF is not finding the session for the respective IMSI because of IMSI prefix problem.

**To Reproduce**
Execute paging scenario from TVM-GUI.
TC9	AMF Initiated Paging
TC9a	Verify T3513 and Max Paging retry
TC9b	Verify_Paging_reponse_in_last_paging_Retry

**Expected behavior**
Paging should get triggered when there is downlink traffic.
syslogs:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/a80e6594-a19c-44f8-9f09-d0a490be9d48)
mme_logs:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/e94dd8cb-05a8-47f2-8c31-09ab4a715431)

[https://app.zenhub.com/files/170803235/989c743b-0edb-4e37-a861-a43fe752499c/download](https://app.zenhub.com/files/170803235/989c743b-0edb-4e37-a861-a43fe752499c/download)

**Comment by arun-magma** [comment] 2022-01-18 18:23
Hi @NeelimaKalpana: Whats the root cause of this issue ? , Where (TVM Scripts or Magma) is the IMSI prefix is malfunctioning ?

**Comment by NeelimaKalpana** [comment] 2022-01-18 19:47
Hi Arun ,
This is issue in Magma .
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/174b75da-6762-48c4-8bb0-ee47cee8d7bb)
In the above screenshot , AsyncResponce is received from UPF with IMSI-Prefixed before the IMSI(IMSI2224560000000101).
But sessiond is checking for the session without IMSI-Prefixed and session lookup is failing . 

And there are some other issues also with IMSI prefix, now most of the issues got fixed Arun.

**Comment by panyogesh** [comment] 2022-02-10 04:52
Closing as the issue got fixed as part of #10972

**Closed as completed by panyogesh** 2022-02-10 04:52 UTC
Labels: type: bug, product: 5g sa
