### ISSUE TITLE
TVM Scale Test:  SUCI based Registration with Valid and Invalid UE's

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11022] opened 2021-12-30 11:37 UTC
Executed Scale Test Scenario's:

[20-12-2021]
1. SA_TC50a_Scale_Test_Suci Scaling, Registration, PDU_Session_Establishment/Release, UDP Traffic UL DL, Suci(100 Valid & 100 Invalid UE, 1Gnb) - Test is failing due to UL/DL traffic issue.

2. scale Test Suci - 200 Valid UE, 200 Invalid UE(Registration, Pdu Session Establishment/Release, DeRegistration, UL/DL traffic(200UE,12Gnb,5UE/s) - Test case is failing due to UL/DL traffic issue.

Please refer the logs and pcaps for more info:
https://drive.google.com/drive/folders/1Kziq5t9sKTW_QEh7cMvvHNOHOCc2Okol

**Comment by Kaleem-Wavelabs** [comment] 2022-01-13 19:00
@rupa455wavelabs 

The root cause for script failures is due to traffic loss in UL/DL which got fixed by #10972 and it got manually verified the fix as well. Can close this if there are no further traffic losses is observed.

**Comment by rupa455wavelabs** [comment] 2022-01-17 16:02
Tested the scenario with latest magma code and observed mme service restart, please check the attached logs and pcaps.
![n3_50a_suci.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/720888ae-3393-4b45-a789-318a0a099417)

![pdusession_50a.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/c52b5232-f2c6-418e-835a-b07d3a5a1722)

![50a_suci.PNG](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/e44c2555-04fe-4509-966d-5ffe2cbf9d36)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/581d9905-fe39-4199-a26e-73c782548c93)

[https://app.zenhub.com/files/170803235/cfb7d9f4-d2df-42a8-a0db-88e3a06ee6a8/download](https://app.zenhub.com/files/170803235/cfb7d9f4-d2df-42a8-a0db-88e3a06ee6a8/download)

**Comment by rupa455wavelabs** [comment] 2022-03-03 09:19
Need to re-verify it in spirent setup and update the results.

**Comment by rupa455wavelabs** [comment] 2022-03-11 08:22
re-executed the TC with 100 invalid UE and 100 valid UE and observed a drop in ul/dl traffic, Please check the below logs.

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/57242fa3-1e7c-4c04-83ea-672eafc847f9)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/59464008-2e1a-4bc5-93ff-6e0b226e112f)
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/cca1bd4d-4b02-4f01-a2f2-a1c0d7faa37b)

**Comment by rupa455wavelabs** [comment] 2022-03-11 08:24
verification fail:  ((as_received_raw_bytes=9278000) 			>= (ue_sent_total_bytes=10000000)-((ue_sent_total_bytes=10000000)*0.01))  => False

[https://app.zenhub.com/files/170803235/264de4d5-a579-4914-8a19-2946994300f2/download](https://app.zenhub.com/files/170803235/264de4d5-a579-4914-8a19-2946994300f2/download)

**Comment by rupa455wavelabs** [comment] 2022-03-11 08:33
Re-Tested TC with 200 Invalid UE and 200 valid UE with 5 ue/s, observing a drop in ul/dl traffic, Please check the below logs.

Verdict Log:
verification fail:  ((as_received_raw_bytes=9278000) 			>= (ue_sent_total_bytes=10000000)-((ue_sent_total_bytes=10000000)*0.01))  => False

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/3ad954d2-7a2a-4590-a93e-aceb9dfbb555)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/c3dfe5fa-5043-4c52-8b19-4491335455c1)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/ce8868b3-ba77-4d43-b5c3-eba554d23efa)

**Comment by rupa455wavelabs** [comment] 2022-03-11 09:16
[https://app.zenhub.com/files/170803235/69d56b4a-fcce-4723-ac53-513c76c2d2df/download](https://app.zenhub.com/files/170803235/69d56b4a-fcce-4723-ac53-513c76c2d2df/download)

**Closed as completed** 2022-05-09 18:38 UTC
Labels: wontfix, product: 5g sa
