### ISSUE TITLE
Iphone 12 unable to Attach

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#4760] opened 2021-02-04 03:20 UTC
**Your Environment**
Version: 1.3.2-1607014227-1462d960
Affected Component: Access Gateway
Affected Subcomponent: mobilityd, MME
Deployment Environment: bare-metal (AGW)

**Describe the Issue**
iPhone 12 is unable to attach to the Network. The MME rejects Attach Request with Cause Code #99. Cause: Information element non-existent or not implemented (99).

Following are the observations from the logs:
1.) EIA0 is not supported by iPhone.
2.) In the request the APN is not carried, neither the ESM Transfer Flag is included that should ideally trigger ESM Information Request Message to get the APN information. (Refer Snapshot)
3.) ESM information Request Procedure didn't take place yet the MME didn't use default APN from the HSS Profile.
4.) EMM-REGISTERED w/o PDN connectivity: Not supported

3GPP Reference: 24.301 - h10 Rel 17

![Attach Reject](https://user-images.githubusercontent.com/77636702/106840210-504ebe80-6665-11eb-8b47-a6089e8d928e.PNG)

**Comment by shehzadalee** [comment] 2021-02-11 03:41
@sourabh-nanoti

**Comment by shehzadalee** [comment] 2021-02-15 23:32
@sourabh-nanoti and @ulaskozat Hello, could you please help us with this issue. We observed Iphone 12 is unable to attach to Magma EPC.
[dolcera_iphone12_reject.zip](https://github.com/magma/magma/files/5984603/dolcera_iphone12_reject.zip)

**Comment by ulaskozat** [comment] 2021-03-07 05:13
@shehzadalee after @jpad-freedomfi  provided the mme logs for the issue https://github.com/magma/magma/issues/4792, I identified that both pixel4 phone and iphone12 had MS Network Capability as 4 bytes while Magma (officially supports Rel 12 and in the process of supporting Rel 15) code base assumes that this IE is up to 3 bytes. It requires a minor modification to the code base and I sent the changes to @jpad-freedomfi  so that he can test against pixel4. Once he verifies, I will raise a PR that should close both this issue and issue #4792 once merged.

**Comment by ulaskozat** [comment] 2021-03-10 17:40
Current status: Besides extending MS Network Capability, I sent two more files for testing to @jpad-freedomfi to fix the UE Capabilities Replay. However, pcap shows that these fields were still not encoded. This is probably due to the asn release version mismatches.

**Comment by jpad-freedomfi** [comment] 2021-03-17 17:45
Hi @ulaskozat any updates here? We are starting to see this issue more often with more phones. Seems a bunch of newer phones are >Rel 12 signaling and making Magma 1.3.3 angry. 

Understand you've had a lot on your plate :) Just bumping thread as we just ran into it again with another customer.

**Comment by ulaskozat** [comment] 2021-03-17 17:54
@jpad-freedomfi did not have time to come back to this issue. Will try to coordinate with the OAI team to see if this can be handled as part of Rel 15 updates... Would you like to bring this issue into Monday meeting?

**Comment by edaspb** [comment] 2021-03-19 16:06
Hi, I think we observe the same issue.  Unfortunately I hadn't chance to trace the call but the symptoms are the same - Iphone 12 is  unable to attach. From ISP point of view the fact that any phone potentially can be upgraded and loose ability to connect to the network is very critical.

**Comment by ulaskozat** [comment] 2021-03-19 20:26
@edaspb, @jpad-freedomfi is testing release v1.4 for this as we bumped up from Rel 12 to Rel 15 on asn encoder/decoder, it looks like all the missing IEs are already supported in there.

**Comment by talkhasib** [comment] 2021-05-07 02:18
@jpad-freedomfi 
I was able to reproduce the decoding problem on 1.4
Issue seems to be resolved on Release 1.5. The fix was not backported to 1.4

Can we get the partner upgraded to 1.5?

**Comment by jpad-freedomfi** [comment] 2021-05-14 18:10
iPhone 12 tested with 1.5.0-1619628161-f023455f and iPhone 12 can attach and pass data. WooHoo!

**Closed as completed by jpad-freedomfi** 2021-05-14 18:10 UTC
