### ISSUE TITLE
sessiond crashed on AGW of Brisanet setup

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#8331] opened 2021-07-29 10:01 UTC

**Comment by ganeshg87** [comment] 2021-07-30 04:41
I have replied to Alves, waiting for response:

Ganesh Gedela  13 hours ago
@Gustavo Alves,
- it seems normal mme exit and does not seems to be related mme issue
 - problem statement refers to sessiond, but we could not find information related to it
 - incase if the problem is observed again, can you please share the following information
        1. mme.log(/var/log/mme.log)
		2. syslog(/var/log/syslog)
		3. crash back trace
		4. steps to reproduce
 - our testing setup we tried mentioned scenario and the issue was not seen, so the above logs mentioned were helpful.

**Comment by panyogesh** [comment] 2021-08-19 06:53
Marking it as closed as no more information is provided.

**Closed as completed by panyogesh** 2021-08-19 06:53 UTC
Labels: product: 5g sa
