### ISSUE TITLE
AGW MME is crashing when when enabling DHCP Server on 1.5 Orc8r

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [magma/magma#6841] opened 2021-05-09 01:13 UTC
### Your Environment

- **Version:** 1.5
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** Orchestrator
- **Deployment Environment:** e.g. AWS (orc8r), bare-metal (AGW),

### Describe the Issue

We need to use the DHCP BROADCAST function so that the IPs assigned to the IMSIs come from the different DHCP Server.

In the AGW 1.3 and Orc8r 1.3 it was working.

Now we are trying to activate DHCP_BROADCAST in the Orc8r - 1.5 with AGW 1.5 without succcess. When I disabled the NAT and sent the AGW reboot the MME service is OK but when I changed the EPC in the Network from NAT to DHCP_BROADCAST and stop the services and magmad restarted, the MME service is in cyclical restart.

**To Reproduce**
1. Go to: NMS -> Equipment -> Gateway -> Config -> Edit EPC -> 
2. Click on: switch the **Nat Enabled** button for disabling NAT.
3. Next: restart AGW from NMS only.
4. Once AGW is up check the status of MME `sudo service magma@mme status
[logs_dhcp_mme failed.zip](https://github.com/magma/magma/files/6446797/logs_dhcp_mme.failed.zip)
`

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).

**Comment by ShubhamTatvamasi** [comment] 2021-05-09 01:24
Is this issue is duplicate for #6508 ?

**Comment by jpad-freedomfi** [comment] 2021-05-12 16:06
@ShubhamTatvamasi we see same issue. it appears MME is looking to eth0 for the IP address even when bridge mode is enabled and IP has been moved to uplink_br0. Only way to fix is to disable bridge mode. 

This is a blocker for us as our biggest deployments use bridge mode.

**Comment by sudhikan** [comment] 2021-05-12 16:18
@jpad-freedomfi - just shooting in the dark here but what happens if you just run `dhclient eth0`? Does that stabilize the MME?

**Comment by pshelar** [comment] 2021-05-12 16:30
yes, it is same as issue #6508 and the fix is merged to master and 1.5.

**Comment by pkapatsos-blinq** [comment] 2021-05-13 18:45
Hi @pshelar just confirming this is fixed now( today 5/13)  and if we build Bare Metal from scripts either master or v1.5  or only code update?  What sub release of AGW is the fix in please ?  The AGW release with the issue is 1.5.0-1619628161-f023455f.
 Also confirming this for either Ubuntu or Debian AGW  as seeing this on both.
 Thanks @ShubhamTatvamasi

**Comment by pshelar** [comment] 2021-05-13 18:59
We will push new ubuntu build later today from latest v1.5 branch.

**Comment by pkapatsos-blinq** [comment] 2021-05-13 19:11
@pshelar is Debian R1.5 fixed ? or same later today ?

**Comment by pshelar** [comment] 2021-05-13 19:15
yes, debian too.

**Comment by pshelar** [comment] 2021-05-14 05:26
@pkapatsos-blinq can you try '1.5.0-1620963309-d2135127' build on ubuntu?

**Comment by pkapatsos-blinq** [comment] 2021-05-14 13:52
@pshelar Where do I get that specific build , sorry when I build via script master am getting 1.5.0-1619637540-f023455f still.

**Comment by pkapatsos-blinq** [comment] 2021-05-17 18:36
Hi @pshelar have you merged to master or guidance on how to get that version onto a Bare metal build ? 1.5.0-1620963309.
Anyone have this working on either OS yet?
thanks,

**Comment by pshelar** [comment] 2021-05-17 18:42
@pkapatsos-blinq you need to add test artifactory to you apt source (/etc/apt/sources.list.d/magma.list) file.
```
deb https://artifactory.magmacore.org/artifactory/debian-test focal-1.5.0 main 
```
After you run `apt update` you shld see the package.

**Comment by pkapatsos-blinq** [comment] 2021-05-17 19:04
@pshelar thanks once I added this test can see a few new items in the list including R1.6 . 
Ok so to update to this the specified release just run 
apt update
apt-get install magma=1.5.0-1620963309-d2135127
correct or another way ?

**Comment by pshelar** [comment] 2021-05-17 19:09
@pkapatsos-blinq yes, that would do it.

**Comment by pkapatsos-blinq** [comment] 2021-05-17 19:15
@pshelar thanks just wanted to be sure, I am at that release and still MME is resetting. 
![image](https://user-images.githubusercontent.com/61711855/118543364-328ffb80-b722-11eb-8635-d1787e99eddb.png)

![image](https://user-images.githubusercontent.com/61711855/118543576-6cf99880-b722-11eb-8136-17a301dea421.png)

Just wondering if this is working for you or on this release ?

**Comment by pshelar** [comment] 2021-05-17 19:19
yes, It works for me on bare metal AGW.
@ulaskozat can you have a look at this error.

**Comment by pkapatsos-blinq** [comment] 2021-05-17 19:20
@pshelar just we are sure is this for Ubuntu ? or Debian please have check as have both

**Comment by pshelar** [comment] 2021-05-17 19:25
This build is for ubuntu.

**Comment by pkapatsos-blinq** [comment] 2021-05-17 19:28
@pshelar Ok just checking as that is what I applied it on an Ubuntu host. Ok when will this release be added to master if it works ?
So I can build via script  and test please?

**Comment by pshelar** [comment] 2021-05-17 20:03
Required patches are already in master and 1.5 branch.

This is document about building magma AGW packages, let me know if you face any issues:
https://github.com/magma/magma/blob/master/docs/readmes/howtos/README_package.md#creating-a-development-package

**Comment by pkapatsos-blinq** [comment] 2021-05-17 20:37
@pshelar Ok thanks we aren't doing packages rather building bare metal AGWs using the agw_install.sh. See that may not work.
Also found that I needed to upgrade sctpd  to be the same release as well however still MME is reloading  
Let me redo a new one using master AGW script for Ubuntu.
of course the reason is we need physically to test our equipment  FWA eNB/CPEs on .

**Comment by pshelar** [comment] 2021-05-17 20:55
@pkapatsos-blinq the build process is useful when you are trying to upgrade AGW to latest code from a branch.

**Comment by jpad-freedomfi** [comment] 2021-05-19 01:11
@pshelar is this patch available in packages in artifactory 1.5 repo for debian?

**Comment by pshelar** [comment] 2021-05-19 15:37
it will be part of 1.5.1, the ETA is next week.

**Comment by pkapatsos-blinq** [comment] 2021-05-25 15:52
@pshelar HI, any eta on the Debian R1.5 fix or when R1.5.1 will be avail please.

**Closed as completed** 2021-06-30 13:07 UTC
Labels: type: bug, priority: high
