### ISSUE TITLE
subscriberdb service restarting

### ISSUE THREAD

**Issue by raphaelsander** [magma/magma#12655] opened 2022-05-09 12:34 UTC
### Your Environment

- **Version:** [v1.7.0](https://raw.githubusercontent.com/magma/magma/v1.7/lte/gateway/deploy/agw_install_ubuntu.sh)
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** subscriberdb service
- **Deployment Environment:** local docker-compose (orc8r) and bare-metal (AGW)

### Describe the Issue

The subscriberdb service is restarting with the error below:

```bash
root@magma-agw:~# journalctl -fu magma@subscriberdb.service
-- Logs begin at Wed 2022-05-04 13:41:40 UTC. --
mai 09 12:04:45 magma-agw subscriberdb[1374295]:     exec(code, run_globals)
mai 09 12:04:45 magma-agw subscriberdb[1374295]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/main.py", line 177, in <module>
mai 09 12:04:45 magma-agw subscriberdb[1374295]:     main()
mai 09 12:04:45 magma-agw subscriberdb[1374295]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/main.py", line 54, in main
mai 09 12:04:45 magma-agw subscriberdb[1374295]:     processor = Processor(
mai 09 12:04:45 magma-agw subscriberdb[1374295]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/processor.py", line 137, in __init__
mai 09 12:04:45 magma-agw subscriberdb[1374295]:     raise ValueError("AMF has invalid length len=%d value=%s" % (len(amf), amf))
mai 09 12:04:45 magma-agw subscriberdb[1374295]: ValueError: AMF has invalid length len=3 value=b'6\x89\xde'
mai 09 12:04:45 magma-agw systemd[1]: magma@subscriberdb.service: Main process exited, code=exited, status=1/FAILURE
mai 09 12:04:45 magma-agw systemd[1]: magma@subscriberdb.service: Failed with result 'exit-code'.
```

**To Reproduce**
1. Install orc8r and nms version 1.7 using the [Quick Starting Guide](https://docs.magmacore.org/docs/basics/quick_start_guide) in the first VM;
2. Install the AGW in another VM using the [Deploy Guide Bare Metal](https://docs.magmacore.org/docs/lte/deploy_install), but using version 1.7 instead version 1.6, because the documentation use 1.6 inside of 1.7 deploy. Maybe it's wrong...

![image](https://user-images.githubusercontent.com/11304987/167409912-705de627-df8e-44e0-a87a-a8e9535e49b5.png)

**Expected behavior**
A expected that the subscriberdb works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/11304987/167410061-80003b48-ddcb-4dda-a155-030ab5d0529c.png)

**Additional context**
[magma.zip](https://github.com/magma/magma/files/8651642/magma.zip)

**Comment by uri200** [comment] 2022-05-10 20:17
this may be caused by this PR

https://github.com/magma/magma/pull/9775

Hey @rupa455wavelabs  can you take a look please. Please, note i left a comment on that PR with some missing docstring

**Comment by panyogesh** [comment] 2022-05-11 01:56
Will check and update.

**Comment by Rajeshs23** [comment] 2022-06-09 03:45
we replicated the system installed orc8r ,nms version 1.7 and agw v1.7. We observed all the services are running fine and working as expected.[https://app.zenhub.com/files/170803235/ed515ee8-b067-4636-8655-229feba84330/download](https://app.zenhub.com/files/170803235/ed515ee8-b067-4636-8655-229feba84330/download)

**Comment by raphaelsander** [comment] 2022-06-09 23:15
Hi @Rajeshs23,

The problem happened because I changed the default 'LTE Auth AMF'.

![image](https://user-images.githubusercontent.com/11304987/172960034-dfd19b2e-d1e0-4eaa-8627-fa18f90751df.png)

Solved using the default value.

**Comment by Rajeshs23** [comment] 2022-06-10 02:42
Hi @raphaelsander Thanks for the confirmation. I am closing this issue since it is solved.

**Closed as completed by Rajeshs23** 2022-06-10 02:42 UTC
Labels: type: bug, component: agw, priority: medium, product: 5g sa
