### ISSUE TITLE
MME: Assertion (enb_association->nb_ue_associated == enb_association->ue_id_coll.num_elements) failed!

### ISSUE THREAD

**Issue by pshelar** [magma/magma#4993] opened 2021-02-17 03:04 UTC
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

**To Reproduce**
1. Apply PR: https://github.com/magma/magma/pull/4992
2. run test_continuous_random_attach.py multiple times

```
Feb 17 02:51:37 magma-dev mme[23881]: Assertion (enb_association->nb_ue_associated == enb_association->ue_id_coll.num_elements) failed!
Feb 17 02:51:37 magma-dev mme[23881]: In s1ap_handle_sctp_disconnection() /home/vagrant/magma/lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c:2297
Feb 17 02:51:37 magma-dev mme[23881]: Num UEs associated with eNB (4) is more than the UEs with valid mme_ue_s1ap_id (2). This is a deadlock state potentially caused by misbehaving eNB; restarting MME. In stateless mode, health management service will eventually detect multiple MME restarts due to this deadlock state and force sctpd and hence all services to restart.
Feb 17 02:51:37 magma-dev mme[23881]:  Will Intentionaly raise SEGFAULT to be catched by GDB!
Feb 17 02:51:37 magma-dev sctpd[7034]: I0217 02:51:37.635773  7481 sctp_connection.cpp:173] HandleClientSock sd = 20
Feb 17 02:51:37 magma-dev sctpd[7034]: I0217 02:51:37.635809  7481 sctp_connection.cpp:225] [sd:20] msg of len 51 on 2:0
Feb 17 02:51:37 magma-dev mme[23881]: Obtained 8 stack frames.
Feb 17 02:51:37 magma-dev mme[23881]: /usr/lib/x86_64-linux-gnu/libasan.so.3(backtrace+0x41) [0x7fe1e4d1b681]
Feb 17 02:51:37 magma-dev mme[23881]: /usr/local/bin/mme(display_backtrace+0xb2) [0x55f4faaa907e]
Feb 17 02:51:37 magma-dev mme[23881]: /usr/local/bin/mme(s1ap_handle_sctp_disconnection+0x7d3) [0x55f4fab44998]
Feb 17 02:51:37 magma-dev mme[23881]: /usr/local/bin/mme(+0xbaf595) [0x55f4faae6595]
Feb 17 02:51:37 magma-dev mme[23881]: /usr/lib/x86_64-linux-gnu/libczmq.so.4(zloop_start+0x47e) [0x7fe1e20cd7be]
Feb 17 02:51:37 magma-dev mme[23881]: /usr/local/bin/mme(+0xbb035c) [0x55f4faae735c]
Feb 17 02:51:37 magma-dev mme[23881]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x74a4) [0x7fe1e48ac4a4]
Feb 17 02:51:37 magma-dev mme[23881]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fe1e0c20d0f]
```

core: https://drive.google.com/file/d/1_RGtuShOEzX5l9BjQhcfJFcf25yee7fz/view?usp=sharing

**Comment by ssanadhya** [comment] 2021-03-31 20:10
It is worth checking if this issue still occurs, since we have landed some more fixes on cleaning up stale eNB state.

**Comment by ssanadhya** [comment] 2022-03-11 21:23
This is a duplicate of https://github.com/magma/magma/issues/8854, closing this one as fix is tracked there.

**Closed as completed by ssanadhya** 2022-03-11 21:23 UTC
Labels: wontfix, mme:core
