### ISSUE TITLE
magma services like td-agent-bit and subscriberd keeps restarting with SIGTERM

### ISSUE THREAD

**Issue by sganiger1** [magma/magma#13558] opened 2022-08-10 06:08 UTC
### Your Environment

- **Version:**
Magma AGW 1.6.1

- **Affected Component:** Orchestrator, Access Gateway, or NMS
AGW 

- **Affected Subcomponent:** Orchestrator pod/service or AGW service
magma services like td-agent-bit and subscriberd keeps restarting.

- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)
AWS

### Describe the Issue
It is observed that td-agent-bit and subscriberd restarts periodically with signal SIGTERM. This is because, the mconfig content of the corresponding services between periodic mconfig syncs by orc8r is shuffled as shown in the following screenshots. In other words, though the content is same between the syncs but the order of the contents is shuffled.  Which makes magmad to think this as the change in the config and restarts the respective service via systemd by sending SIGTERM.

#### To Reproduce
The issue starts popping up, only if magmad is restarted with following commands;
sudo service magma@* stop
sudo service magma@magmad restart 

#### Expected behavior
stable magmad services

#### Additional context

Add any other context about the problem here (e.g. logs).
![image](https://user-images.githubusercontent.com/87134057/183827451-b3ec731d-fbed-4abe-9d15-a6629200643b.png)
![image](https://user-images.githubusercontent.com/87134057/183827552-32ea1118-c776-4bc9-a27e-588bb452d66d.png)

**Comment by sebathomas** [comment] 2022-08-25 08:41
Planned tasks:
- [ ] Reproduce the error on current master. Spin up a local AGW connected to a local Orc8r and create mconfig entries similar to the two screenshots (either via Swagger or local NMS). (Basically, mconfig takes values from the orc8r db and sends them to magmad on the gateway. Magmad dumps them into a json file and restarts services if anything changed.)
  - If you cannot reproduce it on master, try reproducing it on v1.6.
- [ ] Fix the bug.
  - Possibly enforce an order of the values / list somewhere in the pipeline (in the cloud or on magmad)
  - Or the way magmad checks if mconfig changed could be adapted. See config_manager.py L145.
- [ ] Prepare internal review meeting.

**Comment by ajahl** [comment] 2022-08-26 12:27
We cannot reproduce the bug on the current master. No restart of td-agent-bit and subscriberd if the content is the same but the order of the contents changes, see output.


```
Aug 26 12:14:59 magma-dev magmad[150232]: INFO:root:MCONFIG subscriberdb old: b'\x08\x01\x12\x10\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x1a\x02\x80\x10"\x1d\n\x0fadditionalProp3\x12\n\x08\x80\xc2\xd7/\x10\x80\xda\xc4\t"\x1d\n\x0fadditionalProp2\x12\n\x08\x80\xc2\xd7/\x10\x80\xda\xc4\t"\x1d\n\x0fadditionalProp1\x12\n\x08\x80\xc2\xd7/\x10\x80\xda\xc4\t8\xc1\x02'
Aug 26 12:14:59 magma-dev magmad[150232]: INFO:root:MCONFIG subscriberdb new: b'\x08\x01\x12\x10\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x1a\x02\x80\x10"\x1d\n\x0fadditionalProp2\x12\n\x08\x80\xc2\xd7/\x10\x80\xda\xc4\t"\x1d\n\x0fadditionalProp3\x12\n\x08\x80\xc2\xd7/\x10\x80\xda\xc4\t"\x1d\n\x0fadditionalProp1\x12\n\x08\x80\xc2\xd7/\x10\x80\xda\xc4\t8\xc1\x02'

Aug 26 12:14:59 magma-dev magmad[150232]: INFO:root:MCONFIG td-agent-bit old: b'\n\x11\n\ngateway_id\x12\x03gw3\n\x12\n\nnetwork_id\x12\x04testP\xe8\x07X\x05b\x021m\xa2\x01\x1f\n\x07enodebd\x12\x14/var/log/enodebd.log\xa2\x01!\n\x08otherlog\x12\x15/var/log/otherlog.log\xa2\x01\x17\n\x03mme\x12\x10/var/log/mme.log'
Aug 26 12:14:59 magma-dev magmad[150232]: INFO:root:MCONFIG td-agent-bit new: b'\n\x12\n\nnetwork_id\x12\x04test\n\x11\n\ngateway_id\x12\x03gw3P\xe8\x07X\x05b\x021m\xa2\x01\x1f\n\x07enodebd\x12\x14/var/log/enodebd.log\xa2\x01!\n\x08otherlog\x12\x15/var/log/otherlog.log\xa2\x01\x17\n\x03mme\x12\x10/var/log/mme.log'
```

**Comment by ajahl** [comment] 2022-08-26 15:49
We got the same results with magma v1.6.1., no restarts if the content is the same.

**Comment by ajahl** [comment] 2022-08-26 15:53
@sganiger1 What is the content of the `gateway.mconfig` file in `magma-dev$ /var/opt/magma/configs/`?

**Comment by sganiger1** [comment] 2022-08-30 05:21
> What is the content of the `gateway.mconfig`

Following is the content of the gateway.mconfig.
"
root@ip-10-0-4-181:/home/admin# cat /var/opt/magma/configs/gateway.mconfig 
{"configsByKey":{"control_proxy":{"@type":"type.googleapis.com/magma.mconfig.ControlProxy","logLevel":"INFO"},"dnsd":{"@type":"type.googleapis.com/magma.mconfig.DnsD","logLevel":"INFO"},"enodebd":{"@type":"type.googleapis.com/magma.mconfig.EnodebD","logLevel":"INFO","pci":260,"bandwidthMhz":20,"plmnidList":"315010","allowEnodebTransmit":true,"tac":63,"tddConfig":{"earfcndl":44590,"subframeAssignment":2,"specialSubframePattern":7}},"eventd":{"@type":"type.googleapis.com/magma.mconfig.EventD","logLevel":"INFO","eventVerbosity":-1},"liagentd":{"@type":"type.googleapis.com/magma.mconfig.LIAgentD","logLevel":"INFO"},"magmad":{"@type":"type.googleapis.com/magma.mconfig.MagmaD","logLevel":"INFO","checkinInterval":60,"checkinTimeout":30,"autoupgradeEnabled":true,"autoupgradePollInterval":60,"packageVersion":"0.0.0-0","dynamicServices":["eventd","td-agent-bit"]},"metricsd":{"@type":"type.googleapis.com/magma.mconfig.MetricsD","logLevel":"INFO"},"mme":{"@type":"type.googleapis.com/magma.mconfig.MME","logLevel":"INFO","mcc":"315","mnc":"010","tac":63,"mmeGid":1,"mmeCode":1,"lac":1,"mmeRelativeCapacity":255},"mobilityd":{"@type":"type.googleapis.com/magma.mconfig.MobilityD","logLevel":"INFO","ipBlock":"192.168.128.0/24","ipAllocatorType":"DHCP","staticIpEnabled":true,"multiApnIpAlloc":true},"ovpn":{"@type":"type.googleapis.com/magma.mconfig.OpenVPN"},"pipelined":{"@type":"type.googleapis.com/magma.mconfig.PipelineD","logLevel":"INFO","ueIpBlock":"192.168.128.0/24","defaultRuleId":"default_rule_1","services":["ENFORCEMENT"],"liUes":{},"sgiManagementIfaceVlan":"510","heConfig":{}},"policydb":{"@type":"type.googleapis.com/magma.mconfig.PolicyDB","logLevel":"INFO"},"sessiond":{"@type":"type.googleapis.com/magma.mconfig.SessionD","logLevel":"INFO","walletExhaustDetection":{}},"subscriberdb":{"@type":"type.googleapis.com/magma.mconfig.SubscriberDB","logLevel":"INFO","lteAuthOp":"EREREREREREREREREREREQ==","lteAuthAmf":"gAA=","subProfiles":{"deviceGroup-0171b7d2-bb11-4954-99f1-29a54f354673":{"maxUlBitRate":"200000000","maxDlBitRate":"200000000"},"deviceGroup-3447062e-ae6a-466a-ac45-b9d82ff94286":{"maxUlBitRate":"200000000","maxDlBitRate":"200000000"},"deviceGroup-4f347e47-0091-47f6-ba06-9b720d4a07a8":{"maxUlBitRate":"200000000","maxDlBitRate":"200000000"},"deviceGroup-9612ae49-6635-4c0c-86ba-84e478b4e710":{"maxUlBitRate":"200000000","maxDlBitRate":"200000000"}}},"td-agent-bit":{"@type":"type.googleapis.com/magma.mconfig.FluentBit","extraTags":{"gateway_id":"edge-f93c44c2-d241-4938-8916-ed8cd2a5f5ca","network_id":"ns-40996983-bc62-4334-93c6-2a15b4489d46"},"throttleRate":1000,"throttleWindow":5,"throttleInterval":"1m","filesByTag":{"mme":"var/log/mme.log"}}},"metadata":{"created_at":1661836682}}root@ip-10-0-4-181:/home/admin# 

"
We don't have any special/specific config done.

**Comment by sganiger1** [comment] 2022-08-30 05:24
> We got the same results with magma v1.6.1., no restarts if the content is the same.

Once all the magma services are up, please do restart the magma services to recreate the issue, using the following commands;
sudo service magma@* stop
sudo service magma@magmad restart

**Comment by ajahl** [comment] 2022-09-01 08:36
@sganiger1  Following your mconfig, I created a similar configuration using the Swagger UI. However, running the services afterwards doesn’t result in a periodically restart of services in any case.

**Comment by sganiger1** [comment] 2022-09-07 03:35
@voisey 
Please let me know exactly what environment details you are looking for? As mentioned we are using magma 1.6..1. Not sure if in the LATEST magma it has got fixed. As I already mentioned it will be difficult for us to move to LATEST of magma. So, if you want any info let me know, with that also if the issue is not reproducible then you can close the ticket.

**Comment by voisey** [comment] 2022-09-07 09:52
Thanks for the response. We tried reproducing it with 1.6.1 and weren't able to, so without specific step-by-step instructions I think we'll have to close the issue. If you are able to produce a set of minimal instructions that lead to the problem, please let us know and we can reopen it :slightly_smiling_face:

**Closed as completed by voisey** 2022-09-07 09:52 UTC
Labels: type: bug, component: agw
