### ISSUE TITLE
[MME][stateless] Segfault in `send_msg_to_task` when handling `AuthenticationInformationAnswer`

### ISSUE THREAD

**Issue by themarwhal** [magma/magma#4891] opened 2021-02-10 19:57 UTC
### Your Environment

- **Version:** 1.4.0-1612835484-0b35bbf7
- AGW, MME

### Describe the Issue

Seeing the following backtrace in MME core.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055c73b2e09da in send_msg_to_task (task_zmq_ctx_p=<optimized out>, destination_task_id=<optimized out>, message=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/lib/itti/intertask_interface.c:121
121	/home/vagrant/magma/lte/gateway/c/oai/lib/itti/intertask_interface.c: No such file or directory.
[Current thread is 1 (Thread 0x7fdbb01d0700 (LWP 377))]
(gdb)
(gdb) bt
#0  0x000055c73b2e09da in send_msg_to_task (task_zmq_ctx_p=<optimized out>, destination_task_id=<optimized out>, message=<optimized out>) at /home/vagrant/magma/lte/gateway/c/oai/lib/itti/intertask_interface.c:121
#1  0x000055c73b1fb815 in _s6a_handle_authentication_info_ans (imsi="001011234565083", imsi_length=15 '\017', status=..., response=...) at /home/vagrant/magma/lte/gateway/c/oai/lib/s6a_proxy/s6a_client_api.cpp:103
#2  0x000055c73b1fb8ef in <lambda(grpc::Status, magma::feg::AuthenticationInformationAnswer)>::operator()(grpc::Status, magma::feg::AuthenticationInformationAnswer) const (__closure=0x603000040d10, status=..., response=...)
    at /home/vagrant/magma/lte/gateway/c/oai/lib/s6a_proxy/s6a_client_api.cpp:118
#3  0x000055c73b1fc667 in std::_Function_handler<void(grpc::Status, magma::feg::AuthenticationInformationAnswer), s6a_authentication_info_req(const s6a_auth_info_req_t*)::<lambda(grpc::Status, magma::feg::AuthenticationInformationAnswer)> >::_M_invoke(const std::_Any_data &, <unknown type in /usr/local/bin/mme, CU 0x1696734, DIE 0x16c06ce>, <unknown type in /usr/local/bin/mme, CU 0x1696734, DIE 0x16c0756>) (__functor=..., __args#0=<unknown type in /usr/local/bin/mme, CU 0x1696734, DIE 0x16c06ce>,
    __args#1=<unknown type in /usr/local/bin/mme, CU 0x1696734, DIE 0x16c0756>) at /usr/include/c++/6/functional:1731
#4  0x000055c73b201463 in std::function<void (grpc::Status, magma::feg::AuthenticationInformationAnswer)>::operator()(grpc::Status, magma::feg::AuthenticationInformationAnswer) const (this=0x61500013d588, __args#0=..., __args#1=...)
    at /usr/include/c++/6/functional:2127
#5  0x000055c73b201222 in magma::AsyncLocalResponse<magma::feg::AuthenticationInformationAnswer>::handle_response (this=0x61500013d580) at /home/vagrant/build/c/magma_common/async_grpc/GRPCReceiver.h:126
#6  0x000055c73b2c6cfa in magma::GRPCReceiver::rpc_response_loop (this=0x55c73b8b7da0 <magma::S6aClient::get_instance()::client_instance>) at /home/vagrant/magma/orc8r/gateway/c/common/async_grpc/GRPCReceiver.cpp:30
#7  0x000055c73b1fde61 in magma::S6aClient::<lambda()>::operator()(void) const (__closure=0x601000005f78) at /home/vagrant/magma/lte/gateway/c/oai/lib/s6a_proxy/S6aClient.cpp:113
#8  0x000055c73b1febb2 in std::_Bind_simple<magma::S6aClient::S6aClient()::<lambda()>()>::_M_invoke<>(std::_Index_tuple<>) (this=0x601000005f78) at /usr/include/c++/6/functional:1391
#9  0x000055c73b1feb4f in std::_Bind_simple<magma::S6aClient::S6aClient()::<lambda()>()>::operator()(void) (this=0x601000005f78) at /usr/include/c++/6/functional:1380
#10 0x000055c73b1feb2e in std::thread::_State_impl<std::_Bind_simple<magma::S6aClient::S6aClient()::<lambda()>()> >::_M_run(void) (this=0x601000005f70) at /usr/include/c++/6/thread:197
#11 0x00007fdbc66c7e6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007fdbc9ac84a4 in start_thread (arg=0x7fdbb01d0700) at pthread_create.c:456
#13 0x00007fdbc5e3cd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by themarwhal** [comment] 2021-02-10 19:58
Will attach logs+core in a moment...

**Comment by themarwhal** [comment] 2021-02-10 21:39
Core: [2021-Feb-10-08-03-20-core-1612972994-ITTI.zip](https://github.com/magma/magma/files/5961663/2021-Feb-10-08-03-20-core-1612972994-ITTI.zip)
Executable: [mme.zip](https://github.com/magma/magma/files/5961664/mme.zip)
Logs:  [Archive.zip](https://github.com/magma/magma/files/5961674/Archive.zip)

**Comment by ssanadhya** [comment] 2021-03-31 18:21
Closing this as it is a duplicate of #5287

**Closed as completed by ssanadhya** 2021-03-31 18:21 UTC
Labels: priority: high, v1.5, mme:core, workstream: AGW perf, v1.6
