### ISSUE TITLE
[Magma SA - TeraVM] UE Reg fails with immediate SCTP aborts

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#7293] opened 2021-06-03 02:46 UTC
Scenario & Issue description: 

- 4gNBs initiate Ngap Setup request and Magma AGW responds with successful Ngap Response for all 4 gNBs.

- **Initiate UE Registration with SUPI as IMSI and SUCI as id, Immediately AGW breaks the SCTP connection with shutdown followed by Aborts.**

AGW SA Build:  
magma | 1.5.0-1622665804-a126cbd1 | https://artifactory.magmacore.org/artifactory/debian-test stretch-5g/main amd64 Packages

Note: 
Initial phase of CI based AGW SA build test.
First time UE Registration test using TeraVM tool
 
Enclosed the pcap, mme and syslogs for references.

[https://app.zenhub.com/files/170803235/cb907d3f-225a-458a-a3ee-ca509d643b84/download](https://app.zenhub.com/files/170803235/cb907d3f-225a-458a-a3ee-ca509d643b84/download)[https://app.zenhub.com/files/170803235/082714fb-987c-4fe5-8310-f8dc2557ce8c/download](https://app.zenhub.com/files/170803235/082714fb-987c-4fe5-8310-f8dc2557ce8c/download)

**Comment by ulaskozat** [comment] 2021-06-03 04:45
coredump:

[https://app.zenhub.com/files/170803235/7fca95dc-1fdd-4ae5-8ea6-3be5e13791fc/download](https://app.zenhub.com/files/170803235/7fca95dc-1fdd-4ae5-8ea6-3be5e13791fc/download)

mme.log:

[https://app.zenhub.com/files/170803235/4c6f98ff-134c-4142-b062-887dbdfafe34/download](https://app.zenhub.com/files/170803235/4c6f98ff-134c-4142-b062-887dbdfafe34/download)

syslog:

[https://app.zenhub.com/files/170803235/e0b8bf7d-1ccc-47a1-af48-eb149b5c551e/download](https://app.zenhub.com/files/170803235/e0b8bf7d-1ccc-47a1-af48-eb149b5c551e/download)

**Comment by panyogesh** [comment] 2021-06-07 06:29
I have to still check the Backtrace.  In the setup used locally this issue was not seen (the crash seems obvious).
Reason for the difference in behavior seems to be the way the uninitialized variables are filled up. In the setup used locally its using 0xbebebe... which is in the perimeter of flag check.  Hence the if check is success.

Attaching the snapshot :
gdb) bt
#0  magma5g::amf_proc_authentication (amf_context=0x61c00003f890, amf_specific_proc=0x60c000035a40,
    success=0x564cbb441e29 <magma5g::amf_registration_success_authentication_cb(magma5g::amf_context_s*)>,
    failure=0x564cbb443356 <magma5g::amf_registration_failure_authentication_cb(magma5g::amf_context_t*)>)
    at /home/vagrant/magma/lte/gateway/c/oai/tasks/amf/amf_authentication.cpp:346


(gdb) p /x amf_context->_security.eksi
$4 = 0xbe
(gdb) p amf_context->member_valid_mask
$5 = 3200171710
(gdb) p /x amf_context->member_valid_mask
$6 = 0xbebebebe
(gdb) p ((uint32_t) 1 << 7)
$7 = 128
(gdb) p /x ((uint32_t) 1 << 7)
$8 = 0x80
(gdb) p /x amf_context->member_valid_mask & ((uint32_t) 1 << 7)
$9 = 0x80
(gdb) p /x (amf_context->member_valid_mask & ((uint32_t) 1 << 7))
$10 = 0x80
(gdb)

It seems in TerraVM's setup this is initializing to 0 hence its going to the else part of the code. 
Clean up and the fix is in progress. Will update shortly on the same.

**Comment by panyogesh** [comment] 2021-06-07 09:34
[https://app.zenhub.com/files/170803235/2271b548-e49b-4a1b-aabf-0be01cbe2276/download](https://app.zenhub.com/files/170803235/2271b548-e49b-4a1b-aabf-0be01cbe2276/download)After memset'ing few variables we are able to reproduce the issue at local setup.

**Comment by panyogesh** [comment] 2021-07-07 09:33
Closed as part of #7439

**Closed as completed by panyogesh** 2021-07-07 09:33 UTC
Labels: type: bug, product: 5g sa
