### ISSUE TITLE
Add support for PDU session ResourceSetupResponse failure from gNB

### ISSUE THREAD

**Issue by sureshgorijavolu** [magma/magma#6575] opened 2021-04-30 17:51 UTC

**Comment by sureshgorijavolu** [comment] 2021-05-04 15:42
these changes need to be supported on NGAP

**Comment by ganeshg87** [comment] 2021-09-09 07:33
this issue is duplicate of https://app.zenhub.com/workspaces/magma--5g-sa-60871e99b9326f001696b1ee/issues/magma/magma/8905

**Closed as completed by ganeshg87** 2021-09-09 07:33 UTC
Labels: component: agw, type: feature, product: 5g sa
