### ISSUE TITLE
[AGW] Problem with generation of gateway.mconfig file during the initial installation of AGW

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#11044] opened 2022-01-03 16:06 UTC
- Version: 1.7.0-1640908182-e6e795fd
- Affected Component: Access Gateway, NMS
-  Affected Subcomponent: Orchestrator service or AGW service
- Deployment Environment: Vagrant (AGW)

### Describe the Issue
During initial installation of AGW gateway.mconfig file is not getting generated in the /var/opt/magma/configs path even after disabling the stateless feature.
As configurations from NMS will get reflected into the respective file , it is effecting the issue with some of configuration that has to be done from NMS-Dashboard/ Swagger API.

 **To Reproduce**
1. Bring up the VM with the AGW installed.
2. Upgrade the AG to the latest version.
3. Disable the stateless feature 
4. Check that config directory is getting generated in the bellow path.
    cd /var/opt/magma
5. check that gateway.mconfgi file is getting generated along with all other files in  "cd /var/opt/magma/configs ".

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/9196b43b-0da0-49a3-89d0-286e82bb7757)

**Expected behavior**
All files should get generated properly.

Note : MCC , MNC and other configurations that has to be done from Orc8 are getting affected as those configurations will be ported to gateway.mconfig file in /var/opt/magma directory.

**Comment by anusha-konda** [comment] 2022-01-05 12:30
Based on the logs, magmad is unable to fetch the updates from Orc8r while accessing nil pointer. The issue is fixed with merge of these PRs #10717 , #10758 . Please update the Orc8r deployment.

**Comment by NeelimaKalpana** [comment] 2022-01-05 14:03
By committing 'ngc' changes into respective JSON data file gateway.mconfig file got generated .

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/29aae002-b76e-45a5-bfc3-d045a67d1ae9)
After the commit and even any parameter config changes(Eg.: MCC and MNC) are getting reflected in the gateway.mconfig file.

**Comment by NeelimaKalpana** [comment] 2022-03-02 11:59
Need to validate after Orc8r upgradation is done.

**Comment by rupa455wavelabs** [comment] 2022-03-23 07:19
closing this issue, as gateway.mconfig file is generating during the initial installation of AGW.
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/98ddf081-7f02-47c3-ad60-6ee825e0217d)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/d8e7976a-ddbb-4ef4-8563-9dabf6ce63d1)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/1236b582-bb5a-486b-8ac9-3c7d858cf675)

**Closed as completed** 2022-03-23 07:19 UTC
Labels: type: bug, product: 5g sa
