### ISSUE TITLE
NMS Dashboard Metrics collection 

### ISSUE THREAD

**Issue by rupa455wavelabs** [magma/magma#11344] opened 2022-02-01 05:22 UTC
Hi @anusha-konda,

we configured the 5MB per UE of throughput in spirent AGW and executing the TC around 1hour, but in grafana  dashboard we  are observing Throughput in Kbps and Data Usage in MBs. can you please let us know how throughput is calculated in grafana dashboard

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/4f15ad6b-422b-40f4-86e6-2c7d28d9d816)

we need some information about what is this latency related to 

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/c38bd383-16c8-4149-9873-0a0e25372b09)

we are unable to see the data related to Connections, Traffic, ServiceRequests, S6a and Sessions in Gateways section and we are unable to see the data related to Connections, S1,Attach/Detach,Connection Status, ServiceRequests and S6a.  
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/7d23d245-3a60-4563-951d-6a947e976522)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/3c2f7202-5799-4c07-acaa-79e0a5e45336)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/748c4680-4858-4668-ae7e-5cfe4975ac6e)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/a7dc09bf-61b3-4573-8af3-8b69b67cd636)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/20f9ffdd-ba2f-46e5-bd53-782818049225)

![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/75e91ae1-321b-4017-84a6-e21bb81b5d98)

**Comment by shivesh-wavelabs** [comment] 2022-02-08 13:24
Latency is basically the response time of gateway magmad service on pinging 8.8.8.8 which is extracted using a promoql query for grafana =>
magmad_ping_rtt_ms{gatewayID=~"$gatewayID",networkID=~"$networkID",metric="rtt_ms"}

**Comment by rupa455wavelabs** [comment] 2022-02-09 13:50
Hi @anusha-konda, As you suggested I have executed the below commands to check UL/DL stats for the IMSI.
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d UL stats
IMSI: 222450000000101, IP: 192.168.127.145
UL stats: n_packets=61755, n_bytes=61755000
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d DL stats
IMSI: 222450000000101, IP: 192.168.127.145
LOCAL: n_packets=165960, n_bytes=168283440
mtr0: n_packets=0, n_bytes=0
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d DL stats
IMSI: 222450000000101, IP: 192.168.127.145
LOCAL: n_packets=256020, n_bytes=259604280
mtr0: n_packets=0, n_bytes=0
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d UL stats
IMSI: 222450000000101, IP: 192.168.127.145
UL stats: n_packets=347154, n_bytes=347154000
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d UL stats
IMSI: 222450000000101, IP: 192.168.127.145
UL stats: n_packets=452280, n_bytes=452280000
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d DL stats
IMSI: 222450000000101, IP: 192.168.127.145
LOCAL: n_packets=556455, n_bytes=564245370
mtr0: n_packets=0, n_bytes=0
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d UL stats
IMSI: 222450000000101, IP: 192.168.127.145
UL stats: n_packets=707598, n_bytes=707598000
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d DL stats
IMSI: 222450000000101, IP: 192.168.127.145
LOCAL: n_packets=826845, n_bytes=838420830
mtr0: n_packets=0, n_bytes=0
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d UL stats
IMSI: 222450000000101, IP: 192.168.127.145
UL stats: n_packets=932874, n_bytes=932874000
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d DL stats
IMSI: 222450000000101, IP: 192.168.127.145
LOCAL: n_packets=1037001, n_bytes=1051519014
mtr0: n_packets=0, n_bytes=0
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d UL stats
IMSI: 222450000000101, IP: 192.168.127.145
UL stats: n_packets=1143075, n_bytes=1143075000
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d DL stats
IMSI: 222450000000101, IP: 192.168.127.145
LOCAL: n_packets=1292219, n_bytes=1310310066
mtr0: n_packets=0, n_bytes=0
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d UL stats
IMSI: 222450000000101, IP: 192.168.127.145
UL stats: n_packets=1398165, n_bytes=1398165000
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d DL stats
IMSI: 222450000000101, IP: 192.168.127.145
LOCAL: n_packets=1532277, n_bytes=1553728878
mtr0: n_packets=0, n_bytes=0
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d UL stats
IMSI: 222450000000101, IP: 192.168.127.145
UL stats: n_packets=1653330, n_bytes=1653330000
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d DL stats
IMSI: 222450000000101, IP: 192.168.127.145
LOCAL: n_packets=1742433, n_bytes=1766827062
mtr0: n_packets=0, n_bytes=0
magma@TVM3-SA-dev:~$ sudo dp_probe_cli.py --imsi 222450000000101 -d DL stats
UE is not connected


Here I am sending 240 MBPS per 60 seconds.
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/ff5e722c-0f22-4249-a84b-849190ef93bf) 

In the NMS dashboard I am seeing maximum throughput as 14.7MB.
![image.png](https://images.zenhubusercontent.com/60b481800aaaeba6be231e62/a6111c3d-0b1f-4611-9bc3-e77433454d59)

**Comment by shivesh-wavelabs** [comment] 2022-02-15 11:40
Throughput In is calculated on the average rate of reported downlink data usage of UE for 5 minutes interval time.
Throughput Out is calculated on the average rate of reported uplink data usage of UE for 5 minutes interval time.
Both are extracted from Prometheus using following queries respectively - 

1. avg(rate(ue_reported_usage{msisdn=~"$msisdn", direction="down"}[5m])) by (IMSI, apn, msisdn)
2. avg(rate(ue_reported_usage{msisdn=~"$msisdn", direction="up"}[5m])) by (IMSI, apn, msisdn)

**Comment by NeelimaKalpana** [comment] 2022-04-19 13:19
Hi Sabitha,

In the latest Orc8r version we are observing issue with UE data usage reporting in the graphana.

We are pumping 2600000 bits/Sec(0.3 MB) for 15 Sec .

so total UE usage should be (0.3 * 60) * 15  = 270 MB UL and DL. 
But in Graphan UE usage reporting I am observing less than utilized . Please find below graph for the same.

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/9fb23e83-e7de-4d2d-86f0-cc348036c7c5)


I can see throughput in/out are getting populated properly and same thing is getting updated/reflected in subscriber data usage Page. 

![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/1a8db966-b9f6-4295-a4e9-e1b25007dffa)

And Hourly usage is also not getting calculated properly.
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/ec08070c-46a8-4d14-81a5-38a640ed7556)

Per hour it is showing only 0.05MB but I am expecting 270 MB.

Please look into this and let me know if there is some mismatch in my understanding.

**Comment by anusha-konda** [comment] 2022-04-20 05:24
Hi Neelima,
Is the "Current Usage" similar as "UE Data Usage" dispalyed in Grafana. ?
Can you also please share the cli output of the below commands 
 "sudo dp_probe_cli.py --imsi <IMSI> -d DL stats"
 "sudo dp_probe_cli.py --imsi <IMSI> -d UL stats"

**Comment by apekshapk** [comment] 2022-08-19 07:19
Please find the attached working snapshots.
Tested Single UE with Multiple PDU sessions and traffic on latest **master build-1.8.0-1660761818-d00be5c4**. The graph being reflected at the Grafana is updated as per the configurations.  

Attaching the pcap of the tested scenario:
[https://app.zenhub.com/files/170803235/41327d7b-5660-48e1-a616-5870352910cc/download](https://app.zenhub.com/files/170803235/41327d7b-5660-48e1-a616-5870352910cc/download)

Subscribed IMSI - IMSI001019976545662 and DNN - internet1
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/3d56b3d7-2fa7-4aa8-b8a4-a4a42d158d56)

Subscribed IMSI - IMSI001019976545662 and DNN - internet2
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/19331a3e-be66-405d-8469-00afeb6eff89)

![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/e221c2a8-0b24-4b2a-b738-a90fd83de366)
![image.png](https://images.zenhubusercontent.com/61bb050c5a4b60928b83af15/d7104654-f84f-41a9-84b4-df1204cd3ca3)

NOTE: Closing the Bug as the issue is resolved.

**Closed as completed by apekshapk** 2022-08-19 07:19 UTC
Labels: type: bug, product: 5g sa
