### ISSUE TITLE
perf: state service is using 75% of core

### ISSUE THREAD

**Issue by pshelar** [magma/magma#8978] opened 2021-09-07 22:59 UTC
### Your Environment

- **Version:** master
- **Affected Component:** \Access Gateway
- **Affected Subcomponent:** state
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

after deploying latest master in bare metal AGW, the state service started using 75% of core. it looks like related sync-interval. #8482
after manually setting sync-interval to 60, CPU utilization goes back to zero.

**Expected behavior**
state service should not take this much CPU.

**Comment by electronjoe** [comment] 2021-09-08 13:14
On the bare metal AGW running latest master - can somebody with access confirm whether the new `sync_interval` configuration field is successfully being written to the AGW's YAML config files?

Looking at the parameter's passing and parsing, it's absence could very well lead to a `sync_interval = 0`. Broadly this is a problem with all of Magma's configuration today (zero validation possible... aside from sentinel / default value checking if they are truly bad). See #8991

**Comment by electronjoe** [comment] 2021-09-08 13:37
I'm also seeing inconsistent review comments and committed code (I think?).  I see Hunter suggesting that the new State config `sync_interval` should be no smaller than `60` -> one presumes seconds but no units are provided on the configuration field name (ideal) or in comments (fallback). See @hcgatewood [comment on the PR](https://github.com/magma/magma/pull/8482#discussion_r687205781).  But in committed SWAGGER side config at least, [the minimum seems to have landed at 3](https://sourcegraph.com/github.com/magma/magma/-/blob/orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml?L1461-1470&subtree=true)?

I would like to know if the failure mode we are seeing is attempting a `sync_interval` of zero (e.g. field unset or lost in some handoff in the chain), or three?

Also wondering which configuration parameter you over-rode @pshelar  in your test to set it to `60`.  I see more than one `sync_interval` [specified by our configurations](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/magma/magma%24+lang:%22Protocol+Buffer%22+sync_interval&patternType=literal). I presume subscriberdb variant is not at play? Just the `State.sync_interval` configuration? [Edit: this is digested on state service here](https://sourcegraph.com/github.com/magma/magma/-/tree/orc8r/gateway/python/magma/state). I actually spot a **third** instance of `sync_interval` [in our fabfile.py](https://sourcegraph.com/github.com/magma/magma@ccf6b1c5e13f1919e82adf37b2880efe42d25906/-/blob/lte/gateway/fabfile.py?L211:42&subtree=true) - but this appears to me to be ~deprecated and dangling?

**Comment by electronjoe** [comment] 2021-09-08 13:56
I'm also [concerned about these changes in the associated PR](https://github.com/magma/magma/pull/8482/files#diff-0009f5293ae6e186c3498a1e8fb5f266b481e5cf836d14098d881132417ce9f7L58-R67), but so far lack enough context.

Specifically is `service_config_sync_interval` reliably set to `None` in absence? I am not sure what a `service config` is, but it sounds deprecated per comment in this PR (edit: it is [documented here](https://docs.magmacore.org/docs/lte/dev_notes) and consists of a YAML file in the path of `/etc/magma/State.yml`).  If `service_config_sync_interval` is not set to `None` in absence (e.g. by the YAML lib we are using), then this logic appears to pull e.g. `zero` if that were the value, and use it for the `State` daemon's `sync_interval`?

**Comment by electronjoe** [comment] 2021-09-08 16:26
@pshelar noted in chat:

`on my setup, the mconfig value is zero, so it would not work.`

So it seems that somewhere:

- The mconfig configuration is lost in transit from Orc8r to AGW
- We are operating on a zero-value `State.sync_interval` when we probably should do otherwise

Also:

`I tried setting 'sync_interval' in state yml which did not help due to lower value check. I am not sure why only lower sync_interval from yml is allowed.`

There is uncertainty as to why the value comparisons are happening in [this logic of the PR](https://github.com/magma/magma/pull/8482/files#diff-0009f5293ae6e186c3498a1e8fb5f266b481e5cf836d14098d881132417ce9f7R62-R66).

**Comment by uri200** [comment] 2021-09-08 20:01
As mentioned in other places, and just for the record, note sync interval needs to be set to lower values for federated cases (right now we are recommending 4s)

TerraVm Has been using that value for months without any problem

The need of having this synch_interval to low value is described here
https://github.com/magma/magma/issues/8925

**Comment by pshelar** [comment] 2021-09-08 21:49
> I'm also seeing inconsistent review comments and committed code (I think?). I see Hunter suggesting that the new State config `sync_interval` should be no smaller than `60` -> one presumes seconds but no units are provided on the configuration field name (ideal) or in comments (fallback). See @hcgatewood [comment on the PR](https://github.com/magma/magma/pull/8482#discussion_r687205781). But in committed SWAGGER side config at least, [the minimum seems to have landed at 3](https://sourcegraph.com/github.com/magma/magma/-/blob/orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml?L1461-1470&subtree=true)?
> 
> I would like to know if the failure mode we are seeing is attempting a `sync_interval` of zero (e.g. field unset or lost in some handoff in the chain), or three?
> 
> Also wondering which configuration parameter you over-rode @pshelar in your test to set it to `60`. I see more than one `sync_interval` [specified by our configurations](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/magma/magma%24+lang:%22Protocol+Buffer%22+sync_interval&patternType=literal). I presume subscriberdb variant is not at play? Just the `State.sync_interval` configuration? [Edit: this is digested on state service here](https://sourcegraph.com/github.com/magma/magma/-/tree/orc8r/gateway/python/magma/state). I actually spot a **third** instance of `sync_interval` [in our fabfile.py](https://sourcegraph.com/github.com/magma/magma@ccf6b1c5e13f1919e82adf37b2880efe42d25906/-/blob/lte/gateway/fabfile.py?L211:42&subtree=true) - but this appears to me to be ~deprecated and dangling?

To avoid any changes the sync-interval calculation,  I set the value directly in python code :-)

**Comment by mstre123** [comment] 2021-09-09 00:57
Sorry catching up to this
**Variable Name**
The sync interval at issue here is State.SyncInterval - the subscriberdb variable while sharing the same name is distinct from the change in https://github.com/magma/magma/pull/8482
**Minimum Value**
In the conversation of the PR there was some back and forth about the minimum value. From orc8r's perspective we thought 60 seconds made sense as a minimum as it was the current default value, but as Oriol noted above there was concern that we had existing partners that had this value set to 4 seconds.
A compromise was reached to continue to honor shorter sync intervals in the interim as we migrated partners towards setting the value through the orc8r.
https://github.com/magma/magma/pull/8482#issuecomment-906723373
**Cause of Spike**
Re root cause we'll need to dig into this. 

To see the actual value being set I'd log the value being used here
https://github.com/magma/magma/pull/8482/files#diff-0009f5293ae6e186c3498a1e8fb5f266b481e5cf836d14098d881132417ce9f7R68

The default of the builder should lead to a setting of 60 seconds if no value is passed in.
https://github.com/magma/magma/pull/8482/files#diff-0009f5293ae6e186c3498a1e8fb5f266b481e5cf836d14098d881132417ce9f7R68
and we test that here
https://github.com/magma/magma/pull/8482/files#diff-eda01236cac484aeeb25fe5c04b7a52a6b7e63d1555f146d9c9d0964fe66caceR343

In testing the pr before landing I ran a local instance of AGW using vagrant and a local instance of orc8r using docker.
@pshelar lets sync offline about replicating your bare metal deployment with logging added so we can see what's happening.

**Comment by mstre123** [comment] 2021-09-09 22:13
Took a look at this today
**Behavior**
if you start the AGW without an instance of orc8r connected the value defaults to 0.
If you start an instance of orc8r the value defaults to 0, once you set the field however via the rest api, since we have validation and no delete call it cant be unset and it works properly.

**Fix**
The short term fix for this is to enforce a default in the sync_replicator.py code to ensure we aren't setting a value below our accepted minimum. We need to do this here since we have to many spots where this configuration value can be set to be comfortable that future changes won't lead to corruption.
The longer term fix will be tied to #8991 

**Why wasn't this caught in testing**
This slipped through for two reasons

1. Restarting orc8r does not delete stored values in the db - once we set the sync_interval in the state_config it persists in the db even if you delete the docker containers and rebuild - only way to remove is to purge the docker volumes storing the db
2. Restarting AGW in your vm does not purge existing mconfigs stored in the vm.

Thus when i thought i was testing a clean state - i was really using persisted values.
To test the default experience properly you're required to purge your vagrant and docker volumes - which isn't particularly sustainable, or manually entering your postgress db in orc8r and deleting the state config, and going into your mconfig files in the agw vm and manually changing them.

**Future Suggestions**
In AGW we should add a target to the makefile that resets configs for debug testing
In Orc8r we should add a target to the python build tool that resets the db

**Comment by hcgatewood** [comment] 2021-09-16 20:55
My followup: this change is not super important at this point, so we can leave it reverted / not prioritize adding it back

The takeaway here is our e2e config story is legacy, fragile, and not ready for change. But rather than fixing it in the existing AGW, I think we may be better served by deferring the bettereng solution to the golang agw for now cc @markjen @electronjoe

**Comment by mstre123** [comment] 2021-09-20 22:19
https://github.com/magma/magma/pull/9173 fix

**Closed as completed** 2021-10-06 16:17 UTC
Labels: type: bug
