### ISSUE TITLE
Attach Procedure Failure due to duplicate enb_ue_s1ap_ids 

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#6414] opened 2021-04-27 19:41 UTC
### Your Environment

- **Version:** 1.5
- **Affected Component:** AGW
- **Affected Subcomponent:** MME
- **Deployment Environment:**  AWS (orc8r) bare-metal (AGW)

### Describe the Issue

During scale testing, we observed on multiple gateways that after 5+ hrs we see attach procedure timeout on the UEs. In the mme logs we see 

```
INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0102    Received S1AP INITIAL_UE_MESSAGE ENB_UE_S1AP_ID 0xCB9B53 assoc-id:2 
INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0115    New Initial UE message received with eNB UE S1AP ID: 0xCB9B53 assoc-id :2 
ERROR S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0252    Initial UE Message- Duplicate ENB_UE_S1AP_ID. Ignoring the message, eNB UE S1AP 

```

**To Reproduce**
1. Run attach/detach tests over a longer duration of time; approx 4+ hrs.

mme logs and syslog attached. 

Problem starts to happen after 18:00 in the log. 
![image](https://user-images.githubusercontent.com/38921899/116300606-ef122500-a753-11eb-969b-0f3f8dd93642.png)

[vagw4_mme_trunc.log.zip](https://github.com/magma/magma/files/6387188/vagw4_mme_trunc.log.zip)
[vagw4_syslog_trunc.zip](https://github.com/magma/magma/files/6387194/vagw4_syslog_trunc.zip)

**Comment by ulaskozat** [comment] 2021-04-27 19:56
This is also there for v1.4.

**Comment by ardzoht** [comment] 2021-07-12 17:28
Closing this since it hasn't reproduced once fix on https://github.com/magma/magma/pull/6800 merged, we can reopen if needed

**Closed as completed by ardzoht** 2021-07-12 17:28 UTC
Labels: type: bug
