### ISSUE TITLE
[subscriberdb] Subscribers not showing up after IMSI deconcealing fix (12567)

### ISSUE THREAD

**Issue by vroon2703** [magma/magma#13036] opened 2022-06-20 22:58 UTC
### Your Environment

- **Version:** master
- **Affected Component:** Access Gateway 
- **Affected Subcomponent:** SubscriberDB
- **Deployment Environment:** Vagrant (AGW)

### Describe the Issue

Possibly related commit: https://github.com/magma/magma/pull/12567

After adding a new subscriber via swagger and running subscriber_cli.py list on the gateway VM returns no subscribers. The debug logs indicate the following error: 

ERROR:root:Fetch suci profiles error! [StatusCode.UNKNOWN] handler panic: runtime error: invalid memory address or nil pointer dereference; 

**To Reproduce**
1. Add a subscriber using Swagger (/lte/{network_id}/subscribers) 
2. On the AGW VM, run `subscriber_cli.py list ` 
3. Observe that the added subscriber does not show up. 
4. Run `sudo journalctl -u  magma@subscriberdb` to see the logs

**Expected behavior**
IMSI of the added subscriber shows up. 

**Screenshots**
GET shows that IMSI has been added. 
<img width="1234" alt="Screen Shot 2022-06-20 at 3 52 36 PM" src="https://user-images.githubusercontent.com/105877840/174686424-efb7031b-8b42-46da-9a31-c7c8bbea7352.png">

`subscriber_cli.py list `  does not print any IMSIs
<img width="475" alt="Screen Shot 2022-06-20 at 3 53 18 PM" src="https://user-images.githubusercontent.com/105877840/174686466-fd63ffab-fa69-4c0c-a284-a971d79f3008.png">

Error message shows up:  fetch suci profiles error!

<img width="1637" alt="Screen Shot 2022-06-20 at 3 57 17 PM 1" src="https://user-images.githubusercontent.com/105877840/174686781-4a9770af-ef47-43b3-bc69-e8fcd019dfa1.png">

**Comment by Akshayp77** [comment] 2022-06-23 09:17
On latest master code base, we have added a new subscriber(IMSI001010000000004) through swagger API and it is getting reflected only after 5 minutes in the subscriberdb. Please refer attached log file and snapshots.
[sys-subdb.log](https://github.com/magma/magma/files/8965824/sys-subdb.log)

![Screenshot (27)](https://user-images.githubusercontent.com/87304387/175263415-84089b08-244c-4fd2-9294-723926d9ada0.png)
![Screenshot (28)](https://user-images.githubusercontent.com/87304387/175263428-4622fdff-fa13-4ed6-a84c-0bd3f33c60d7.png)
![Screenshot (29)](https://user-images.githubusercontent.com/87304387/175263433-1beb35cc-a193-410c-8da7-c4fd3e6b60f9.png)
![Screenshot (30)](https://user-images.githubusercontent.com/87304387/175263439-cb3c2ea6-ca09-4dd7-b5de-dc5ec63d5364.png)

**Comment by sebathomas** [comment] 2022-06-23 13:04
I see the error on my laptop as well and I'm not sure it's caused by the changes from #12567. It seems like it's somewhere in the orc8r, and the PR mostly touched agw code.

It might be the change of the proto file though.

**Comment by panyogesh** [comment] 2022-07-18 06:45
Closing the ticket with reference to #13081

**Closed as completed by panyogesh** 2022-07-18 06:45 UTC
Labels: type: bug, product: 5g sa
