### ISSUE TITLE
scale test: SA_TC50a_Scale_Test_Suci is failing when tried at the rate of 1ue/sec.

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#10006] opened 2021-11-01 17:52 UTC
### Your Environment

Version:1.7.0-1635757065-ea9b8813
Affected Component: Access Gateway 
Affected Subcomponent: AGW service
Deployment Environment: Vagrant (AGW)

### Describe the Issue
 SA_TC50a_Scale_Test_Suci is failing when tried at the rate of 1ue/sec.

### To Reproduce
1. In TVM-GUI go to testcase SA_TC50a_Scale_Test_Suci is failing  
2. Execute testcase by increasing the number of UEs step by step(100,200,....)

### Error Noticed:
Observed that More registration request happening than expected. 

### Expected behavior
All UEs should be served.
Please find the logs and pcaps below 

[https://app.zenhub.com/files/170803235/f0bb2de3-8a09-4686-8022-bf72cf997d35/download](https://app.zenhub.com/files/170803235/f0bb2de3-8a09-4686-8022-bf72cf997d35/download)
[https://app.zenhub.com/files/170803235/8c43b9e2-6574-455c-b983-e4b068ef7b44/download](https://app.zenhub.com/files/170803235/8c43b9e2-6574-455c-b983-e4b068ef7b44/download)
![image.png](https://images.zenhubusercontent.com/60ff6822051e9582447f32aa/8cee0713-e707-4ba6-8665-73f01839d8ea)

**Comment by Kaleem-Wavelabs** [comment] 2021-12-06 09:45
Verified this TC on TeraVM with Neelima, it is passing as expected. Please re-verify and close the issue with the required logs attached.

**Comment by arun-magma** [comment] 2021-12-15 06:57
@NeelimaKalpana : In Today's Regression 12/14 we found TC1a fails with SUCI Reg with 50 loop count fails because of Reg Req (51) & Accept(50) counts.

Enclosed the traces
[https://app.zenhub.com/files/170803235/fda23e45-410e-4084-bb83-ffdf1ba465b4/download](https://app.zenhub.com/files/170803235/fda23e45-410e-4084-bb83-ffdf1ba465b4/download)
[https://app.zenhub.com/files/170803235/53e1320a-a43c-4e08-903c-efde049b3fa1/download](https://app.zenhub.com/files/170803235/53e1320a-a43c-4e08-903c-efde049b3fa1/download)

**Comment by NeelimaKalpana** [comment] 2021-12-15 10:11
Hi Arun , 

Noticed the problem. I will raise a bug on this after my analysis. I will Update further details on this.

**Comment by Kaleem-Wavelabs** [comment] 2021-12-29 10:20
@NeelimaKalpana @rupa455wavelabs can you update the results and process.

**Comment by rupa455wavelabs** [comment] 2022-01-21 04:08
closing the issue, as we verified it and updated the results in this zenhub issue #11022

**Closed as completed by rupa455wavelabs** 2022-01-21 04:08 UTC
Labels: type: bug, product: 5g sa
