### ISSUE TITLE
[4G AGW] [4G Orchestrator ]  AGW Attach reject message (ESM failure) & PDN Connectivity Reject.

### ISSUE THREAD

**Issue by Chandrashrathore** [magma/magma#10988] opened 2021-12-23 11:53 UTC
Version: :AGW : 1.6.1-1636529012-5d886707 
Affected Component : Orchestrator, Access Gateway
Affected Subcomponent : AGW
Deployment Environment : AWS (orc8r), bare-metal (AGW)

In 4G end to end call flow I'm facing one issue in LTE mode only Attach reject message (ESM failure) & PDN Connectivity Reject.( Request Rejected by Serving GW or PDN GW). 
As seen in the MME log lte/gateway/c/core/oai/tasks/sgw/pgw_pco.c : 0445 this line is getting trigger and after reviewing the code this packet (MS support of network Requested Bearer control Indicator 0*0005) is not supported also I am not configure this packet it is send by UE by default. 

In Orchestrator when we do the changes in JSON Config setting for Disable  gx_gy_relay_enabled, hss_relay_enabled it is happing their  but in AGW the changes is not reflected then we do forcefully changes done in AGW 
(  /var/opt/magma/configs/gateway.mconfig ).

For  your reference attaching all the working and non working logs.[https://app.zenhub.com/files/170803235/60d040f1-5dec-4045-8b84-0d281a0061f9/download](https://app.zenhub.com/files/170803235/60d040f1-5dec-4045-8b84-0d281a0061f9/download)

**Comment by Chandrashrathore** [comment] 2021-12-29 05:45
Hi All plz find the working logs.[https://app.zenhub.com/files/170803235/112d98fe-bd1c-4ef7-9cb4-7db3dc75cb6f/download](https://app.zenhub.com/files/170803235/112d98fe-bd1c-4ef7-9cb4-7db3dc75cb6f/download)

**Comment by panyogesh** [comment] 2021-12-29 05:59
Can you please share : mme.yml spgw.yml

**Comment by Chandrashrathore** [comment] 2021-12-29 06:51
Hi Yogesh kindly find the attachment of  mme.yml and  spgw.yml file.

[https://app.zenhub.com/files/170803235/9c5a7676-43bd-44d8-8d3d-0cdda5fecb44/download](https://app.zenhub.com/files/170803235/9c5a7676-43bd-44d8-8d3d-0cdda5fecb44/download)

**Comment by Chandrashrathore** [comment] 2021-12-29 11:30
Hi Yogesh kindly find the attachment of Sessiond log file.

[https://app.zenhub.com/files/170803235/43be418f-68f7-43a5-8809-78b4bfbf5138/download](https://app.zenhub.com/files/170803235/43be418f-68f7-43a5-8809-78b4bfbf5138/download)

**Comment by panyogesh** [comment] 2021-12-29 18:21
Seems to be that FEG is not completely disabled                                                                                             
"Dec 29 03:21:47 fb-appliance1 sessiond[194476]: I1229 03:21:45.679318 194476 sessiond_main.cpp:71] Using proxied SessionD controller"

Is their a way to disable FEG at system level.

Also can you please share the output of : "magma_get_config.py -s sessiond".

**Comment by Chandrashrathore** [comment] 2021-12-30 07:34
Hi Yogesh kindly find the attachment of  magma_get_config.py -s sessiond file

[https://app.zenhub.com/files/170803235/fb6b425b-d63e-4ecb-a878-2f1575be2a11/download](https://app.zenhub.com/files/170803235/fb6b425b-d63e-4ecb-a878-2f1575be2a11/download)

**Comment by panyogesh** [comment] 2021-12-30 09:06
As we can see "gxGyRelayEnabled True" this is set to true... Hence sessiond is trying to open a FEG connection which failed and most likely failing in session creation.
One option is to disable this either from orc8r or swagger to disable it

**Comment by Chandhu-Wavelabs** [comment] 2022-01-03 11:45
ZH task : 11041 is the root cause, will be tracked with that task and closing this one.

**Closed as completed by Chandhu-Wavelabs** 2022-01-03 11:45 UTC
Labels: type: bug
