### ISSUE TITLE
MME doesn't start up after reboot in stateless mode

### ISSUE THREAD

**Issue by edaspb** [magma/magma#1979] opened 2020-07-17 21:38 UTC
### Your Environment

- Version: Magma 1.1.0-1594138895-23c486fc
- Affected Component: Access Gateway
- Affected Subcomponent: magma@mme.service,  magma@state.service
- Deployment Environment: bare-metal (AGW)

### Describe the Issue

MME service core dumped after reboot AGW in stateless mode.
Nothing appears in logs except:
`magma systemd[1]: magma@mme.service: Main process exited, code=dumped, status=11/SEGV`
`magma systemd[1]: magma@mme.service: Unit entered failed state.`
`magma systemd[1]: magma@mme.service: Failed with result 'core-dump'.`

Also in a magma@state service many lines like:

`WARNING:root:Failed to replicate state for (S1AP,IMSI710700000000010): No Serde found for type S1AP`

To Reproduce
1. Apply stateless mode on AGW following this instruction https://github.com/facebookincubator/magma/blob/master/docs/readmes/lte/s1ap_tests.md
2. In /etc/magma/sessiond.yml support_stateless: true
3. Connect UE, check redis store data from services
4. Reboot AGW server.

**Comment by ardzoht** [comment] 2020-07-25 00:37
Hi @edaspb, it would be great if you can please share your `/var/log/mme.log`?

**Comment by edaspb** [comment] 2020-07-27 16:06
Hi @ardzoht! Sure, here is little bit more info:

**1**. Initial state. Magma has been configured as described in my first message. Stateless mode is activated.
Redis DB:
`127.0.0.1:6380> KEYS *`
` 1) "sessiond:sessions"`
` 2) "mobilityd:ip_states:IPState.RESERVED"`
` 3) "pipelined:rule_names"`
 `4) "IMSI710700000000010:SPGW"`
 `5) "IMSI710700000000010:MME"`
 `6) "mme_nas_state"`
` 7) "IMSI710700000000004:directory_record"`
` 8) "spgw_state"`
 `9) "IMSI710700000000010.internet:mobilityd_ipdesc_record"`
`10) "pipelined:rule_versions"`
`11) "mobilityd:assigned_ip_blocks"`
`12) "IMSI710700000000010:directory_record"`
`13) "mobilityd:ip_states:IPState.FREE"`
`14) "s1ap_imsi_map"`
`15) "pipelined:rule_ids"`
`16) "mme:systemd_status"`
`17) "IMSI710700000000010:S1AP"`
`18) "IMSI714030013809526:directory_record"`
`19) "s1ap_state"`
`20) "mobilityd:ip_states:IPState.ALLOCATED"`

**2**. UE regular attachment. There is long log in attachment in case it can help.
[mme_UE_attach.log](https://github.com/magma/magma/files/4983012/mme_UE_attach.log)
Redis DB:

`127.0.0.1:6380> KEYS *`
` 1) "sessiond:sessions"`
` 2) "mobilityd:ip_states:IPState.RESERVED"`
` 3) "pipelined:rule_names"`
 `4) "IMSI710700000000010:SPGW"`
` 5) "IMSI710700000000010:MME"`
` 6) "mme_nas_state"`
` 7) "IMSI710700000000004:directory_record"`
` 8) "spgw_state"`
 `9) "IMSI710700000000010.internet:mobilityd_ipdesc_record"`
`10) "pipelined:rule_versions"`
`11) "mobilityd:assigned_ip_blocks"`
`12) "IMSI710700000000010:directory_record"`
`13) "mobilityd:ip_states:IPState.FREE"`
`14) "s1ap_imsi_map"`
`15) "pipelined:rule_ids"`
`16) "mme:systemd_status"`
`17) "IMSI710700000000010:S1AP"`
`18) "IMSI714030013809526:directory_record"`
`19) "s1ap_state"`
`20) "mobilityd:ip_states:IPState.ALLOCATED"`

**3**. Soft reboot magma server (command 'reboot')

**4**. magma@mme.service crashes on start

mme.log:

`000151 Mon Jul 27 11:46:31 2020 7F82338E1600 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0808    Done reading MME statistics from data store`
`000152 Mon Jul 27 11:46:31 2020 7F82338E1600 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0815    Hashtable MME UE ID => IMSI`
`000153 Mon Jul 27 11:46:31 2020 7F82338E1600 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0819    Hashtable TEID 11 => MME UE ID`
`000154 Mon Jul 27 11:46:31 2020 7F82338E1600 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0823    Hashtable ENB UE S1AP ID => MME UE ID`

Also with `journalctl -u magma@magmad -f` command i see:

`Jul 27 11:50:24 magma mme[3880]: [/home/vagrant/magma/orc8r/gateway/c/common/config/ServiceConfigLoader.cpp:30] Override file not found for service redis`
`Jul 27 11:52:40 magma magmad[3586]: ERROR:root:Cant get RPC channel to redis`

**5**. flushall redis keys and restart magma's services fix the issue.

**Comment by ardzoht** [comment] 2020-08-03 18:34
Thanks for the detailed explanation, I do not see the attachment for the full `mme.log` (just the UE attach one) could you please add it so I can take a look? Thanks!

**Comment by edaspb** [comment] 2020-08-06 16:36
Hi @ardzoht. I double checked there is nothing else in the log after reboot, except
`000150 Thu Aug  6 12:29:29 2020 7FDA2D1C37C0 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0760    Done reading MME statistics from data store`
`000151 Thu Aug  6 12:29:29 2020 7FDA2D1C37C0 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0767    Hashtable MME UE ID => IMSI`
`000152 Thu Aug  6 12:29:29 2020 7FDA2D1C37C0 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0771    Hashtable TEID 11 => MME UE ID`
`000153 Thu Aug  6 12:29:29 2020 7FDA2D1C37C0 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0775    Hashtable ENB UE S1AP ID => MME UE ID`

Before reboot there is just a messages related to UE connection as in my second message.


BTW I can confirm similar behavior with newer 1.1.0-1596007123-a1880d15 version.

**Comment by edaspb** [comment] 2020-08-06 16:57
UPD.
Debug log:

`000150 Thu Aug  6 12:54:44 2020 7FA2084637C0 DEBUG UTIL   tasks/service303/service303_task:0164    Initializing Service303 task interface`
`000151 Thu Aug  6 12:54:44 2020 7FA2084637C0 DEBUG UTIL   tasks/service303/service303_task:0182    Initializing Service303 task interface: DONE`
`000152 Thu Aug  6 12:54:44 2020 7FA2084637C0 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0760    Done reading MME statistics from data store`
`000153 Thu Aug  6 12:54:44 2020 7FA2084637C0 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0767    Hashtable MME UE ID => IMSI`
`000154 Thu Aug  6 12:54:44 2020 7FA2084637C0 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0771    Hashtable TEID 11 => MME UE ID`
`000155 Thu Aug  6 12:54:44 2020 7FA2084637C0 INFO  MME-AP tasks/mme_app/mme_app_state_conv:0775    Hashtable ENB UE S1AP ID => MME UE ID`
`000156 Thu Aug  6 12:54:44 2020 7FA2084637C0 DEBUG MME-AP tasks/mme_app/mme_app_state_conv:0173    mcc-1: 7 mcc-2: 1 mcc-3: 0 mnc-1: 7 mnc-2: 0 mnc-3: f mme_group_id: 1 mme_code: 1 m_tmsi: 3ac00 `
`000157 Thu Aug  6 12:54:44 2020 7FA2084637C0 DEBUG MME-AP tasks/mme_app/mme_app_state_mana:0213    Reading UE state from db for IMSI710700000000004:MME`
`000158 Thu Aug  6 12:54:44 2020 7FA2084637C0 DEBUG NAS-ES tasks/nas/nas_state_converter.cp:0273    Reading esm context from proto`
`000159 Thu Aug  6 12:54:44 2020 7FA2084637C0 DEBUG NAS-ES tasks/nas/nas_state_converter.cp:0235    Reading esm proc data from proto`
`000160 Thu Aug  6 12:54:44 2020 7FA2084637C0 DEBUG MME-AP tasks/nas/nas_state_converter.cp:0096    State PLMN 000.000from proto`
`000161 Thu Aug  6 12:54:44 2020 7FA2084637C0 DEBUG MME-AP tasks/nas/nas_state_converter.cp:0096    State PLMN 710.70 from proto`
`000162 Thu Aug  6 12:54:44 2020 7FA2084637C0 DEBUG MME-AP tasks/mme_app/mme_app_state_conv:0498    Reading PDN context at index 0`

**Comment by ssanadhya** [comment] 2020-08-13 19:14
@edaspb thanks for sharing the details on this issue. Looking through the MME error, it looks like the Redis service did not come up after the AGW rebooted. Let me reproduce this issue locally and get back to you.

**Comment by ssanadhya** [comment] 2020-11-21 06:12
@edaspb, testing with the latest v1.3 branch as well as master, I see that MME comes back up after rebooting in stateless mode. Closing this issue for now, please re-open it if it recurs.

**Closed as completed by ssanadhya** 2020-11-21 06:12 UTC
Labels: component: agw
