### ISSUE TITLE
scale test:SA_TC50b_Scale_Test_Guti is failing when tried at the rate of 1UE/Sec.

### ISSUE THREAD

**Issue by shanjanaWL** [magma/magma#10056] opened 2021-11-03 07:50 UTC
### Your Environment

Version:1.7.0-1635820828-8d09392e
Affected Component: Access Gateway, 
Affected Subcomponent: AGW service
Deployment Environment: Vagrant (AGW)

### Describe the Issue
SA_TC50b_Scale_Test_Guti is failing when tried at the rate of 1UE/Sec.

**To Reproduce**
1. In TVM-GUI go to testcase SA_TC50a_Scale_Test_Guti.
2. Execute testcase by increasing the number of UEs step by step(100,200,....)

Error Noticed:
Observed that More registration request happening than expected.

**Expected behavior**
All UEs should be served.
Please find the logs and pcaps below.
 [https://app.zenhub.com/files/170803235/5027cb49-180f-4a27-82e0-dedc2428aaac/download](https://app.zenhub.com/files/170803235/5027cb49-180f-4a27-82e0-dedc2428aaac/download)
[https://app.zenhub.com/files/170803235/d7b0b7e0-9641-44b7-a2a6-2f914e2a8d76/download](https://app.zenhub.com/files/170803235/d7b0b7e0-9641-44b7-a2a6-2f914e2a8d76/download)

**Comment by Kaleem-Wavelabs** [comment] 2021-12-06 09:47
Verified this TC on TeraVM with Neelima, it is passing as expected. Please re-verify and close the issue with the required logs attached. If the issue is seen again latest, please revert back with the logs.

**Comment by Kaleem-Wavelabs** [comment] 2021-12-29 10:28
@NeelimaKalpana Can you update on this TC verification to process.

**Comment by rupa455wavelabs** [comment] 2022-01-21 04:23
validated and updated the results in zenhub issue #11023, hence closing this issue.

**Closed as completed by rupa455wavelabs** 2022-01-21 04:23 UTC
Labels: type: bug, product: 5g sa
