### ISSUE TITLE
NMS in dev env: Unable to communicate with magma controller: Not Found

### ISSUE THREAD

**Issue by crbertoldo** [magma/magma#1887] opened 2020-06-29 20:33 UTC
Hello,

After successfully building the Orchestrator according to the [Quick Start Guide](https://facebookincubator.github.io/magma/docs/basics/quick_start_guide), running it (without Grafana) and then setting up the NMS UI, I could connect to the https://magma-test.localhost, but perform nothing due to the following error: "Unable to communicate with magma controller: Not Found".

Running **docker ps** shows no port for the _orc8r_controller_ container. After  running **docker logs orc8r_controller_1**, I could see:

```
fbinternal stderr | envdir: fatal: unable to run /var/opt/magma/bin/fbinternal: file does not exist
feg_relay stderr | envdir: fatal: unable to run /var/opt/magma/bin/feg_relay: file does not exist
analytics stderr | envdir: fatal: unable to run /var/opt/magma/bin/analytics: file does not exist
vpnservice stderr | envdir: fatal: unable to run /var/opt/magma/bin/vpnservice: file does not exist
download stderr | envdir: fatal: unable to run /var/opt/magma/bin/download: file does not exist
health stderr | envdir: fatal: unable to run /var/opt/magma/bin/health: file does not exist
testcontroller stderr | envdir: fatal: unable to run /var/opt/magma/bin/testcontroller: file does not exist
```

P.S.: Thru https://master.localhost/ I cannot enable the magma-test organization to access all networks. The WebUI shows it was enabled, but after refreshing, the checkbox keeps unchecked. I don't know if it's a related issue.

**Comment by karthiksubraveti** [comment] 2020-06-30 13:42
Hey @crbertoldo , Thanks for reporting this issue. I'll take a look at this and update this thread.

**Comment by karthiksubraveti** [comment] 2020-07-01 01:48
@crbertoldo  Can you provide more info here. These services might not be necessary for running orc8r. Can you attach the logs for magmalte and orc8r containers. Also can you dump the environment variables within the magmalte container and attach that info as well. Thanks.

**Comment by crbertoldo** [comment] 2020-07-01 21:58
@karthiksubraveti, thanks a lot.

[magma_logs.zip](https://github.com/facebookincubator/magma/files/4860273/magma_logs.zip)

From container **orc8r_proxy_1** we can see that CONTROLLER_HOSTNAME env var cannot be found. Maybe no env var is being taken into account even declared in orc8r/cloud/docker/docker-compose.yml. I am trying to figure out why.

From orc8r/cloud/docker/, both nginx/generate_nginx_configs.py and proxy/run_nghttpx.pyy try to get CONTROLLER_HOSTNAME from os.env (as well 'backend' and 'resolver'). 

P.S.: I didn't build (build.py -a) as root.

**Comment by karthiksubraveti** [comment] 2020-07-06 18:37
Hey @crbertoldo, What's the environment file in your magmalte folder. Did you set up values for 
ksubraveti@ksubraveti-mbp magmalte % cat .env
#API_HOST=<>
#API_CERT_FILENAME=<>
#API_PRIVATE_KEY_FILENAME=<>

Also looks like we have orc8r_proxy is removed and we have moved onto nginx proxy. 
https://github.com/facebookincubator/magma/commit/af33a2261b9393f8ec97b1f35a0341b2f741290e
You might want to update your local tree and rebuild and restart all the orc8r and NMS containers. 

Also can you let us know your git commit so that we can locally try to reproduce and check if something is broken.

**Comment by karthiksubraveti** [comment] 2020-07-17 18:59
@crbertoldo  can you close this issue if doing this fixed your issue. Thanks.

**Comment by crbertoldo** [comment] 2020-07-21 18:19
@karthiksubraveti, I saw that magma/nms/app/fbcnms-projects/magmalte/ was pushed to master 5 days ago. When I tried it was not available yet. I'm confused now. Please should I build it (docker-compose build magmalte
)? Not through the magma/orc8r/cloud/docker/build.py according to the docs?

**Comment by karthiksubraveti** [comment] 2020-07-21 18:53
magma/orc8r/cloud/docker/build.py is for building the orc8r, docker-compose build magmalte is for building the NMS. Yes. You should rebuild NMS docker container.
https://facebookincubator.github.io/magma/docs/orc8r/deploy_build - path mentioned here is little old, symphony directory is renamed to nms.

**Comment by karthiksubraveti** [comment] 2020-07-23 17:30
@crbertoldo I'm closing this issue for now. We can reopen this in case if you are running into this issue of not being able to communicate with controller, else you can open a new case. Thanks.

**Closed as completed by karthiksubraveti** 2020-07-23 17:30 UTC
