### ISSUE TITLE
Mme is unable to establish S1 session with S1APtester(causeType[4] causeValue[5])

### ISSUE THREAD

**Issue by jayshankarnair** [magma/magma#7515] opened 2021-06-12 09:48 UTC
Ubuntu 18.04
**Version:latest
**Affected Component:Mme
**Affected Subcomponent:S1aptest
**Deployment Environment:Virtual box guest OS debian
Describe the Issue
When i run the script ./testCntrlr -f testCaseList_1.txt from S1APtester , there is failure in S1setup phase. The magma mme is able to receive SCTP messages. The error causeType[4], causeValue[5] is returned. I am testing against magma AGW. What does causeValue[4] signify. I didn't find the value in 3GPP document.

oot@magma-test:/home/vagrant/extra/S1APTester/TestCntlrStub/bin# ./testCntrlr -f testCaseList_1.txt
[Stub] Initialising stack manager
tag: AUTH_TYPE tagVal: MILENAGE
[Stub] Entering trf_test_init()
[Stub] Creating message queu
[Stub] Sending UE App config
[Stub] ../src/ts_utls.c:TC_API():460: Message Sent
[Stub] ../src/ts_utls.c:TC_msg_recv():234: Entering
[Stub] TC_msg_recv(): msgid=2

[Stub] Received (msgptr.msgType=2), expected (msgid=2)

[Stub] Received a message of type = 2

[Stub] UE APP Config Completed
[Stub] Entering tsReadImsiAndSendUeConfig()
[Stub] Reading imsi file for ueId: 1
[Stub] ueId :1 temp 2 0 8 1 1 1 2 3 4 5 6 7 8 9 0 temp len :14::
[Stub] ueId :1 IMSI imsi len :15::

[STUB]: Sending Ue Config.
[Stub] ../src/ts_utls.c:TC_API():460: Message Sent
[Stub] ../src/ts_utls.c:TC_msg_recv():234: Entering
[Stub] TC_msg_recv(): msgid=4

[Stub] Received (msgptr.msgType=4), expected (msgid=4)

[Stub] Received a message of type = 4

[Stub] UE 1 Config Completed

[Stub]: Sending eNodeB Config
[Stub] ../src/ts_utls.c:TC_msg_recv():234: Entering
[Stub] TC_msg_recv(): msgid=34

**************TPT open server 0

Server Socket FD =[12][Stub] ../src/ts_utls.c:TC_API():460: Message Sent

[Stub] Received (msgptr.msgType=34), expected (msgid=34)

[Stub] Received a message of type = 34

[Stub] Received Enodeb Config Confirm from TFW

[Stub] eNodeB configured successfully

[Stub]: eNb Config Completed

[Stub]: Sending S1 SETUP Request
[Stub] ../src/ts_utls.c:TC_msg_recv():234: Entering
[Stub] TC_msg_recv(): msgid=38

************* Testing *Time elapsed(in usec): for timer expiry :12933 usec
[Stub] ../src/ts_utls.c:TC_API():460: Message Sent

[Stub] Received (msgptr.msgType=38), expected (msgid=38)

[Stub] Received a message of type = 38

[Stub] Received S1-SETUP Response from TFW

[Stub] S1-SETUP failed, causeType[4], causeValue[5]

[Stub] Received time to wait-IE with Value[4]

[Stub]: S1 SETUP Processing failed
[Stub] Performing step by step ATTACH(IMSI) procedure
[Stub] ueId(1)
[Stub] Entering tsStepByStepAttachWithImsi(), ueId(1)

[Stub] Sending Attach Request, ueId(1)
[Stub] ../src/ts_utls.c:TC_msg_recv():234: Entering
[Stub] TC_msg_recv(): msgid=7

**Comment by ulaskozat** [comment] 2021-06-13 00:34
@jayshankarnair is there a reason why you don't use suggested testing infra for developers? Please check out mme logs (/var/logs/mme.log and /var/logs/syslog) and pcaps to get more context about the issue . But most likely reason is that you have not configured eNB properly. The specific causeValue:
`build/c/core/oai/tasks/s1ap/r15/S1ap_CauseMisc.h:	S1ap_CauseMisc_unknown_PLMN	= 5`

Also issues should be reserved for clearly identified bugs or feature requests. Please raise this type of questions in github discussions and communicate the discussion on appropriate slack channels. I am closing the issue.

**Closed as completed by ulaskozat** 2021-06-13 00:34 UTC
Labels: type: bug

**Comment by jayshankarnair** [comment] 2021-06-13 05:34
@ulaskozat  Thanks for the reply.  I was not sure about whether it was bug or query.  With valid value in PLMN the S1 test passes further. At the end the magma(mme) returns a different msgType(23) from expected msgType(7).
[Stub]: eNb Config Completed

[Stub]: Sending S1 SETUP Request
[Stub] ../src/ts_utls.c:TC_msg_recv():234: Entering
[Stub] TC_msg_recv(): msgid=38
[Stub] ../src/ts_utls.c:TC_API():460: Message Sent

[Stub] Received (msgptr.msgType=38), expected (msgid=38)

[Stub] Received a message of type = 38

[Stub] Received S1-SETUP Response from TFW

[Stub] S1-SETUP successful received from TFWAPP

[Stub]: RECEIVED S1-SETUP RESPONSE FROM TFWAPP
[Stub] Performing step by step ATTACH(IMSI) procedure
[Stub] ueId(1)
[Stub] Entering tsStepByStepAttachWithImsi(), ueId(1)

[Stub] Sending Attach Request, ueId(1)
[Stub] ../src/ts_utls.c:TC_msg_recv():234: Entering
[Stub] TC_msg_recv(): msgid=7
[Stub] ../src/ts_utls.c:TC_API():460: Message Sent

[Stub] Received (msgptr.msgType=23), expected (msgid=7)

[Stub] Received msgptr.mtype = 23
root@magma-test:/home/vagrant/extra/S.

Also internal s1ap  test is failing for certain test. I have posted in the discussion. Hence i used s1aptester.

**Comment by ulaskozat** [comment] 2021-06-13 06:13
@jayshankarnair as I mentioned in my earlier reply, you need to go through the mme log and pcaps to have the full picture. If you are not using the out of the box s1ap integration tests we specify under the magma folder, you need to configure eNBs, subscribers, etc., yourself. If you run MME in debug log level (update /etc/magma/mme.yml file) (you need to restart the magma services for new config to take effect), you can get more context about the call flow on MME side in the mme.log. If you capture and look at the pcaps, you can also see the causes of rejections/failures etc.  For message types, causes, etc., check out `/home/vagrant/s1ap-tester/bin/s1ap_types.py`. You can see there that msgType=23 is attach reject. Most likely you did not add the subscriber information to subscriberdb (which is the local HSS for Magma).

**Comment by jayshankarnair** [comment] 2021-06-13 07:58
@ulaskozat   I am getting subscribers error. Particular IMSI id not present. In /var/opt/magma there are subscriber0.db to  subscriber99. db .There are no records in subscriber. How can i add subscriber from command. Let me know the procedure.

**Comment by jayshankarnair** [comment] 2021-06-13 08:09
@ulaskozat   Logs of subscriberd.
root@magma-dev:/home/vagrant/magma/lte/gateway/python/scripts# journalctl -fu magma@subscriberdb
-- Logs begin at Sun 2021-06-13 01:54:44 UTC. --
Jun 13 06:52:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Socket closed
Jun 13 06:55:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 13 06:56:42 magma-dev subscriberdb[13343]: WARNING:root:Subscriber not found: IMSI208111234567890
Jun 13 06:58:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 13 07:01:07 magma-dev subscriberdb[13343]: WARNING:root:Subscriber not found: IMSI208111234567890
Jun 13 07:01:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 13 07:04:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Broken pipe
Jun 13 07:07:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 13 07:10:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 13 07:13:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 13 07:16:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 13 07:17:11 magma-dev subscriberdb[13343]: WARNING:root:Subscriber not found: IMSI208111234567890
Jun 13 07:19:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 13 07:22:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Socket closed
Jun 13 07:24:19 magma-dev subscriberdb[13343]: WARNING:root:Subscriber not found: IMSI208950000000001
Jun 13 07:25:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 13 07:28:35 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503

**Comment by jayshankarnair** [comment] 2021-06-13 09:53
@ulaskozat Logs for subscribe_cli.py and subscriberd
Jun 13 09:34:36 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Transport closed

Jun 13 09:36:49 magma-dev subscriberdb[13343]: ERROR:root:Auth error for 208950000000001: Subscriber key not valid for IMSI208950000000001
Jun 13 09:37:36 magma-dev subscriberdb[13343]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
^C
root@magma-dev:/home/vagrant/magma/lte/gateway/python/scripts# ./subscriber_cli.py get IMSI208950000000001 
pipeline 127.0.0.1
pipeline port50051
sid {
  id: "208950000000001"
}
gsm {
}
lte {
  state: ACTIVE
}
state {
}

**Comment by ulaskozat** [comment] 2021-06-13 23:11
I explained the configurations that needs to be done here: https://github.com/magma/magma/discussions/7522.

**Comment by jayshankarnair** [comment] 2021-06-14 05:41
@ulaskozat 
Thanks for sharing the config details.I am getting error in subscriberdb. Invalid resync authentication code.

Jun 14 05:33:55 magma-dev subscriberdb[26527]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 14 05:35:22 magma-dev subscriberdb[26527]: INFO:root:Auth success: 001010000000002
Jun 14 05:35:22 magma-dev subscriberdb[26527]: ERROR:root:s6_proxy Auth error for 001010000000002: Invalid resync authentication code
Jun 14 05:36:55 magma-dev subscriberdb[26527]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Received http2 header with status: 503
Jun 14 05:39:55 magma-dev subscriberdb[26527]: ERROR:root:Fetch subscribers error! [StatusCode.UNAVAILABLE] Socket closed

Also i change the OP_KEY and shared key to lte auth key given in #7522 in ueCfg.Do i have change OP_KEY or shared key for lte_auth. 

At the S1aptester end, I am getting Auth Reject.

[Stub] UE Auth Request indication Completed

[Stub] Sending Authentication Response
[Stub] ../src/ts_utls.c:TC_msg_recv():234: Entering
[Stub] TC_msg_recv(): msgid=9
Authentication Failed, Failure cause is 21
[Stub] ../src/ts_utls.c:TC_API():460: Message Sent

[Stub] Received (msgptr.msgType=69), expected (msgid=9)

[Stub] Received msgptr.mtype = 69

**Comment by ulaskozat** [comment] 2021-06-14 06:03
On MME you just need to enter the lte key for the subscriber. OPC is computed from OP. OP is not the same as lte auth key. If you check gateway.mconfig, you can see the default values:
```
    "subscriberdb": {
      "@type": "type.googleapis.com/magma.mconfig.SubscriberDB",
      "logLevel": "INFO",
      "lteAuthOp": "EREREREREREREREREREREQ==",
      "lteAuthAmf": "gAA="
    },
```
Note that lteAuthOp and lteAuthAmf are network level configs, here they are encoded as Base64 (e.g., see https://en.wikipedia.org/wiki/Base64 for details of the encoding).

**Comment by jayshankarnair** [comment] 2021-06-14 06:58
@ulaskozat  I didnt get where i have to maintain the subscriber id or the lteauthkey.   Do i have to add the id key:id in  gateway.mconfig in subscriber section. Do i have to add base64 encodings in lteAuthOp  computed from lteAuthKey. Amf i have not  configured.

**Comment by jayshankarnair** [comment] 2021-06-15 09:14
@ulaskozat . In oai configuration for mme there is no setting of key. Only plmn setting. In mme log there is Info message "PLMN is not configured. Selecting SPGW subscriber". Also in IMSI, the log doesn't print leading 0's. I have attached the log. 

000741 Tue Jun 15 06:22:39 2021 7F3D2A13A700 NOTIC S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0600   [1010000000002]                        Send S1AP DOWNLINK_NAS_TRANSPORT message ue_id = 0x0000003C MME_UE_S1AP_ID = 0x0000003C eNB_UE_S1AP_ID = 0x000001
000742 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0241               EMM-FSM   - Received event COMMON_PROC_REQ (1) in state EMM-DEREGISTERED
000743 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0156                     UE 0x0000003C EMM-FSM   - Status changed: EMM-DEREGISTERED ===> EMM-COMMON-PROCEDURE-INITIATED
000744 Tue Jun 15 06:22:39 2021 7F3D2A13A700 INFO  S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0318                           Received S1AP UPLINK_NAS_TRANSPORT message MME_UE_S1AP_ID 0x0000003C
000745 Tue Jun 15 06:22:39 2021 7F3D2A13A700 INFO  S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0080   [1010000000002]                        Sending NAS Uplink indication to NAS_MME_APP, mme_ue_s1ap_id = (60) 
000746 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS    tasks/nas/nas_proc.c            :0309      Received NAS UPLINK DATA IND from S1AP for ue_id = (60)
000747 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0176            EMMAS-SAP - Received primitive EMMAS_DATA_IND (214)
000748 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0621               EMMAS-SAP - Received AS data transfer indication (ue_id=0x0000003C, delivered=true, length=19)
000749 Tue Jun 15 06:22:39 2021 7F3D2D228700 NOTIC NAS    tasks/nas/emm/sap/emm_as.c      :0408                  Hit 3GPP TS 24_301R10_4_4_4_3__1 : Integrity checking of NAS signalling messages exception in the MME
000750 Tue Jun 15 06:22:39 2021 7F3D2D228700 NOTIC NAS    tasks/nas/emm/sap/emm_as.c      :0411                  Hit 3GPP TS 24_301R10_4_4_4_3__2 : Process NAS signalling message in the MME, even if it fails the integrity check or MAC cannot be verified
000751 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_recv.c    :1010                     EMMAS-SAP - Received Authentication Failure message
000752 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/Authentication.c  :0616                        EMM-PROC  - Authentication failure (ue_id=0x0000003C, cause=21)
000753 Tue Jun 15 06:22:39 2021 7F3D2D228700 NOTIC NAS    tasks/nas/emm/Authentication.c  :0623                        Hit 3GPP TS 24_301R10_5_4_2_4__3 : AUTHENTICATION FAILURE received with EMM cause sync failure, renegociate with HSS.
000754 Tue Jun 15 06:22:39 2021 7F3D2D228700 NOTIC NAS    tasks/nas/emm/Authentication.c  :0634                        Hit 3GPP TS 24_301R10_5_4_2_4__3 : AUTHENTICATION FAILURE received with EMM cause sync failure, renegociate with HSS.
000755 Tue Jun 15 06:22:39 2021 7F3D2D228700 NOTIC NAS    tasks/nas/emm/Authentication.c  :0643

000756 Tue Jun 15 06:22:39 2021 7F3D2D228700 NOTIC NAS    tasks/nas/emm/Authentication.c  :0645                        Hit 3GPP TS 24_301R10_5_4_2_7_e__2 : Re-synchronise with AUTS parameter
000757 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/Authentication.c  :1463                                 Sending Authentication Information Request message to S6A for ue_id =0x0000003C
000758 Tue Jun 15 06:22:39 2021 7F3D29915700 INFO  S6A    common/common_utility_funs.cpp  :0056   [1010000000002] PLMN is not configured. Selecting default mode: SPGW_SUBSCRIBER 
000759 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/nas_proc.c            :0367      Received Authentication Information Answer from S6A for ue_id =0x0000003C
000760 Tue Jun 15 06:22:39 2021 7F3D2D228700 ERROR NAS-EM tasks/nas/nas_proc.c            :0387      INFORMING NAS ABOUT AUTH RESP ERROR CODE
000761 Tue Jun 15 06:22:39 2021 7F3D2D228700 ERROR NAS-EM tasks/nas/nas_proc.c            :0407      Auth info Rsp failure for imsi 1010000000002, experimental_error_code 4001 
000762 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_cn.c      :1138               EMMCN-SAP - Received primitive EMM_CN_AUTHENTICATION_PARAM_FAIL (402)
000763 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0241                              EMM-FSM   - Received event COMMON_PROC_REJ (3) in state EMM-COMMON-PROCEDURE-INITIATED
000764 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_fsm.c     :0156                                 UE 0x0000003C EMM-FSM   - Status changed: EMM-COMMON-PROCEDURE-INITIATED ===> EMM-DEREGISTERED
000765 Tue Jun 15 06:22:39 2021 7F3D2D228700 WARNI NAS-EM tasks/nas/emm/LowerLayer.c      :0472                                 NO Valid Security Context Available
000766 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :0176                                 EMMAS-SAP - Received primitive EMMAS_SECURITY_REJ (204)
000767 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_as.c      :1752                                 EMMAS-SAP - Send AS security reject
000768 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  NAS-EM tasks/nas/emm/sap/emm_send.c    :1428                                 EMMAS-SAP - Send Authentication Reject message
000769 Tue Jun 15 06:22:39 2021 7F3D2D228700 INFO  MME-AP tasks/mme_app/mme_app_itti_messa:0090   [1010000000002]                     Sending UE Context Release Cmd to S1ap for (ue_id = 60)
UE Context Release Cause = (1)
000770 Tue Jun 15 06:22:39 2021 7F3D2A13A700 NOTIC S1AP   tasks/s1ap/s1ap_mme_nas_procedur:0600   [1010000000002]                        Send S1AP DOWNLINK_NAS_TRANSPORT message ue_id = 0x0000003C MME_UE_S1AP_ID = 0x0000003C eNB_UE_S1AP_ID = 0x000001
000771 Tue Jun 15 06:22:39 2021 7F3D2D228700 ERROR NAS-EM tasks/nas/emm/Attach.c          :1235         ATTACH - Authentication procedure failed!
