### ISSUE TITLE
Integrate Information from Community Repository into Documentation

### ISSUE THREAD

**Issue by Neudrino** [magma/magma#13235] opened 2022-07-07 17:28 UTC
## Describe the Issue

The repository https://github.com/magma/community/ holds information, which is largely duplicated in the [Magma main repository](https://github.com/magma/magma/) or in the official documentation in [DocuSaurus](https://docs.magmacore.org/) or [Github Wiki](https://github.com/magma/magma/wiki/).

## Desired target state

For the repository https://github.com/magma/community/ the following measures should be taken:
- Content should be evaluated in comparison to
  - https://docs.magmacore.org/
  - https://github.com/magma/magma/wiki/
  
  and it should
  - be removed, in case it is duplicated or outdated.
  - migrated to the above documentation locations, in case it not present in other documentation.
- Once all content is removed or migrated, the repository should be deleted. :warning: Archiving is than not necessary.

**Comment by maxhbr** [comment] 2022-07-09 07:04
sorry, this is a duplicate of https://github.com/magma/magma/issues/12708

**Closed as completed by maxhbr** 2022-07-09 07:04 UTC
Labels: component: docs, willfix
