### ISSUE TITLE
Error creating new org from master NMS 1.7 release

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [magma/magma#12346] opened 2022-03-30 06:18 UTC
### Your Environment

- **Version:** 1.7
- **Affected Component:** NMS

### Describe the Issue

Getting error creating new org from master NMS.

<img width="1904" alt="Screen Shot 2022-03-30 at 11 08 29 AM" src="https://user-images.githubusercontent.com/14152150/160764088-7859d6ff-cf49-4d10-bf8f-5a77fbe68acc.png">

**Comment by thmsschmitt** [comment] 2022-05-30 06:38
Many things have changed around organisations since 1.7. I just tried it again on master and I can create a new organisation on a fresh install without an issue. @ShubhamTatvamasi I'm closing for now unless you have some more specific steps how this can still be reproduced.

**Closed as completed by thmsschmitt** 2022-05-30 06:38 UTC
Labels: type: bug

**Comment by ShubhamTatvamasi** [comment] 2022-05-30 06:50
This is great @thmsschmitt, thanks for testing it.

**Comment by ivan-freedomfi** [comment] 2022-07-18 16:45
We have faced the same `500` error trying to use `v1.7.0` when creating Network:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/104149278/179543019-3838db9d-efcd-4b92-ab6a-2832f4e8f01d.png">

And the following message in the logs:
```
{"message":"92.253.236.216 - - [11/Jul/2022:12:48:50 +0000] \"GET /master/networks/async HTTP/1.1\" 200 2 \"https://master.nms.my.domain.com/master/organizations/new\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2022-07-11T12:48:50.044Z"}
Error: Invalid value Where {
  attribute: Fn { fn: 'lower', args: [ Col { col: 'name' } ] },
  comparator: '=',
  logic: Fn { fn: 'lower', args: [ 'val' ] } }
    at Object.escape (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/sql-string.js:65:11)
    at PostgresQueryGenerator.escape (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:986:22)
    at PostgresQueryGenerator.whereItemQuery (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2282:102)
    at forEach (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25)
    at Array.forEach (<anonymous>)
    at PostgresQueryGenerator.whereItemsQuery (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)
    at PostgresQueryGenerator.getWhereConditions (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2583:19)
    at PostgresQueryGenerator.selectQuery (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1315:28)
    at QueryInterface.select (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/query-interface.js:1127:27)
    at Promise.try.then.then.then (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/model.js:1759:34)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
{"message":"92.253.236.216 - - [11/Jul/2022:12:48:59 +0000] \"POST /master/organization/async HTTP/1.1\" 500 148 \"https://master.nms.my.domain.com/master/organizations/new\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2022-07-11T12:48:59.281Z"}
Error: Invalid value Where {
  attribute: Fn { fn: 'lower', args: [ Col { col: 'name' } ] },
  comparator: '=',
  logic: Fn { fn: 'lower', args: [ 'val' ] } }
    at Object.escape (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/sql-string.js:65:11)
    at PostgresQueryGenerator.escape (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:986:22)
    at PostgresQueryGenerator.whereItemQuery (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2282:102)
    at forEach (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25)
    at Array.forEach (<anonymous>)
    at PostgresQueryGenerator.whereItemsQuery (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)
    at PostgresQueryGenerator.getWhereConditions (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2583:19)
    at PostgresQueryGenerator.selectQuery (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1315:28)
    at QueryInterface.select (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/query-interface.js:1127:27)
    at Promise.try.then.then.then (/usr/src/node_modules/@fbcnms/sequelize-models/node_modules/sequelize/lib/model.js:1759:34)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
{"message":"92.253.236.216 - - [11/Jul/2022:12:49:26 +0000] \"POST /master/organization/async HTTP/1.1\" 500 148 \"https://master.nms.my.domain.com/master/organizations/new\" \"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0\"\n","level":"info","label":"express-middleware/appMiddleware.js","timestamp":"2022-07-11T12:49:26.511Z"}
Error: connect ETIMEDOUT 35.161.13.242:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```
