### ISSUE TITLE
Logging into docker registry at magmad_

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#513] opened 2019-08-04 14:16 UTC
How to get the username and password for the docker registry.

**Comment by shoaibbutt50** [comment] 2019-08-05 08:54
When running this command Error is coming
sudo ./install_gateway.sh feg
Logging into docker registry at magmad_
Username: 
Password: 
Error response from daemon: Get https://magmad_/v2/: dial tcp: lookup magmad_: no such host

**Comment by annepak88** [comment] 2019-08-06 04:34
@mpgermano  - not sure if magmad is a FeG issue - if not, please reassign to the right team.

**Comment by shoaibbutt50** [comment] 2019-08-06 04:36
@annepak88 @mpgermano i have made the docker hub account and i am entering my docker hub account user name and password.

**Comment by shoaibbutt50** [comment] 2019-08-06 04:40
After setting the HTTP and HTTPS proxy the below error is coming
Logging into docker registry at magmad_
Username: shoaibbutt50
Password: 
Error response from daemon: Get https://magmad_/v2/: proxyconnect tcp: dial tcp 127.0.0.1:53: connect: connection refused

**Comment by shoaibbutt50** [comment] 2019-08-06 09:24
@mpgermano any update on this how to resolve this issue.

**Comment by mpgermano** [comment] 2019-08-06 16:42
@shoaibbutt50 We do not host our docker images on docker hub. For this, you will have to add the images to your own docker registry and update the `.env` file with the repository name.

**Comment by shoaibbutt50** [comment] 2019-08-06 16:45
@mpgermano any guide or document for this how to add the images to my own docker registry

**Comment by shoaibbutt50** [comment] 2019-08-08 14:49
i added the images to my own docker registry and updated the .env file with the repository name but still error is coming.
Error response from daemon: Get https://shoaibfeg/v2/: dial tcp: lookup shoaibfeg: no such host
What else is required to change or how do i change the Get https://shoaibfeg/v2/:  address?

**Comment by mpgermano** [comment] 2019-08-14 05:26
Closing as this is a duplicate of https://github.com/facebookincubator/magma/issues/537.

**Closed as completed by mpgermano** 2019-08-14 05:26 UTC
