### ISSUE TITLE
[TVM- CI Sanity] cause-91 "DNN Not Supported or Subscribed in the Slice"

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#11523] opened 2022-02-11 06:47 UTC
Issue: cause-91 "DNN Not Supported or Subscribed in the Slice"
Occurrence: Intermittently without any manual changes in Subscriber profiles.

Magma build - 1.7.0-1644522379-11954d35

Scenario:
SUCI Registration
PDU Establishment with DNN: "internet"
PDU Reject with cause-91 "DNN Not Supported or Subscribed in the Slice"

We find in syslogs that mme services complains Mismatch IE length as below, This is happening Intermittently, Fyi with same I.E length & DNN name TCs are passiing with successful PDU establishment.

![Screen Shot 2022-02-10 at 10.35.33 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/ce6ae190-5cf5-4b42-bcfb-303662f0613d)

[3gpp pcaps and Syslog (Issue occurrence TS: 01:43:11)
[https://app.zenhub.com/files/170803235/4807f4da-46ae-43bf-88a0-72998655c318/download](https://app.zenhub.com/files/170803235/4807f4da-46ae-43bf-88a0-72998655c318/download)
[https://app.zenhub.com/files/170803235/1d0384e3-25b1-4dbc-865d-ffbad4a4263e/download](https://app.zenhub.com/files/170803235/1d0384e3-25b1-4dbc-865d-ffbad4a4263e/download)

[3gpp Pcap]
![Screen Shot 2022-02-10 at 10.39.50 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/1e218554-a004-4ff5-a3f6-760457bac506)

![Screen Shot 2022-02-10 at 10.39.34 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/a300d003-a0a3-42d9-a54f-e5aa24ebad2f)

**Comment by panyogesh** [comment] 2022-02-11 12:22
1. Reason for the issue
The issue is coming due to the failure in type check in GRPC 
It seems we are trying to set the max_ul_bit_rate as : 200000000000 (200 Gbps) Whereas in GRPC calls this is only uint32 : 4,29,49,67,296. So while doing the syntax checking this is failing.

2. To Reproduce
This failure can easily be seen when doing the operation
magma@TVM3-SA-regression:~$ subscriber_cli.py get IMSI222456000000101
Error! [StatusCode.UNKNOWN] Exception calling application: Value out of range: 200000000000

AMF fails to get the APN and AMBR information hence the subsequent PDU Session Establishment fails

3. Probable reason
    In subscriberdb.yml  : 
    -> Default Subscription Profile
         default_max_ul_bit_rate: 200000000000 # 2 Gbps
        default_max_dl_bit_rate: 400000000000 # 4 Gbps
	
4. Possible solution
Can we decrease the rate and check it


Line 7279: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]: ERROR:grpc._server:Exception calling application: Value out of range: 200000000000
	Line 7280: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]: Traceback (most recent call last):
	Line 7281: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]:   File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
	Line 7282: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]:     response_or_iterator = behavior(argument, context)
	Line 7283: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/protocols/s6a_proxy_servicer.py", line 118, in UpdateLocation
	Line 7283: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]:   File "/usr/local/lib/python3.8/dist-packages/magma/subscriberdb/protocols/s6a_proxy_servicer.py", line 118, in UpdateLocation
	Line 7284: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]:     ula.total_ambr.max_bandwidth_ul = profile.max_ul_bit_rate
	Line 7285: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/python_message.py", line 713, in field_setter
	Line 7286: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]:     new_value = type_checker.CheckValue(new_value)
	Line 7287: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]:   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/internal/type_checkers.py", line 168, in CheckValue
	Line 7288: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]:     raise ValueError('Value out of range: %d' % proposed_value)
	Line 7289: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]: ValueError: Value out of range: 200000000000
	Line 7293: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]: INFO:root:Successfully fetched all subscriber pages from the cloud!
	Line 7293: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]: INFO:root:Successfully fetched all subscriber pages from the cloud!
	Line 7431: Feb 10 01:43:35 TVM3-SA-regression2 subscriberdb[1190417]: INFO:root:M5GAuthenticationInformation Request:

**Comment by arun-magma** [comment] 2022-02-23 04:48
[2/22] This issue still persists in 5g SA Sanity on [2/21/22, 14:05] Magma build - 1.7.0-1645480370-e3b49ea6

Failed TC: 
SA_TC2_UE_Initiated_PDU_Session_Establishment_with_traffic_test

**Comment by panyogesh** [comment] 2022-02-25 14:29
Arun : Will analyze and come back.

**Comment by NeelimaKalpana** [comment] 2022-03-31 10:24
Hi Arun,

With above configuration we are not seeing any PDU-Reject with cause :91 .
Can we close this issue.

**Comment by panyogesh** [comment] 2022-05-05 11:13
Closing based on previous comments.

**Closed as completed by panyogesh** 2022-05-05 11:13 UTC
Labels: product: 5g sa
