### ISSUE TITLE
[TVM CI Sanity] Rej Reject Illegal UE -  get_subs_auth_info fails

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#11853] opened 2022-03-01 00:48 UTC
Issue Title: [TVM CI Sanity] Rej Reject Illegal UE -  get_subs_auth_info fails

Issue occurrence Build: 
Magma build - 1.7.0-1646079958-9e20c7b9

Scenario: 
- Plain SUCI/IMSI based Registration Request
- Registration Accept is expected after Auth procedure but Received Registration Reject with Illegal UE.

Seems DB operation to Retrieve Auth vectors Failed, below are the pcap, mme & sys logs, Kindly check.

[https://app.zenhub.com/files/170803235/34884326-0135-483c-85b7-eab5a6b4fb39/download](https://app.zenhub.com/files/170803235/34884326-0135-483c-85b7-eab5a6b4fb39/download)

[https://app.zenhub.com/files/170803235/8c4d5cc6-206e-4ddf-8203-67866788afb1/download](https://app.zenhub.com/files/170803235/8c4d5cc6-206e-4ddf-8203-67866788afb1/download)

[https://app.zenhub.com/files/170803235/930ab700-d11f-407b-9bab-34872b5c5cea/download](https://app.zenhub.com/files/170803235/930ab700-d11f-407b-9bab-34872b5c5cea/download)

[pcap]
![Screen Shot 2022-02-28 at 4.31.35 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/536aec8c-496a-4590-90b5-8681b56dd92e)

[mmelog]
![Screen Shot 2022-02-28 at 4.38.55 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/d5088f55-bf05-4866-a10d-d9942e9933ed)

[syslog]
![Screen Shot 2022-02-28 at 4.39.58 PM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/526cd41c-50e2-4127-8af2-c2a8bdf03b64)

**Comment by arun-magma** [comment] 2022-03-01 02:28
This Issue Repeated again in this Build related test
Magma build - 1.7.0-1646093314-e9162f2f

**Comment by panyogesh** [comment] 2022-03-01 14:11
The issue got introduced by a commit #11773. The issue is identified and fixed as part of #11858 which is also merged. Hopefully it should get resolved in todays build. I have done some basic sanity with the change and it looks fine.

**Comment by arun-magma** [comment] 2022-03-08 17:58
Hi @panyogesh : Another instance of Auth procedure failure results in Illegal UE , This time "error= TOO BUSY" found in syslogs, kindly check. Enclosing pcap and logs.

Magma build - 1.7.0-1646749589-878c98df
![Screen Shot 2022-03-08 at 9.50.56 AM.png](https://images.zenhubusercontent.com/5f934b19f9d04269a3f065cd/98a85571-0efd-4c35-8214-dd6a7ef5ef3f)

[https://app.zenhub.com/files/170803235/6ff5c750-7a42-48e3-b129-5fa45e7f0b65/download](https://app.zenhub.com/files/170803235/6ff5c750-7a42-48e3-b129-5fa45e7f0b65/download)

[https://app.zenhub.com/files/170803235/83d45779-44e9-47b7-b82c-b2abd87a192d/download](https://app.zenhub.com/files/170803235/83d45779-44e9-47b7-b82c-b2abd87a192d/download)

[https://app.zenhub.com/files/170803235/0e845325-cc38-47ca-a6be-26672266230c/download](https://app.zenhub.com/files/170803235/0e845325-cc38-47ca-a6be-26672266230c/download)

**Comment by panyogesh** [comment] 2022-05-05 11:14
Not seen issue in new setups. Closing it

**Closed as completed by panyogesh** 2022-05-05 11:14 UTC
Labels: wontfix, product: 5g sa
