### ISSUE TITLE
PDN IP Assigned by DHCP Server doesnt update unless lease time expires

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#5906] opened 2021-04-03 23:02 UTC
### Your Environment

- **Version:**1.3.3-1614917907-371c6462
- **Affected Component:** AGW
- **Affected Subcomponent:** mobilityd, pipelined
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

At one of FreedomFi customers site, dynamic IP Pool assignment is configured where the DHCP Pool assigns IP to the UE.
When the AGW requests DHCP Discovery during default bearer creation procedure, the IP is assigned for a specific lease time period. During this time, if the UE detaches or signaling interrupts, the IP is released by the AGW. However when the same UE Tries to attach again, the AGW instead of initiating new DHCP Discovery, assigns the same old IP. This happens unless the lease timer in the first DHCP discovery expires.

**Screenshots**
![image](https://user-images.githubusercontent.com/77636702/113493548-56aeba80-949d-11eb-9872-1b6bb7384e01.png)

**Additional context**
When around 07:30 the UE got registered to network, Magma AGW made a DHCP Discovery and got this IP 10.1.95.197 which can be seen from the logs below.

```
Apr  3 07:37:35 agw mme[1356]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 314030000001469
Apr  3 07:37:35 agw mobilityd[1287]: INFO:root:GW update: GW IP[3038]: 10.1.95.1
Apr  3 07:37:35 agw mobilityd[1287]: INFO:mobilityd.dhcp.sniff:Record DHCP for: v3038.8a_06_fc_23_b1_bd state: state: OFFER    requested state: DISCOVER mac 8a:06:fc:23:b1:bd ip 10.1.95.197 subnet 10.1.95.197/32 DHCP: 10.1.95.1 router 10.1.95.1 lease time 2021-04-05 07:37:35.741459, renew 2021-04-03 07:37:35.741527 xid 1 vlan 3038
Apr  3 07:37:35 agw mobilityd[1287]: INFO:root:Allocated IPv4 10.1.95.197 for sid IMSI314030000001469 for apn internet
Apr  3 07:37:35 agw sessiond[395]: I0403 07:37:35.917879   395 LocalSessionManagerHandler.cpp:622] Received a LocalCreateSessionRequest for IMSI314030000001469 with APN:internet, default bearer ID:5, PLMN ID:314030, IMSI PLMN ID:314030, User location: 82 13 04 30 00 01 13 04 30 08 1b 00 8e
Apr  3 07:37:35 agw sessiond[395]: I0403 07:37:35.917979   395 LocalSessionManagerHandler.cpp:257] Sending a CreateSessionRequest to fetch policies for IMSI314030000001469-477595
Apr  3 07:37:35 agw policydb[442]: INFO:root:Creating a session for subscriber ID: IMSI314030000001469
Apr  3 07:37:35 agw mobilityd[1287]: INFO:mobilityd.dhcp.sniff:Record DHCP for: v3038.8a_06_fc_23_b1_bd state: state: ACK      requested state: REQUEST  mac 8a:06:fc:23:b1:bd ip 10.1.95.197 subnet 10.1.95.197/32 DHCP: 10.1.95.1 router 10.1.95.1 lease time 2021-04-05 07:37:35.926917, renew 2021-04-04 07:37:35.926974 xid 1 vlan 3038
Apr  3 07:37:35 agw sessiond[395]: I0403 07:37:35.927909   395 LocalSessionManagerHandler.cpp:267] Processing a CreateSessionResponse for IMSI314030000001469-477595
Apr  3 07:37:35 agw sessiond[395]: I0403 07:37:35.928757   395 LocalEnforcer.cpp:775] Activating untracked rule allowlist_sid-IMSI314030000001469-internet
Apr  3 07:37:35 agw sessiond[395]: I0403 07:37:35.928846   395 PipelinedClient.cpp:97] Sending AMBR info for IMSI314030000001469, ip addr=10.1.95.197 , dl=1000000000, ul=1000000000
Apr  3 07:37:35 agw sessiond[395]: I0403 07:37:35.929060   395 PipelinedClient.cpp:97] Sending AMBR info for IMSI314030000001469, ip addr=10.1.95.197 , dl=1000000000, ul=1000000000
```

For any reason due to Switch off/Signaling issue when Context is released, the IP is released also the release is sent to the DHCP Server.

`Apr  3 07:38:08 agw mobilityd[1287]: INFO:root:Released IPv4 10.1.95.197 for sid IMSI314030000001469`

But, When next time the same UE attaches again, AGW doesnt make a new DHCP Discovery until the lease time in previously assigned expires and the AGW assigns the same IP to the UE with hitting the DHCP Server.

```
Apr  3 09:30:15 agw mme[1356]: [INFO] sent itti S6A-LOCATION-UPDATE_ANSWER for IMSI: 314030000001469
Apr  3 09:30:15 agw mobilityd[1287]: INFO:root:Allocated IPv4 10.1.95.197 for sid IMSI314030000001469 for apn internet
Apr  3 09:30:15 agw sessiond[395]: I0403 09:30:15.217692   395 LocalSessionManagerHandler.cpp:622] Received a LocalCreateSessionRequest for IMSI314030000001469 with APN:internet, default bearer ID:5, PLMN ID:314030, IMSI PLMN ID:314030, User location: 82 13 04 30 00 01 13 04 30 08 1b 00 8e
Apr  3 09:30:15 agw sessiond[395]: I0403 09:30:15.217756   395 LocalSessionManagerHandler.cpp:257] Sending a CreateSessionRequest to fetch policies for IMSI314030000001469-257913
Apr  3 09:30:15 agw policydb[442]: INFO:root:Creating a session for subscriber ID: IMSI314030000001469
Apr  3 09:30:15 agw sessiond[395]: I0403 09:30:15.223733   395 LocalSessionManagerHandler.cpp:267] Processing a CreateSessionResponse for IMSI314030000001469-257913
Apr  3 09:30:15 agw sessiond[395]: I0403 09:30:15.223805   395 LocalEnforcer.cpp:775] Activating untracked rule allowlist_sid-IMSI314030000001469-internet
Apr  3 09:30:15 agw sessiond[395]: I0403 09:30:15.223870   395 
PipelinedClient.cpp:97] Sending AMBR info for IMSI314030000001469, ip addr=10.1.95.197 , dl=1000000000, ul=1000000000
Apr  3 09:30:15 agw sessiond[395]: I0403 09:30:15.224074   395 PipelinedClient.cpp:97] Sending AMBR info for IMSI314030000001469, ip addr=10.1.95.197 , dl=1000000000, ul=1000000000
```

[DHCP Issue Logs-PCAPs.zip](https://github.com/magma/magma/files/6253702/DHCP.Issue.Logs-PCAPs.zip)

**Comment by shehzadalee** [comment] 2021-04-03 23:03
@pshelar @jpad-freedomfi

**Comment by jpad-freedomfi** [comment] 2021-04-04 03:39
We are able to reproduce this flow, pcap attached, using the following steps:

1. Configure network for IP Allocation mode = DHCP Broadcast (bridge mode)
2. attach UE (note IP offered to UE)
2. start captures on eth0 (udp port 67) and eth1 (SCTP)
3. reboot UE (initiate reboot or enter airplane mode)
4. observe explicit detach message on S1AP
5. observe DHCP release of IP
6. immediately re-attach UE (power back on UE or exit airplane mode)
7. observe the attach call flow
8. observe that AGW does not issue DHCP discover but still offers old DHCP obtained IP to UE from step 2

This causes upstream router to become out of sync with DHCP issued/used addresses. 

**Expected Behavior**

Anytime after DHCP Release is issued to DHCP server, even if same UE/IMSI re-attaches, a new DHCP Discover/Offer/Request/ACK flow should be initiated. 
[UE_reboot_DHCP_release_but_no_discover_on_reattach.pcapng.zip](https://github.com/magma/magma/files/6253968/UE_reboot_DHCP_release_but_no_discover_on_reattach.pcapng.zip)

**Comment by jpad-freedomfi** [comment] 2021-04-04 03:46
AGW is in ip allocation mode = DHCP_Broadcast

**Comment by pshelar** [comment] 2021-04-05 06:39
@shehzadalee @jpad-freedomfi can you try v1.4? there is fix merged in 1.4 to cleanup after releasing IP: https://github.com/magma/magma/pull/3867

**Comment by jpad-freedomfi** [comment] 2021-04-05 23:27
Thanks @pshelar we have tested that PR and it does fix the observed behavior. 

Can this be back port to 1.3.3?

**Comment by jpad-freedomfi** [comment] 2021-04-12 17:22
per conversation on Monday 4/12 Weekly Developer Meeting for Magma Gateways the referenced PR also fixed the following issue:

Scenario:

- Network ip allocation set to DHCP Broadcast
- UE count observed in NMS for a gateway does not match UE count in mobility_cli.py (NMS has higher number)

After looking at code, we observed that NMS count is based on UEs with a location (sent during attach removed during detach) whereas mobilityd was based on ip address status. 

As the IP release was being performed, mobilityd properly decremented the UE count/entry, but since UE wasn't being deleted, this caused the mismatch. 

Based on our testing, the referenced PR (https://github.com/magma/magma/pull/3867) has fixed that issue as well.

**Closed as completed** 2021-07-15 17:18 UTC
Labels: type: bug, fbcpp
