### ISSUE TITLE
Orchestrator docker setup failing

### ISSUE THREAD

**Issue by shoaibbutt50** [magma/magma#503] opened 2019-08-01 05:46 UTC
When building the Orchestrator using docker error is recevied
~/magma/orc8r/cloud/docker$ sudo ./build.py 
Orc8r_cache image does not exist. Building...
FileNotFoundError: [Errno 2] No such file or directory: '/controller/Dockerfile'
[16591] Failed to execute script docker-compose

**Comment by bhtabor** [comment] 2019-08-01 19:31
This is the error I get:
`Building controller
Step 1/46 : ARG baseImage="ubuntu:xenial"
Step 2/46 : FROM ${baseImage} as base
ERROR: Service 'controller' failed to build: pull access denied for orc8r_cache, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by mpgermano** [comment] 2019-08-01 21:32
@bhtabor @shoaibbutt50 I'm unable to reproduce this. What OS, Docker, and Docker-Compose version are you using?

**Comment by bhtabor** [comment] 2019-08-02 06:08
Never mind it worked on a retry. Thanks. And I had to `pip install pyyaml` before running `./build.py`

**Comment by shoaibbutt50** [comment] 2019-08-02 10:25
i solved with this command sudo PWD=$PWD ./build.py

**Comment by mpgermano** [comment] 2019-08-06 16:40
Yeah pyyaml is one of our prereqs listed here: https://facebookincubator.github.io/magma/docs/basics/prerequisites. Closing.

**Closed as completed by mpgermano** 2019-08-06 16:40 UTC
