### ISSUE TITLE
[Qos]Configured Qos parameters are not getting updated in the respective IE's in PDUSessionResourceSetupRequest and PDU session establishment accept messages 

### ISSUE THREAD

**Issue by NeelimaKalpana** [magma/magma#10434] opened 2021-11-18 19:36 UTC
Version:  1.7.0-1637044298-4402e275
Affected Component: Access Gateway
Affected Subcomponent: AGW service
Deployment Environment: Vagrant (AGW)

Describe the Issue
Configured Qos parameters(QFI, Priority(ARP), Preemption parameters) are not getting updated in the respective IE's in PDUSessionResourceSetupRequest and PDU session establishment accept messages 

To Reproduce
1. Configure the APN parameters with values other than default values from NMS-Dash board.
2. Bind the APN to subscriber. 
3. Check that Subscriber info is getting updated with the configured values
4. Trigger the PDU-Session and check that PDU is coming up successfully  5. Configured Qos parameters are not getting reflected in Qos related IE. 

**Expected behavior**
Configured Qos-Profile values are getting reflected in the Qos-IE in the PDUSessionResourceSetupRequest and PDU session establishment accept messages

**Screenshots**
APN info from NMS
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/855507a8-c288-412f-9901-c9bc1f880a8a)

Subscriberinfo
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/0c2ec51e-f9b4-4870-9b3e-05ce7c7e6d30)

Syslog 
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/5f61a83f-285d-45d4-89a2-ff39e7f38b24)

PCAP:
![image.png](https://images.zenhubusercontent.com/6139f1931bcb9da2af1bf651/27ac3825-47d5-4c62-9ff9-9253ca3baf4a)

[https://app.zenhub.com/files/170803235/2aed76e9-e57e-4e5a-b732-4abd4e9a59bf/download](https://app.zenhub.com/files/170803235/2aed76e9-e57e-4e5a-b732-4abd4e9a59bf/download)

**Comment by moinuddin1980** [comment] 2021-12-03 17:32
In API SessionStateEnforcer::prepare_response_to_access()
We see that with the current implementation, the default value of Qos are getting set, if static Qos rule list are not configured.
From the pcap attached it is confirmed that all the Qos values are of default in nature.
So, the issue need fix from sessiond side also.

**Comment by GANESH-WAVELABS** [comment] 2021-12-09 06:16
[09-December-2021 : Ganesh . I ] :  From the provided logs we could see sessiond doesn't receive any static policies from PolicyDB. Added few debug logs in policyDB and got to know that PolicyDB also not having any static rules even though configured in NMS. so there was some some problem between Orc8r<-->PolicyDB communication via streamer API.  Below is the screen shot of PolicyDB logs:
![image.png]
(https://images.zenhubusercontent.com/608a39d761f99431f5047a77/43c1f335-b06a-4eca-b242-041ed430a136)
So Requesting @anusha-konda  and team to check from Orc8r point of view and transferring the ownership of this ticket from AGW to Orc8r. Feel free to add AGW if you find any AGW issue later.

**Comment by GANESH-WAVELABS** [comment] 2021-12-10 17:01
[10-December-2021 : Ganesh. I] : As suspected it is policydb look up issue. in Redis data is stored in the form "IMSI222700000000001", sessiond is sending request with "222700000000001" so  policydb code trying to find data from Redis with key as "222700000000001" [without IMSI prefix]. so policydb is not getting updated with static rules, due to this sessiond is not getting static rules so sessiond was setting default AMBR values, default Qos Values.

I modified the sessiond code and added few debug logs now I can see static rules are updating from Redis-->policydb-->sessiond-->pipelined. below are the screen shots.
1) below screen shot for Redis-->policydb and respond to sessiond:
![image.png](https://images.zenhubusercontent.com/608a39d761f99431f5047a77/b470faf9-9edb-484d-95a0-515f37406450)
2) below screen shot for sessiond --> pipelined grpc message:
![image.png](https://images.zenhubusercontent.com/608a39d761f99431f5047a77/dfc90b47-b875-424a-979a-4b5016d6c765)
3) below screen shot for pipelined received the static rules:
![image.png](https://images.zenhubusercontent.com/608a39d761f99431f5047a77/83c85578-e615-49ae-9bbc-ff86feb72ae6)

this is a known issue: zenhub task #10632 will have fix for this issue

**Comment by GANESH-WAVELABS** [comment] 2021-12-13 06:27
[13-December-2021 : Ganesh . I]: Fix for This issue can be tracked with #10632, so closing this issue.

**Comment by moinuddin1980** [comment] 2021-12-13 07:22
@NeelimaKalpana and team can confirm the behavior and comment after #10632 is merged.

**Comment by rupa455wavelabs** [comment] 2022-03-01 14:34
Hi @all, 

With latest master code, I have retested the TC and observed that Qos parameters are getting updated properly in the respective IE's PDUSessionresourceSetupRequest and PDU session establishment accept messages.Please find the attached the logs and pcaps for the same.

[https://app.zenhub.com/files/170803235/fcc847a6-6056-4f24-bc52-931f69694493/download](https://app.zenhub.com/files/170803235/fcc847a6-6056-4f24-bc52-931f69694493/download)

**Comment by rupa455wavelabs** [comment] 2022-03-01 14:34
Closing the issue

**Closed as completed by rupa455wavelabs** 2022-03-01 14:34 UTC
Labels: type: bug, product: 5g sa
