### ISSUE TITLE
[TVM] large no of Attach Rejects during Multiple UE Attach test

### ISSUE THREAD

**Issue by arun-magma** [magma/magma#4685] opened 2021-02-02 07:52 UTC
Title: - large no of Attach Rejects during Multiple UE test
Tested AGW & FEG Build: "fbf1d965"
Date: 2/1/2021
FB Task: T84054892 ( Pcaps enclosed)

[Description]
[gx_gy_combined_04_210201_070626-1.log](https://github.com/magma/magma/files/5909513/gx_gy_combined_04_210201_070626-1.log)

1. 32 UEs try attach with 3sec intervals between each UE attach.
2. Found Attach Reject with cause Network Failure, PDN connectivity Reject and Rejected by S-GW and P-GW
3. Test continued 2nd and 3rd Cycle of 32 UE attach and Attach rejects were observed in all cycles.

As per cumulative 3 cycle 32 UE attach Stats out of 96 attach req only 27 Were succeeded and rest 69 rejected
[TeraVM Stats]
07:08:57: verification fail:  ((received_Attach_Acc_=27) >= 32)  => False
07:08:57: verification fail:  ((received_Attach_Rej_=69) == 0)  => False

[PCAP Snap - Attach Rejects]
![image](https://user-images.githubusercontent.com/70725754/106567964-76e6eb00-64e7-11eb-8c4c-8775b9854d6e.png)

**Comment by mattymo** [comment] 2021-02-02 10:07
Possible duplicate of https://github.com/magma/magma/issues/4666

**Closed as completed** 2022-03-17 22:37 UTC
Labels: wontfix
