### ISSUE TITLE
Google Pixel 4 is unable to attach to the Network

### ISSUE THREAD

**Issue by shehzadalee** [magma/magma#4792] opened 2021-02-05 19:56 UTC
### Your Environment

- **Version:**1.3.2-1607014227-1462d960
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** MME
- **Deployment Environment:** bare-metal (AGW)

### Describe the Issue

Google Pixel 4 is unable to attach to the Network. The MME rejects Attach Request with Cause Code #99. Cause: Information element non-existent or not implemented (99).

Following are the observations from the logs:
1.) In the request the APN was not carried but the ESM Transfer Flag was included yet the MME didn't send "ESM Information Request Message" to request the UE for APN information.
3.) ESM information Request Procedure didn't take place but the MME didn't use default APN from the HSS Profile.
4.) EMM-REGISTERED w/o PDN connectivity: Not supported.

3GPP Reference: 24.301 - h10 Rel 17

**Expected behavior**
The MME should have initiated ESM information Procedure to get Session Management information from the UE. Since the ESM Transfer Flag was received.

OR the MME should have created default bearer using default APN in HSS Profile.

**Screenshots**
![Attach Reject - Pixel](https://user-images.githubusercontent.com/77636702/107079287-3c19d700-67b5-11eb-92b8-16435bf9c372.PNG)

**Comment by shehzadalee** [comment] 2021-02-11 03:41
@sourabh-nanoti

**Comment by shehzadalee** [comment] 2021-02-15 23:33
@sourabh-nanoti and @ulaskozat Hello, could you please help us with this issue. We observed Google Pixel 4 is unable to attach to Magma EPC.
[pixel4_attach_fail_IE_non_existent.zip](https://github.com/magma/magma/files/5984608/pixel4_attach_fail_IE_non_existent.zip)

**Comment by ulaskozat** [comment] 2021-03-06 05:57
@shehzadalee not sure which IE is the unsupported one by a quick scan. @jpad-freedomfi could you test pixel4 attach with debug mode on for the MME?

**Comment by jpad-freedomfi** [comment] 2021-03-07 02:11
@ulaskozat debug log attached. Not sure this is capturing what you want. is there a more verbose log than debug? like trace? 

[pixel4_debug_mme_log.txt](https://github.com/magma/magma/files/6096419/pixel4_debug_mme_log.txt)

**Comment by jpad-freedomfi** [comment] 2021-03-07 02:12
```
magma@FreedomFi-Gateway:~$ apt list magma -a
Listing... Done
magma/stretch-1.3.3,now 1.3.3-1614917907-371c6462 amd64 [installed]

also FYI I have updated this lab env to latest 1.3.3 version. That is what the latest log is based on. 
```

**Comment by ulaskozat** [comment] 2021-03-07 05:15
@shehzadalee please see my comment on the issue #4760. The culprit looks like MS Network Capability IE.

**Comment by ulaskozat** [comment] 2021-03-08 00:29
Okay, after @jpad-freedomfi's tests with my initial modifications, we pass through this stage but security mode command is rejected in the subsequent steps as played back UE capabilities do not match to what UE has sent. Will follow up on the issue once I can spare some time to have a fix for this...

**Comment by ulaskozat** [comment] 2021-03-08 06:21
@jpad-freedomfi sent you 2 additional files for testing to fix UE capability replay.

**Comment by jpad-freedomfi** [comment] 2021-04-05 20:57
[pixel4_v14_agw_attach_fail.pcapng.zip](https://github.com/magma/magma/files/6260621/pixel4_v14_agw_attach_fail.pcapng.zip)

@ulaskozat here is the pixel4 again on v1.4.0-1615912803-6bca6402

**Comment by ulaskozat** [comment] 2021-04-06 18:51
@jpad-freedomfi can you also provide mme log in debug mode?

**Comment by jpad-freedomfi** [comment] 2021-04-09 06:43
@ulaskozat new pcap and mme.log in debug mode. 
[pixel4_on_v1.4.zip](https://github.com/magma/magma/files/6283672/pixel4_on_v1.4.zip)

**Comment by ulaskozat** [comment] 2021-04-13 17:02
@jpad-freedomfi  I went through the steps where we decode the attach requests and looks like we are actually processing each IE type. I will need to code some unit tests to see what I am missing by eyeballing...

**Comment by jpad-freedomfi** [comment] 2021-04-13 19:43
Ok, thanks @ulaskozat. Not sure if it's good to post here or to make a new issue, but we have another Rel 15 5G/4G unit showing the same IE not implemented. I'll put logs here as the error in mme debug log is the same

`Failed to decode L3 EMM message 0x41 (-2)`

[quactel_rm502Q_AE_attach_fail.zip](https://github.com/magma/magma/files/6306292/quactel_rm502Q_AE_attach_fail.zip)

**Comment by talkhasib** [comment] 2021-05-07 02:16
@jpad-freedomfi 
I was able to reproduce the decoding problem on 1.4
Issue seems to be resolved on Release 1.5. The fix was not backported to 1.4

Can we get the partner upgraded to 1.5?

**Comment by jpad-freedomfi** [comment] 2021-05-07 02:17
@talkhasib Thanks for looking into this. We are a while from 1.5. We are getting ready to do 1.4 in production orc8r and AGWs. 
Can we get the change backported to 1.4?

**Comment by talkhasib** [comment] 2021-05-07 22:11
@jpad-freedomfi 
Backports are only done for hot patches/critical fixes.
Rel-15 support is a major feature that spanned multiple PRs. It will be nearly impossible to cherry pick them cleanly into 1.4

**Comment by jpad-freedomfi** [comment] 2021-05-14 18:11
this has been retested in 1.5.0-1619628161-f023455f and Pixel4 how works. We can close this.

**Closed as completed by jpad-freedomfi** 2021-05-14 18:11 UTC
