### ISSUE TITLE
Use Github Actions container directive for the Bazel Build & Test job

### ISSUE THREAD

**Issue by jheidbrink** [magma/magma#14579] opened 2022-11-30 10:12 UTC
In #14562 we upload docker images with pre-filled Bazel caches. This will significantly increase the time to download the container images in workflows. We currently use [addnab/docker-run-action](https://github.com/magma/magma/blob/8374468f07ea77c7e15cd3ea89af709e38e7b913/.github/workflows/bazel.yml#L110) to run the bazel-base image. Check if we can use the `container:` directive instead, as we do [here](https://github.com/magma/magma/blob/8374468f07ea77c7e15cd3ea89af709e38e7b913/.github/workflows/magma-build-3rd-party.yml#L51). Maybe this will cache the downloaded image between workflow runs and thus lead to faster workflows.

This would also make it simpler to set step outputs from within the container. Currently we have to use a [workaround](https://github.com/magma/magma/blob/8374468f07ea77c7e15cd3ea89af709e38e7b913/.github/workflows/bazel.yml#L450) to do that.

**Comment by LKreutzer** [comment] 2023-01-09 14:04
Duplicate of https://github.com/magma/magma/issues/14274

**Closed as not planned by LKreutzer** 2023-01-09 14:04 UTC
Labels: bazel, willfix
