### ISSUE TITLE
User access restriction not working on NMS

### ISSUE THREAD

**Issue by ardzoht** [magma/magma#1149] opened 2020-02-03 17:52 UTC
### Your Environment

- **Version:** v1.0.0, on revision 6c1b189d3c1d5c9582b22da06b8e8a04aaff5ea8
- **Affected Component:** NMS
- **Deployment Environment:** AWS (orc8r)

#### Arcangelli reported that user access is not working for them, to reproduce 2 users and 2 networks were created, each user should only have access to one network. 

**Expected behavior**
Each user should only have access to own network, it was reported that this is not filtered and both users can access all networks.

**Comment by ardzoht** [comment] 2020-02-03 17:54
Creating this to track issue, NMS team detected a bug on the specified revision, Arcangelli will pull latest changes and update their deployment, should be fixed with the update.

**Comment by xjtian** [comment] 2020-02-04 03:21
Is this a confirmed bug on 1.0.0? Just want to double-check the version that we're running in that cluster. If it is, we probably have to pick the fix into the release branch for a 1.0.1 release.

**Comment by ardzoht** [comment] 2020-02-04 19:05
Double checking and the revision they're using (https://github.com/facebookincubator/magma/commit/6c1b189d3c1d5c9582b22da06b8e8a04aaff5ea8) it's before 1.0.0, the bug is fixed on the v1.0 release.

**Comment by xjtian** [comment] 2020-02-05 01:53
Closing this out since it's fixed on the release branch

**Closed as completed by xjtian** 2020-02-05 01:53 UTC
Labels: type: bug, component: nms
