### ISSUE TITLE
ModuleNotFoundError: No module named 's1ap_types'

### ISSUE THREAD

**Issue by kimberqiqi** [magma/magma#13839] opened 2022-09-05 09:07 UTC
### Your Environment
- **Version:**
![image](https://user-images.githubusercontent.com/109064396/188411306-43b8809f-5279-41a6-a69a-1a80e0ebdc29.png)
- **Affected Component:**  Access Gateway
- **Affected Subcomponent:** Orchestrator pod/service or AGW service
- **Deployment Environment:** e.g. AWS (orc8r), local docker-compose (orc8r), bare-metal (AGW), Vagrant (AGW)

### Describe the Issue
Source files：https://github.com/magma/magma/tree/master/lte/gateway/python/integ_tests
I was doing SAP integration testing and when I was running the tests, I found that whether I did a single or all of the tests, there were errors.
![image](https://user-images.githubusercontent.com/109064396/188412090-e4155da5-d537-4434-bbe0-baf46006d0fd.png)

#### To Reproduce

1. vagrant up magma_test && vagrant ssh magma_test
2. cd $MAGMA_ROOT/lte/gateway/python && make
3. cd integ_tests && make
4. make integ_test
5. See error

#### Expected behavior

find the moudle s1ap_types

**Comment by mpfirrmann** [comment] 2022-09-07 06:39
I cannot reproduce the bug, the tests are running on my machine.
For context: Magma's `S1APTester` repo is cloned (and build) during the provisioning of the test VM. The `s1ap_types.py` is located in `/home/vagrant/s1ap-tester/bin`. This path is added to the `PYTHONPATH` on-the-fly anytime a test is started via `make` (as seen in your screenshot: `PYTHONPATH=:/home/vagrant/s1ap-tester/bin`).
What is your `ll /home/vagrant/s1ap-tester/bin/`?

**Comment by kimberqiqi** [comment] 2022-09-07 09:43
My s1ap-tester is in the /home/vagrant directory，but I can't find the s1ap_types.py
![image](https://user-images.githubusercontent.com/109064396/188845200-57be478f-769e-41de-8ab2-cf0a0269799e.png)
My PYTHONPATH :
![image](https://user-images.githubusercontent.com/109064396/188847110-f8bd621d-d8d4-4c3d-b496-b3284426a8b4.png)

**Comment by mpfirrmann** [comment] 2022-09-07 09:48
Try running 
`vagrant@magma-test:~/magma$ ./lte/gateway/deploy/roles/magma_test/files/update_package.sh`
This should recreate the `s1ap_types.py`.

**Comment by kimberqiqi** [comment] 2022-09-07 09:56
Thank you so much! The command you gave is very effective, s1ap_types.py this file is successfully generated!

**Comment by kimberqiqi** [comment] 2022-09-07 10:39
sorry to bother you again，but it occurs another problem
![image](https://user-images.githubusercontent.com/109064396/188858348-669e9d69-8c55-41a5-8ae0-0900b35d1d4b.png)
Why did it appear？

**Comment by mpfirrmann** [comment] 2022-09-07 10:48
Where does the `print()` statement come from? Line 29 in `s1ap_utils.py`. It is not checked in on master. Did you add it yourself? Maybe delete it.

**Comment by kimberqiqi** [comment] 2022-09-07 10:52
Yes，I will delete it .I have add it before.

**Comment by kimberqiqi** [comment] 2022-09-07 12:15
When I try to do this:
sudo su
make integ_test TESTS=s1aptests/test_attach_detach.py
it occurs new unknown error:
![image](https://user-images.githubusercontent.com/109064396/188874998-1b4af4ae-7241-4d49-b05a-2d79422d98ef.png)
Is it occurs because I have changed the IP of the magma_test.
because it had occured one error like this:
![image](https://user-images.githubusercontent.com/109064396/188875505-bc4f45b7-27cd-42d2-9f94-0aefa809bb5a.png)
so I have change one IP of magma_test:
![image](https://user-images.githubusercontent.com/109064396/188875866-6ed70712-c768-4703-bb05-8053bf52d7b8.png)

**Comment by mpfirrmann** [comment] 2022-09-08 10:44
Ok, so this is a bug on your setup and not in magma, so I close this issue.
The test VMs need the IP addresses as described in the `Vagrantfile` for them to work.

**Closed as completed by mpfirrmann** 2022-09-08 10:44 UTC
Labels: type: bug
