### ISSUE TITLE
no datapath on subscriber reattach, production customer, Magma 1.7 LTE

### ISSUE THREAD

**Issue by Radula76** [magma/magma#14064] opened 2022-10-01 03:27 UTC
### Your Environment

- Magma 1.7
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** AGW service
- **Deployment Environment:** bare-metal (AGW), Vagrant (AGW)

### Describe the Issue

Customer reported user unable to do any traffic, they had rebooted the CPE (=customer premise equipment = mobile phone) but still no traffic.
Logging into the AGW we could see that the datapath's had not been setup correctly.
we issued an s6a delete, the user re-attached to the network, but still the datapath's did not setup correctly and no payload was possible for the user.
A technician was sent onsite and the SIM card was replaced, solving the issue.

#### To Reproduce

We believe it has something to do with going idle, or partially idle in the network. subsequent connection attempts are successful but the redis database or pipelined or ovs is not being cleared out and reset enough for the new sessions to be setup correctly.

#### Expected behavior

Users should have all session variables reset on re-attach/reboot.
We would also like extra steps to debug this problem.
Would it be possible to clear just this subscriber data from redis rather than the whole redis purge?  we have 87 subscribers active on this AGW.

#### Screenshots
![Ue traffic orc8r](https://user-images.githubusercontent.com/80013777/193385448-bf930444-883b-49c4-a02c-e4a2b05dba5f.jpg)

#### Additional context
[subscriber flows.txt](https://github.com/magma/magma/files/9689439/subscriber.flows.txt)
[user_trace.txt](https://github.com/magma/magma/files/9689440/user_trace.txt)
[Subscriber redis.txt](https://github.com/magma/magma/files/9689441/Subscriber.redis.txt)

**Comment by sebathomas** [comment] 2022-10-20 07:46
Hi @Radula76, thanks for opening this ticket. We're starting to have a look at the bug report.

We'll try to reproduce the state but we only have a dev setup, no production AGW.

Magma team tasks
- [ ] Go through the logs and report and try to understand how the subscriber ended up in this state.
- [ ] Document how to delete a single subscriber from an AGW without a Redis purge.
- [ ] Prepare internal review.

**Comment by crasu** [comment] 2022-10-31 17:58
@Radula76 Could you sent us an excerpt from your pipelined log and tell us which NetworkServices (in gateway.mconfig) you have active?

A dump of your flows would be helpful as well.
sudo ovs-ofctl dump-flows  gtp_br0|grep <ue ip>

**Comment by Radula76** [comment] 2022-11-07 22:18
We are not seeing this fault as much anymore.  We have offloaded some eNB's from the AGW.  We had 16 eNB's connected to our AGW and now only have 11.  We had about 90 Subscribers which is down to about 60 with the offload to a new AGW.
We are monitoring the situation.
We will be upgrading the customer to 1.8 in the next 2 weeks as well.

**Comment by crasu** [comment] 2022-11-08 07:28
@Radula76 Thank you for your response. I am closing this ticket for now. Feel free to reopen the ticket if the issue occurs again.

Note: It looks like the entries from the enforcement table (table=13) were missing for this subscriber. Why this happens is unclear.

**Closed as completed by crasu** 2022-11-08 07:28 UTC
Labels: type: bug
