### ISSUE TITLE
[subscriberdb]: not synching after manually deleting some subscribers

### ISSUE THREAD

**Issue by uri200** [magma/magma#9029] opened 2021-09-09 16:46 UTC
On `terravm1_agw_network` at staging we have few subscribers configured on the db. Those are used for some regression testing.

https://magma-admin.nms-staging.magma.etagecom.io/nms/terravm1_agw_network/subscribers/overview/config

To test subscriber db synch we deleted all but one subscriber (IMSI888881234632900) from local AGW using  `subscriber_cli.py delete IMSI888881234632901`

AGW is running `1.7.0-1631129923-9768e7e7`

After waiting for more than an hour, subscribers never showed up again. Restart of AGW did not help either.
```
magma@ubuntuAGW:/var/opt/magma/configs$ subscriber_cli.py list
IMSI888881234632900
```

subscriberdb log showing the digest from `terravm1_agw_gateway1` with hwid `e88ee8cc-aa8b-4189-8f14-41d83de9ce4e`
```
Sep 09 09:41:24 ubuntuAGW subscriberdb[2210272]: INFO:root:Starting subscriberdb...
Sep 09 09:41:24 ubuntuAGW subscriberdb[2210272]: INFO:root:Listening on address 127.0.0.1:50051
Sep 09 09:41:24 ubuntuAGW subscriberdb[2210272]: INFO:root:get digest stored in gateway: eaBZHB+JazOTinLEp2TPbA==1B2M2Y8AsgTpgAmY7PhCfg==
Sep 09 09:41:25 ubuntuAGW subscriberdb[2210272]: INFO:root:Running s6a over grpc
Sep 09 09:41:25 ubuntuAGW subscriberdb[2210272]: INFO:root:starting s6a_proxy servicer
Sep 09 09:41:48 ubuntuAGW subscriberdb[2210272]: INFO:root:GRPC message:
Sep 09 09:41:48 ubuntuAGW subscriberdb[2210272]:   magma.orc8r.Void {}
```

![image](https://user-images.githubusercontent.com/16157139/132727381-c566626a-b078-4e6e-bf28-6fdceb04d6df.png)

**Comment by electronjoe** [comment] 2021-09-09 17:28
What git hash were you running on the AGW?

I'm not sure if this is governed by the same `sync_interval` that was rolled back recently in https://github.com/magma/magma/commit/05cbccfa738fb29c63677629ad59c1164acc1111, hence my ask.

**Comment by electronjoe** [comment] 2021-09-09 17:39
@mstre123 pointed out that this may be related to https://github.com/magma/magma/pull/7664 and or https://github.com/magma/magma/pull/7719, though those landed a *long* time ago.

**Comment by uri200** [comment] 2021-09-09 19:30
Hey @electronjoe hash on agw is latest available from today (`1.7.0-1631129923-9768e7e7`)

This issue may be caused by the changes on how subscriber db synchronization procedure that @hcgatewood added few weeks ago. I think `sync_interval` is only related to state service which, per my understanding, does not touch subscribers


By the way, as @ulaskozat mentioned, a workaround to force the resync is to delete subscriber*.db files

```
magma@ubuntuAGW:/var/opt/magma$ sudo rm -rf  subscriber*
```

**Comment by hcgatewood** [comment] 2021-09-16 21:19
This is most likely due to how we sync subscribers now -- it's no longer a naive full-copy replication https://magma.github.io/magma/docs/next/orc8r/dev_sub_digests

The root cause here is we are relying on basic functionality at the AGW that doesn't have a test (? or, at least, doesn't fully express the expectations).

I will try to get up a PR later this week. Basically, deleting a subscriber also needs to delete the accompanying digest

**Comment by uri200** [comment] 2021-09-17 17:14
Not having a test is fine for this kind of tools. But it is important to play with the system when a feature impacts the gateways.

My recommendation is every time there is a change on orc8r that impacts the gateway, try to go to a lab and run some manual test using a lab+staging or with your local setup (agw + orc8r). Unfortunately, golang unit test are not enough to catch cross platform issues.

Note I am working to fix some issues we have on our local environment to spin up a AGW+orc8r on our dev machines. Once it is done, you will be able to check your changes using just your mac and we can even create automated tests for those tools

**Comment by hcgatewood** [comment] 2021-09-29 02:56
We did indeed run some manual sanity checks. But that said, it's not reasonable to manually test every tool + functionality the gateway provides

This is the value of automated tests -- aside from actually testing things, it serves as an explicit, go/no-go documentation of the expected affordances of a system. Meaning it's how we all communicate to each other how the different components should work 🙂 So this to say: agreed that we should run manual high-level sanity checks in scenarios like this, but once we get to the level of particular pieces of functionality -- if it's not important enough for an automated test, then it's not important enough to manually test

**Closed as completed** 2021-09-29 22:43 UTC
Labels: type: bug
