### ISSUE TITLE
[orc8r][1.4] Post Upgrade no events or log collection on orc8r

### ISSUE THREAD

**Issue by sudhikan** [magma/magma#4637] opened 2021-01-28 17:29 UTC
### Your Environment

- **Version:** 1.4
- **Affected Component:** Orchestrator and NMS
- **Affected Subcomponent:** fluentd
- **Deployment Environment:** AWS (orc8r)

### Describe the Issue

After the 1.4 upgrade, we added a few gateways to the network and noticed that we were not getting any alerts or logs from the gateways. It seems that the agw is not able to connect with the fluentd service in the orc8r.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here (e.g. logs).
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/38921899/106175690-43a10680-614b-11eb-9b30-16abd9e06a89.png">

**Comment by karthiksubraveti** [comment] 2021-02-01 14:20
@sudhikan I'm closing this issue for now. I believe this has been root caused to an underlying network issue.

**Closed as completed by karthiksubraveti** 2021-02-01 14:20 UTC
Labels: apply-v1.4
