### ISSUE TITLE
s1ap_handle_sctp_disconnection assert hit 3 times in a row

### ISSUE THREAD

**Issue by talkhasib** [magma/magma#5211] opened 2021-02-27 01:19 UTC
Was the assert meant to prevent this from cascading?
See attached cores in first comment

Reproduced by running test_continuous_random_attach.py multiple times

**Comment by talkhasib** [comment] 2021-02-27 01:22
https://drive.google.com/drive/folders/1dB9auf2HigbSgm2PU5sT6bD86L_zF2Zm?ths=true

**Comment by ssanadhya** [comment] 2021-03-31 20:05
Closing this as it is a duplicate of https://github.com/magma/magma/issues/4993

**Closed as completed by ssanadhya** 2021-03-31 20:05 UTC
Labels: mme:core
