### ISSUE TITLE
[AMF]: PDU Session not getting connected while attaching to New GNB

### ISSUE THREAD

**Issue by panyogesh** [magma/magma#14729] opened 2022-12-20 14:29 UTC
[https://app.zenhub.com/files/170803235/d2f35afe-92f5-4511-91d4-a8dcafc71dcf/download](https://app.zenhub.com/files/170803235/d2f35afe-92f5-4511-91d4-a8dcafc71dcf/download)

**Comment by panyogesh** [comment] 2022-12-20 14:30
[https://app.zenhub.com/files/170803235/33942115-0940-4980-80ef-4a25088d832c/download]

**Comment by panyogesh** [comment] 2022-12-20 14:30
PDU Sessions not coming up.  Refer to slack discussion https://magmacore.slack.com/archives/C020S2QB6N8/p1671534180581009?thread_ts=1657804100.315779&cid=C020S2QB6N8

**Comment by jao-tm** [comment] 2022-12-21 10:07
Seems to be related to slicing mismatch. When SD is changed to 0xFFFFFF (default value) in AGW and gNB the session is created. Did not work with SD=1

**Comment by prabinakpattnaik** [comment] 2022-12-21 10:17
As per provided logs, pdu session is established successfully.

000571 Tue Dec 20 14:35:03 2022 7F4350DF1700 WARNI AMF-AP tasks/amf/amf_app_handler.cpp   :0538    Warning PTI from sessiond 
000572 Tue Dec 20 14:35:03 2022 7F4350DF1700 INFO  NAS-AM tasks/amf/amf_fsm.cpp           :0304    [STATE_PDU_SESSION_ESTABLISHMENT_ACCEPT] Event triggered, PDU session state switches from [CREATING] to [ACTIVE] and UE state :[REGISTERED_CONNECTED]

**Comment by jao-tm** [comment] 2022-12-21 10:38
Correct, but due to mismatch in S-NSSAI parameter SD the UE request release immediately after PDU session establishment accept. The reported release cause value in the AMF logs is 12, but the pcap files (packet 159) show that the release cause is 39, slice-not-supported. The closes indication to this is the log entry "PLMN is not configured."

At NGSetupRequest (packet 5): s-NSSAI sST: 01, sD: 000001. At PDU Session Request (packet 157): Allowed s-nSSAI is sst:1, no sD.

[mme.log](https://github.com/magma/magma/files/10276902/mme.log)
[syslog.log](https://github.com/magma/magma/files/10276904/syslog.log)
[debug.zip](https://github.com/magma/magma/files/10276908/debug.zip)

**Comment by prabinakpattnaik** [comment] 2022-12-21 10:50
Yes, magma is supported default slice value only ```("ffffff" and type is 1)```.

**Comment by jao-tm** [comment] 2022-12-22 09:09
Maybe this should be reflected in the documentation? As it is possible to set the SD value in the Orc8r, it implies that different SD values are supported. Perhaps the SD value field in the Orc8r should be locked to "ffffff", or removed?

**Comment by shashidhar-patil** [comment] 2022-12-27 04:41
Tested by Configuring  sST: 01, sD: 000001, the PDU session establishment was successful. 

Attaching the pcap:
[Debug_14729.zip](https://github.com/magma/magma/files/10305946/Debug_14729.zip)

**Comment by shashidhar-patil** [comment] 2023-01-16 13:40
Closing this issue as the issue was not reproducible locally. Please open a new issue if this issue occurs again.

**Closed as not planned by shashidhar-patil** 2023-01-16 13:40 UTC
Labels: type: bug, component: agw, product: 5g sa
