### ISSUE TITLE
agw: sctp_sendmsg error Invalid argument

### ISSUE THREAD

**Issue by wallyrb** [magma/magma#9153] opened 2021-09-17 02:58 UTC
### Your Environment

- Version: 1.5.2-1624485681-ae972900, 1.5.3
- Affected Component(s): Access Gateway
- Affected Sub-Component(s): mme, sctpd
- Deployment Environment: bare-metal(AGW)
- eNB Model: Fiberhome TDRU364FAD
- CPE Model: LTE Outdoor BBU - EBB5236 / MRRU - TDRU364FAD-P.
### Describe the Issue

User is unable to attach to AGW, getting below error

- mme logs

`176666 Wed Sep 15 14:16:40 2021 7FA775DE9700 ERROR S1AP   tasks/s1ap/s1ap_mme_itti_messagi:0134  ERROR: Failed to send S1AP message to eNB. mme_ue_s1ap_id =  5729
`

- syslogs

```
Sep 15 14:16:40 agwFB sctpd[2841]: I0915 14:16:40.173961  3436 sctpd_downlink_impl.cpp:76] SctpdDownlinkImpl::SendDl starting
Sep 15 14:16:40 agwFB sctpd[2841]: I0915 14:16:40.174021  3436 sctp_connection.cpp:82] sctp_sendmsg error (22): Invalid argument

```

Note: There is another issue as consequence of this, attach request after this error are ignored

`Hit 3GPP TS 24_301R10_5_5_1_2_7_e__2 : Ignore the this duplicate ATTACH REQUEST message, continue with the previous attach procedure`

**Expected behavior**
User should be able to attach to the network
User shouldn't be kept in a loop trying to attach again and again due to requests being ignored

**Additional context**
Logs can be found in internal task T100920563

**Comment by pshelar** [comment] 2021-10-01 23:07
@ardzoht  @ulaskozat this looks like 3GPP control plane issue, have you seen this before?

**Comment by ulaskozat** [comment] 2021-10-02 00:06
assigning to @pruthvihebbani. Haven't seen this sequence before where `ERROR: Failed to send S1AP message to eNB` is seen. @wallyrb are all other attach requests failing for this UE afterwards?

**Comment by wallyrb** [comment] 2021-10-02 00:29
@ulaskozat correct, after this failure, UE keep trying to attach but it gets ignored. Similar messages as below get repeated several times:
(I deleted IMSI information below)

```
176778 Wed Sep 15 14:17:05 2021 7FA778DEF700 INFO  NAS-EM tasks/nas/emm/Attach.c          :0220    ATTACH REQ (ue_id = 0x00001666) 
176779 Wed Sep 15 14:17:05 2021 7FA778DEF700 INFO  NAS-EM tasks/nas/emm/Attach.c          :0239    EMM-PROC:  ATTACH - EPS attach type = IMSI (1)
176780 Wed Sep 15 14:17:05 2021 7FA778DEF700 NOTIC NAS    tasks/nas/emm/Attach.c          :0500    Hit 3GPP TS 24_301R10_5_5_1_2_7_e__2 : Ignore the this duplicate ATTACH REQUEST message, continue with the previous attach procedure

```

**Comment by ulaskozat** [comment] 2021-11-02 04:50
@ssanadhya can you update the target date for this to close?  can you provide an update on any blockers for resolution? (cc @aswin-alexander)

**Comment by ssanadhya** [comment] 2021-11-02 21:01
@ulaskozat, I have added this issue to current sprint (target date Nov 19). @wallyrb shared new logs in the internal task, so nothing blocking me at the moment.

**Comment by ssanadhya** [comment] 2022-02-07 18:02
@wallyrb , Task [T100920563](https://www.internalfb.com/intern/tasks/?t=100920563) is closed and this issue is marked as mitigated. Closing this issue for now. 

If this recurs, please re-open the issue with steps on how to reproduce it.

**Closed as completed by ssanadhya** 2022-02-07 18:02 UTC
Labels: type: bug, fbcpp
